### ISSUE TITLE
Add Iterative Deepening as Search Strategy to ATP

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#104]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2011 18:44:43_

During a discussion about nondeterministic proof search, Tomer and me talked about having diffferent search strategies to reduce the state explosion problem of BFS.

This task should add a new trait formalizing A* Search, which does DFS up to a given bound, then explores different paths and after their exhaustion increases the bound.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=104_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2011 09:45:26_

**Owner:** shaolintl

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2011 09:45:46_

**Owner:** Martin.Riener

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 10, 2011 07:59:28_

A* is something different, so I removed it...

**Summary:** Add Iterative Deepening as Search Strategy to ATP  
**Labels:** Type-Enhancement Priority-Low

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:39:59_

**Labels:** Component-TheoremProvers

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 23, 2011 13:42:35_

**Labels:** Milestone-Release3.0

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:38:07_

**Status:** New

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:38:28_

**Owner:** bruno...@gmail.com

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:43:53_

**Owner:** ---

**Comment by gebner** [comment]
No longer relevant since ATP was removed.
