### ISSUE TITLE
Upward Shifting of Equality Rules

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#141]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on August 23, 2011 16:22:55_

What should the feature do? shift equality inference upward, as the old C++ ceres used to do.

THis was needed to avoid paramodulation when refuting the clause set.

It might also be needed for reductive cut-elimination. Which packages, classes and methods should be created?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=141_

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 23, 2011 13:12:14_

**Labels:** Component-ProofTransformations

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on September 06, 2011 03:01:13_

**Blocking:** 129

**Comment by shetzl** [comment]
adding CCs from google code: @frehn

**Comment by shetzl** [comment]
Implemented in PR #627.
