### ISSUE TITLE
Implementation of Resolution Calculus/Labeled Resolution Calculus

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#16]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on October 07, 2009 10:48:55_

on top of top level calculus

_Original issue: http://code.google.com/p/gapt/issues/detail?id=16_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 23, 2009 06:32:18_

**Status:** Started

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 23, 2009 08:45:36_

I will read andrews paper before I implement this and as it does not affect CERes I
will move it to next release

**Labels:** -Milestone-Release1.0 Milestone-Release2.0

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on October 13, 2010 06:16:29_

According to our next milestone Calculi for Res and Res_al should be implemented

**Summary:** Implementation of Resolution Calculus/Labeled Resolution Calculus  
**Status:** New  
**Owner:** fraini

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on August 11, 2011 03:17:20_

Since the resolution calculus works with sequents, and these are being redone in issue #117 , that issue blocks this issue.

**Blockedon:** 117

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 06:31:43_

**Labels:** Milestone-Release3.0

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 12:07:33_

**Labels:** Type-Feature

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:20:13_

**Labels:** Component-LogicalDataStructures

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:20:47_

**Labels:** -Component-Logic

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on August 23, 2011 07:05:26_

**Status:** Started

**Comment by shetzl** [comment]
IMHO we can consider this issue closed as the implementation of resolution calculi fulfils the current needs of the system.

**Comment by quicquid** [comment]
Hi Stefan, just for completeness: The labeled hol resolution calculus Ral is implemented in syntax.calculi.ral , there is also a conversion from robinson resolution to Ral in algorithms.robinson.RobinsonToRal . The rules of Ral are independent of Robinson resolution, i.e. algorithms on Robinson resolution cannot be directly transferred to Ral.
