### ISSUE TITLE
evaluation of schematic formulas/clause sets

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#162]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on August 30, 2011 13:18:45_

What should the feature do? There should be functions that take a SchemaFormula and an Integer and output a HOLFormula (that represents its evaluation for that integer). The same goes for a set of schematic clauses.

Note: We have some ``inductive'' or ``primitive recursive'' definitions (e.g. the characteristic clause set for schemata uses them), which are encoded at the moment in the object language. The functions described above should OPTIONALLY also ``evaluate'' these definitions. It seems that it would be good to have some technical means to deal with these definitions, which we do not have yet. Which packages, classes and methods should be created? Among others, a function

evaluate( f : SchemaFormula, i : Int ) : HOLFormula

_Original issue: http://code.google.com/p/gapt/issues/detail?id=162_

**Comment by shetzl** [comment]
adding CCs from google code: @frehn

**Comment by gebner** [comment]
No longer relevant after the removal of the schema code.
