### ISSUE TITLE
IndexedPredicate, ClauseSetSymbol

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#165]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on August 31, 2011 03:53:05_

Dear friends,

finally we can display nicely also the cut-configuration in the CL variables when computing projections.
I suggest to add the case for clauseSetSymbol in the unapply method of the IndexedPredicate in order to distinguish easy betwen the 2 different objects which we create using IndexedPredicate.

Also clauseSetSymbol should be not in Struct but rather in syntax.language.schema?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=165_

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on September 12, 2011 05:06:57_

**Status:** Started

**Comment by shetzl** [comment]
adding CCs from google code: @frehn

**Comment by gebner** [comment]
This seems to be left over from a few years ago and probably no longer relevant since @quicquid is rewriting the CERES code now.

**Comment by quicquid** [comment]
This is part of the schematic ceres which will still with the old calculus. Is there a "won't fix" category to keep this documented?

**Comment by gebner** [comment]
Unfortunately no, you can only close issues as "closed"...  However, the closed issues are still searchable.

**Comment by quicquid** [comment]
ok, then sorry for reopening :)
