### ISSUE TITLE
Improve Apply Methods of the Inference Rules

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#171]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on September 06, 2011 12:41:31_

I have noticed the following lack of uniformity in the implementation of "apply" methods in inference rules:

1) "apply" methods of propositional rules take only the auxiliary formulas and construct/compute the main formula.

2) "apply" methods of quantifier rules, on the other hand, expect the main formula to be given as another argument. (Why is this so? In principle, the main formula could also be recomputed from the auxiliary formula together with an indication of which terms in the auxiliary formula should be replaced by a quantified variable.). They also check that the given main formula and the given auxiliary formula are "compatible", by calling an "assert" that checks whether instantiating the main formula gives a formula that is syntactically equal to the auxiliary formula.

3) "apply" methods for equational rules are similar to those of quantifier rules, in the sense that it is necessary to pass the main formula as an argument. However, they don't check their own correctness as the quantifiers rule do with an "assert". (This is even a bit strange. As Giselle noticed today, the implementations of EqualityLeft1 and EqualityLeft2 are exactly the same, since in theory they only differ in the direction in which the equality is used and  in practice the correctness of the direction is simply not checked. Indeed, they check nothing at all and the responsibility of computing a correct main formula is left completely to the programmer.)

I think option 1 above is the most useful. At least, that is the kind of behaviour that I need (or that would be more convenient to me) when implementing "eliminateDefinitionRules". And I think this behaviour is needed whenever one is reconstructing a proof in a top down way and making changes that may affect the auxiliary formulas: in such cases, it is convenient to simply reapply the inference rule to the new auxiliary formula, and let the inference recompute the new main formula.

What do you think?

As I said, I need this behaviour for "eliminateDefinitionRules" (and I think), and therefore I am thinking about overloading the "apply" method for quantifier rules (and later on, equality rules too)... However, since I believe this kind of issue is quite common, I imagine that something similar (i.e. recomputing the main formula after new premises have been computed) might have already been implemented somewhere else, perhaps as part of some other algorithm that also does proof transformations in a top-down way.  So, if you know where I can find this code, please let me know!

This is related to Issue 48 . 
It blocks Issue 167 . 
And the implementation of an apply method for equality rules blocks Issue 133 .

_Original issue: http://code.google.com/p/gapt/issues/detail?id=171_

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on September 06, 2011 03:42:02_

**Blocking:** 167

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on September 06, 2011 03:42:54_

**Blocking:** 133

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:49:27_

**Status:** Accepted

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 10, 2011 09:22:41_

**Owner:** ---  
**Cc:** bruno...@gmail.com

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on July 17, 2012 09:59:40_

**Blocking:** gapt:133

**Comment by shetzl** [comment]
adding CCs from google code: @frehn @gisellemnr

**Comment by gebner** [comment]
This is obsolete now with lkNew.
