### ISSUE TITLE
export schema

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#172]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on September 09, 2011 14:11:23_

Hi friends,

I can not see in the current exporter how do we export a schema proof. Even if we want to export an instance of a schema proof, we can not do this because of the BigAnd and BigOr. I will add this feature. Probably unfolding a schema into a formula for a given instance of the parameter? Or in the exporter, which needs a convention for the xml?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=172_

**Comment by gebner** [comment]
No longer relevant after the removal of the schema code.
