### ISSUE TITLE
FeatureVector in subsumption is not thoroughtly tested

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#179]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 17, 2011 12:15:25_

The test file for the feature vector contains only object creation with no tests. Such algorithms must be tested before usage.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=179_

**Comment by gebner** [comment]
No longer relevant since ATP was removed.
