### ISSUE TITLE
Vector subsumption does not extend subsumption manager!

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#180]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 17, 2011 12:17:49_

how can it be used as a manager if it does not extend the manager interface?!

_Original issue: http://code.google.com/p/gapt/issues/detail?id=180_

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on September 17, 2011 04:09:43_

If possible don't use it for now. I have to deal with another things. Soon I will come again to it.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 17, 2011 13:12:58_

sure. it is not being used so far due to several problems and it is not urgent.

**Comment by gebner** [comment]
No longer relevant since ATP was removed.
