### ISSUE TITLE
XML exporter

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#185]
_From [mrukh...@gmail.com](https://code.google.com/u/105746934973897711712/) on October 18, 2011 14:05:21_

There should be possibility to save output in xml file. For this reason we should decide which dtd we want to use. Old ceres dtd or should we create new one? Anyway we need some extension for schematic LK.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=185_

**Comment by newca12** [comment]
_From [mrukh...@gmail.com](https://code.google.com/u/105746934973897711712/) on October 20, 2011 03:47:46_

I have made some progress but there are some basic problems again. Now I can export propositional proof into xml file, but prooftool can't parse that file, because parser takes into account permutation rules to find auxiliary formulas and construct principal formula. I can't write permutation rules in the file, because they do not exists in the proof! Any ideas?

Second problem is about Atom object of hol.scala file. Unapply method of this object is implemented in such a way, that every propositional or first-order formula (ex. A /\ B, -A -> B ) matches to HOL Atom, why???

**Status:** Started

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 20, 2011 04:48:26_

Two ideas:

1) compute the permutations based on the positions where the formula occurrences occur in the Seq. This will allow you to write permutation rules in the XML even though there are no permutation rules in the proof.

2) change the parser, so that it does not rely on permutation rules anymore. Permutation rules could be simply skipped. And for all other rules, the auxiliary formulas must be searched in the premise sequents, instead of simply taking the first/last formulas in the antecedent/succedent, as we used to do in c++ ceres.

Of course, idea 2 is much better...

**Labels:** -Milestone-Unspecified Milestone-Release2.0

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 20, 2011 04:49:43_

I answered your other question here: https://code.google.com/p/gapt/source/detail?r=898

**Comment by newca12** [comment]
_From [mrukh...@gmail.com](https://code.google.com/u/105746934973897711712/) on October 20, 2011 06:44:08_

I do not understand what you mean under 1).

I also thought about doing 2), but I think may be it is better if we
design new xml format, a bit simpler one, which will be able to handle
also schematic proofs.

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 20, 2011 06:51:23_

I can explain better what I meant by 1 when we meet next time. But anyway, since I don't like 1, I think you can just ignore it...

I have always been against XML for proof formats, especially very verbose ones like the one used by ceres... So, I am in favor of your suggestion of designing a simpler XML format... And I am even more in favor of designing a non-XML proof format...

**Comment by gebner** [comment]
We no longer want to support the CERES XML format, neither for import nor export, hence this issue is now obsolete.
