### ISSUE TITLE
Symmetry of equations is not considered in guided search in ATP

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#187]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 10, 2011 15:18:42_

Right now symmetry is considered only when applying para modulation. Need to check if it is considered when applying resolution. It is not considered when using guided in order to search for a specific clause, i.e.:
trying to obtain a=b from the set x,b=a and -c will not be possible.
solution (for the guided part): improve the equality test on two equations.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=187_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 10, 2011 10:00:23_

In my opinion, this should be implemented directly into Equations in syntax.

**Comment by gebner** [comment]
No longer relevant since ATP was removed.
