### ISSUE TITLE
Parsing of Definitions

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#188]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 16, 2011 16:32:12_

When one tries to load the output of the c++ ceres instance 1 of the prime proof, the parsing does not work. The reason is, that the definition of PRIME is encoded as an atom including its parameters and that then unification doesn't work as expected. The failing example tries to unify

PRIME_{s_2(t),s_3(t)} [...t...] with PRIME_{s_2(t0),s_3(t0)} [...t0...]

which is not simply possible by substituting t0 for t (the atom name needs to change too).

you can play around yourself by constructing the terms from:

 And(Imp(Atom( ConstantStringSymbol( "PRIME_{s_2(t),s_3(t)}" ), FOLVar( VariableStringSymbol( "t" ) )::Nil), Atom( ConstantStringSymbol( "∈" ), FOLConst( ConstantStringSymbol( "P[1]" ) )::FOLVar( VariableStringSymbol( "t" ) )::Nil)), Imp(Atom( ConstantStringSymbol( "∈" ), FOLConst( ConstantStringSymbol( "P[1]" ) )::FOLVar( VariableStringSymbol( "t" ) )::Nil), Atom( ConstantStringSymbol( "PRIME" ), FOLVar( VariableStringSymbol( "t" ) )::Nil)))

and

 And(Imp(Atom( ConstantStringSymbol( "PRIME_{s_2(t_0),s_3(t_0)}" ), FOLVar( VariableStringSymbol( "t_0" ) )::Nil), Atom( ConstantStringSymbol( "∈" ), FOLConst( ConstantStringSymbol( "P[1]" ) )::FOLVar( VariableStringSymbol( "t_0" ) )::Nil)), Imp(Atom( ConstantStringSymbol( "∈" ), FOLConst( ConstantStringSymbol( "P[1]" ) )::FOLVar( VariableStringSymbol( "t_0" ) )::Nil), Atom( ConstantStringSymbol( "PRIME" ), FOLVar( VariableStringSymbol( "t_0" ) )::Nil)))

**Attachment:** [oldprime1-2.xml](http://code.google.com/p/gapt/issues/detail?id=188)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=188_

**Comment by shetzl** [comment]
adding CCs from google code: @quicquid

**Comment by gebner** [comment]
Closing this as we intend to drop support for the CERES XML format; the prime instance proofs should be rewritten using the tactics prover in #241.
