### ISSUE TITLE
Logging things through a well configured logger.

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#194]
_From [olivier....@edla.org](https://code.google.com/u/100852032415239746600/) on August 15, 2012 16:05:21_

It would be more appropriate to use a well configured logger instead of println and commented println everywhere.
slf4j facade is the way to go and is already included in maven dependencies but the logback provider is now recommended to replace log4j 
With scala using http://software.clapper.org/grizzled-slf4j/ is also highly recommended.

So the right combination for us is : sl4j facade + logback implementation + grizzled-slf4j adapter 

I will probably fix this in the offline_xml_validation branch.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=194_

**Comment by shetzl** [comment]
adding CCs from google code: @newca12

**Comment by gebner** [comment]
We've been using slf4j for some while now.
