### ISSUE TITLE
classes vs objects

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#197]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on August 23, 2012 13:59:57_

In our system we do not have clear distinction between classes and objects.

We might create an object:

1) using a factory method that compose several basic types
2) using a factory method that instantiate a specific class of the same name
3) use the constructor of the object directly (using new)

we need to make this representation uniform and decide which one we want to use

As a first step 3 should be eliminated and we need always to use 2 (remove all calls to new in the system)

second, we need to make sure to remove redundant classes (i.e. HOLConst which is 
Var with Const with HOL but just have the HOLConst factory that mixes everything.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=197_

**Comment by shetzl** [comment]
adding CCs from google code: @shetzl @shaolintl

**Comment by gebner** [comment]
As far as I can tell, this issue about the expression classes (HOLConst is mentioned)?  If so, this is fixed/resolved/obsoleted by merging the regular layers branch.

If this was about something else, please feel free to reopen.
