### ISSUE TITLE
Sequent/FSequent and Clause/FClause should be improved

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#201]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 18, 2012 10:49:47_

One of the major design flaws in our system is the inconvenient and misleading duplication of sequents and clauses.

As you know, we needed sequent and clause to have formula occurrences since this is the way we represent them in proofs. The problem is that we normally also use them outside of proofs and then the occurrences do not play a role. moreover, they cannot be used as the occurrences are an inner data structure of proofs (they represent an occurrence in a proof).

The solution to create two data types for each is flawed.

A better solution is to have clauses and sequents contain formulas and not formula occurrences and proofs will encapsulate that with information that extends the Clauses and Sequents and contain formula occurrences as well (we will have two methods for returning antecedent etc.)

Since occurrences are always computed within a proof, this will not pose a problem to the existing code.

Does anybody have any reflection on that?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=201_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on September 18, 2012 05:49:26_

I agree that this duplicate implementation is not well designed.

The problem is that a "formula occurrence" is a somewhat vague notion which depends on the context in which it is used. In fact, this problem goes way beyond implementations having the effect that most papers published about sequent calculi are - strictly speaking - incorrect: often sequents are defined as pairs of multisets but then the notion of formula occurrence is used. However, in a multiset by definition there is no possibility of distinguishing different copies of a single formula.

I think a clean solution would be to carry through this paradigm of an immutable inductive data structure all the way from constant symbols via HOLExpressions to sequents and proofs.

One option for completely avoiding formula occurrences would then be to speak about positions (as in term rewriting) instead. There a position is just a sequence of natural numbers that encodes moves in a tree: the number i means "move down to the i-th subterm". E.g. the position of the constant c in the term f(g(d,c),g(d,d)) would be (1,2). 

In a setting of proofs we will probably want to extend this by defining a more flexible system of moves, e.g.
"go from this inference rule to the one above" (for unary rules)
"go from this inference rule to the one above on the left" (for binary rules)
"go from this inference rule to the one above on the right" (for binary rules)
"enter the conclusion sequent of the current inference rule"
"go the the i-th formula of the antecedent of the current sequent"
"go the the i-th formula of the succedent of the current sequent"
and so on continuing possibly all the way down to the term level

Such a sequence of moves can then be used to point to an inference rule, to a sequent, to a formula, to a subformula, etc.

The ancestor relation can then be implemented on the level of the individual rules as follows. A rule like e.g. NegLeft has a getAncestors-function which takes a position that moves from its conclusion sequent to something (e.g. a formula in this sequent or a subformula/term) and returns a list of positions which start from its premise sequent and move to the corresponding objects in the premise sequent. This can be done with a change which only depends on a constant amount of the given sequence of moves (on its start).

**Comment by gebner** [comment]
This has been solved with the type-parametric `Sequent[A]` data structure, and the index-based new calculi.
