### ISSUE TITLE
two input methods for factor

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#218]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 20, 2012 21:12:44_

there is a new factor apply method which is pretty different from the first one. I am not sure why it was added but I think it greately complexify the code as now we need to take care of this method separately every time we match on Factors (it changes the extractor).

1) Do we really need it?
2) if so, shouldnt it be in another Factor object, maybe not in the robinson set of rules?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=218_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 20, 2012 14:37:30_

I don't think we need it; my guess was that it is used in TAP since there one can really look in the positive and in the negative literals in parallel. I'd proopose to replace it with a constructor that creates two successive Factor rule.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 21, 2012 00:19:34_

I agree with the suggestion. It is a good idea.

**Comment by shetzl** [comment]
adding CCs from google code: @quicquid

**Comment by gebner** [comment]
The new resolution calculus now only has a rule for (propositionally) factoring two literals; even the unification is handled by separate instance rules.
