### ISSUE TITLE
Skolemization momery leak/trashing

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#220]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 09, 2013 23:12:28_

input the following into the cli:

val f = parse hol "Forall x:i Exists y:i P(x:i,y:i,Z:i)"
for (i<-1 to 100) { println(i); at.logic.transformations.skolemization.skolemize(f.asInstanceOf[HOLFormula],1) }

with each step, skolemization takes more time, after 20 iterations, the cli stops reacting but gives no out of memory error.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=220_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 09, 2013 14:23:03_

Hi Martin,

Do you think this is the main source of memory problems and not the parsing?
Anyway, I can try to help with this over the weekend so you can focus on the parsing problems.

**Owner:** shaoli...@gmail.com  
**Cc:** Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 09, 2013 15:18:12_

Hi Tomer!

I don't think this is the main source of the memory problems - skolemization is not called at all in many use cases and we still have memory problems. I just found this bug when i added the detection of unskolemized endsequents to the cli and found out that one call to loadProver9LKProof was fine and the subsequent identical call locked the system. The workaround keeps the behaviour constant.

**Comment by newca12** [comment]
_From [olivier....@edla.org](https://code.google.com/u/100852032415239746600/) on January 10, 2013 11:00:16_

Regarding skolemization, the root cause is the way you generate the Skolem symbols.
Each time you call getSkolemSymbols (ie each time you call skolemize) the number of elements evaluated in the stream is doubled until the memory heap is exhausted.
The stream is size doubled when you do skolem_symbol_stream = odd( skolem_symbol_stream)

There is probably a similar problem with your Variable Symbol Factory because you do it the same way.

Hope this help

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 12, 2013 12:37:15_

Martin, have you solved this or do you want me to look at it?

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 12, 2013 15:50:31_

Tomer: i didnt't solve it yet. My plan was to remove the getSkolemSymbols method at all - one central symbol factory should be enough. The only reason for the stream is that a get does not automatically advance in the stream. Don't know if this is necessary somewhere.

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on March 11, 2013 07:04:44_

**Cc:** -Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on March 11, 2013 07:05:13_

**Cc:** fra...@gmail.com Martin.R...@googlemail.com

**Comment by shetzl** [comment]
adding CCs from google code: @shaolintl @shaolintl @quicquid @frehn
