### ISSUE TITLE
ivy import: error in parsing replacement

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#228]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 13, 2013 00:09:18_

In the CLI enter:
scala> loadProver9Proof( "../testing/prover9-TSTP/REL/REL050-4/Prover9---1109a.UNS-Ref.s.out" )

A proof should be imported, instead the following exception is thrown:
java.lang.Exception: Error in parsing replacement: (sub)term join(v2, join(v1, converse(v0))) is not the expected term join(v1, join(converse(v0), v2))
        at at.logic.provers.prover9.ivy.IvyParser$.replaceTerm_by_in_at(Ivy.scala:569)

The same problem appears in most of the proofs from the relation algebra (REL)-category of the prover9-TSTP, for example: REL045-2, REL024+1, REL008+4, REL005-3, REL023-2,...

_Original issue: http://code.google.com/p/gapt/issues/detail?id=228_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2013 11:25:42_

Issue 231 has been merged into this issue.

**Cc:** stefan.hetzl shaoli...@gmail.com mrukh...@gmail.com

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2013 11:30:17_

The exception above is now fixed - actually, the ivy paramod allows demodulation (i don't understand why there is a flip rule then). our calculus can handle demodulation (actually we dont check if the given formula can be derived at all), but it could be cleaner to insert an explicit flip.

I will not close this issue yet, as the proof REL050-4 contains new_symbol, which is not finished.

**Blockedon:** gapt:222

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2013 11:33:07_

**Owner:** Martin.R...@googlemail.com  
**Cc:** -Martin.R...@googlemail.com

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on July 03, 2013 01:40:58_

As of revision 1601 , the status of the examples mentioned above is the following:
REL050-4 failure at name_replacement:232
REL045-2 OK
REL024+1 OK
REL008+4 OK
REL005-3 failure at name_replacement:232
REL023-2 OK

**Comment by shetzl** [comment]
adding CCs from google code: @shaolintl @shetzl @quicquid

**Comment by shetzl** [comment]
I am closing this issue as the original bug has been fixed. The above examples which still fail do so due to the new_symbol rule not being handled by the import (see issue 222).
