### ISSUE TITLE
implement abstraction case in hol/replacements (positions)

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#266]
_From [christop...@gmail.com](https://code.google.com/u/105962898423732300418/) on June 18, 2014 16:48:01_

In at.logic.language.hol.replacements adapt the code to support
abstractions.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=266_

**Comment by newca12** [comment]
_From [christop...@gmail.com](https://code.google.com/u/105962898423732300418/) on June 23, 2014 16:39:47_

Note: The change done in r2077 unleashed the problem that the atp package did not compile any more, due to an infinite testcase. For a quick workaround the getAllPositions object in hol.replacements got reverted and another object
getAllPositions2 got introduced as a workaround to fit the needs of fol.replacements .

**Comment by shetzl** [comment]
adding CCs from google code: @quicquid

**Comment by gebner** [comment]
This has been made obsolete by merging PR #333.
