### ISSUE TITLE
expansionProofToLKProof fails to produce LK proof on valid expansion proof

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#279]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 27, 2015 14:13:14_

Do the following in the CLI:

import at.logic.calculi.expansionTrees.{toShallow,toDeep}
import at.logic.algorithms.lk.solve.expansionProofToLKProof
val p = loadProver9LKProof( "testing/TSTP/prover9/PUZ/PUZ002-1/Prover9---1109a.UNS-Ref.s.out" )
val E = extractExpansionSequent( p )
miniSATprove( toDeep( E ).toFormula )

This returns true, hence the deep formula of E is valid. However, executing

expansionProofToLKProof( toShallow(E), E )

results in an exception.

The PUZ002-1 - example is quite simple (10 quantified formulas with one instance each).

_Original issue: http://code.google.com/p/gapt/issues/detail?id=279_

**Comment by shetzl** [comment]
adding CCs from google code: @frehn @gisellemnr @shetzl

**Comment by shetzl** [comment]
This bug happens very frequently. As the latest regression tests show this happens on 89% of the prover9-TSTP files which do not contain equality reasoning.

**Comment by newca12** [comment]
Great ! Maybe you can make a unit test with this now that it is working :
https://github.com/gapt/gapt/blob/master/src/test/scala/at/logic/gapt/integration_tests/MiscTest.scala#L196

**Comment by shetzl** [comment]
Done.
