### ISSUE TITLE
implement proof building support for n>1 cuts in CutIntroduction

### ISSUE THREAD

**Issue by DarwinsBuddy** [gapt/gapt#281]
As for now building a proof is possible when considering ExtendedHerbrandSequents
with 1 cut, many quantifiers.
The computation of a canonicalSolution for many cuts, many quantifiers is already implemented.
Additionally the function buildProofWithCut should be extended to buildProofWithCuts
to support building a proof from an ExtendedHerbrandSequent with > 1 cuts.

(Still the minimization i.e. improvement of a canonical solution with > 1 cuts is missing)

**Comment by frehn** [comment]
Christoph and I started generalizing the buildProofWithCut method to n>1 cuts. Please find the fork here: https://github.com/frehn/gapt/tree/ncuts. Note that I will be rewriting the GIT history on this repo, so please contact me if you decide to do any work on that fork.

**Comment by frehn** [comment]
The implementation in the ncuts branch of the gapt repo (https://github.com/gapt/gapt/tree/ncuts) seems fine to me now - @shetzl, @gisellemnr: do you think we are ready to merge this into master?

**Comment by gisellemnr** [comment]
Hi Daniel,

if it is up to me, you can push it to master. I guess the change that will
cause the most noise is the interpolation, whose errors I still need to
figure out how to catch... but this is already in master, right?

Best,
Giselle

**Comment by frehn** [comment]
I'll merge with master, then. The interpolation code is not always run now - there might not be too many errors due to interpolation in the presence of equality not being implemented yet. We'll find out soon ^^

**Comment by frehn** [comment]
The ncuts branch has been merged in 62b9228581e52958c47d2534c69151c7bfe9619f.
