### ISSUE TITLE
incompatiblity between veriT and prover9

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#283]
Looking at the cutintro_ehs_unprovable - exceptions obtained from the experiments uncovered the following interesting behaviour.  For the three files:
  testing/TSTP/prover9/RNG/RNG039-1/Prover9---1109a.UNS-Ref.s.out
  testing/TSTP/prover9/LCL/LCL198-3/Prover9---1109a.UNS-Ref.s.out
  testing/TSTP/prover9/LCL/LCL259-3/Prover9---1109a.UNS-Ref.s.out
the cut-introduction algorithm produces sequents s on which calling isValid( s ) of EquationalProver (which uses veriT) returns true but getLKProof( s ) of EquationalProver (which uses prover9) returns None.

To obtain these sequents, do
  val p = loadProver9LKProof( <filename> )
and
  cutIntro.one_cut_one_quantifier( p )
these sequents then are seq2 created in CutIntroduction.scala:730.

Unfortunately all three of these sequents are too big to see at first sight wether they are valid, RNG039-1 seems to create the simplest of the three.

**Comment by gebner** [comment]
This offending sequent is now `R(0)` at [line 428](https://github.com/gapt/gapt/blob/e9efd8a54db72f9d62eeaa46fbdf5c8802d750c3/src/main/scala/at/logic/gapt/proofs/lk/cutIntroduction/CutIntroduction.scala#L428).

**Comment by gebner** [comment]
Okay, this is weird.

Here are the [relevant files we produce](https://gist.github.com/gebner/dd6bff70ee0611681f3a#file-smtlib-cnf-smt):
* `prover9.ladr` is the prover9 input.
* `smtlib-cnf.smt` is the same CNF that we pass to prover9, but exported as SMT-LIB benchmark.
* `smtlib-renamed-vars.smt` is the same benchmark that we pass to veriT, but with the symbols renamed to match prover9.
* `smtlib.smt` is the input that we pass to veriT.

Both veriT and z3 say that all of the SMT files are unsat.

Prover9 terminates with `SEARCH FAILED`.

But now comes the weird part: if we run prover9 with `prover9 -x` on the *exact* same input, then it terminates with `THEOREM PROVED`.  (`-x` enables the [experimental auto mode developed for CASC-2005](https://www.cs.unm.edu/~mccune/mace4/manual/2009-11A/auto.html); this can also be set in the input file with the flag `set(auto2)`)

Should we add `set(auto2)` by default?

**Comment by gebner** [comment]
This also happens in the latest regression tests:
```scala
val p = new Prover9Prover().reconstructLKProofFromFile("./testing/TSTP/prover9/SWW/SWW473+5/Prover9---1109a.THM-Ref.s.out")
val E = LKToExpansionProof(p)
val deep = toDeep(E)
println("p9: " + new Prover9Prover().isValid(deep))
println("p9/auto2: " + new Prover9Prover(_ => Seq("set(auto2)")).isValid(deep))
println("verit: " + new VeriTProver().isValid(deep))
```
gives
```
p9: false
p9/auto2: true
verit: true
```

**Comment by gebner** [comment]
I don't think there is much that we can do about this issue.  It's an upstream bug in Prover9, which will probably never be fixed. :cry: 

For comparison, Escargot gives the correct answer for this problem:
```
scala> Escargot isValid ExpansionProof(Prover9Importer.expansionProofFromFile(glob("**/SWW473+5/Prover9*.s.out").head)).deep
res2: Boolean = true
```
