### ISSUE TITLE
efficiency of equality rules

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#284]
Prompted by the high number of parsing-timeouts (150) we have seen on the recent cut-introduction experiments I have carried out a few tests and the cause appears to be the addition of validation of equality rules in their constructors. While a decrease in performance (to a certain extent) is unavoidable when adding this functionality, I would still expect it to pay out to try to implement these constructors in a more efficient way.

More precisely, the data I gathered is the following. I randomly chose 5 TSTP input files (from the 150 who timed out but did not before):
1: testing/TSTP/prover9/GRP/GRP251-1/Prover9---1109a.UNS-Ref.s.out
2: testing/TSTP/prover9/LCL/LCL373-1/Prover9---1109a.UNS-Ref.s.out
3: testing/TSTP/prover9/PRO/PRO002+2/Prover9---1109a.THM-Ref.s.out
4: testing/TSTP/prover9/SET/SET831-2/Prover9---1109a.UNS-Ref.s.out
5: testing/TSTP/prover9/CSR/CSR008+1/Prover9---1109a.THM-Ref.s.out

I ran a testscript with the following three outcomes
OK: loadProver9LKProof terminates sucessfully within 1 minute
EX: loadProver9LKProof throws an exception within 1 minute
TO: loadProver9LKProof does not terminate within 1 minute
on various revisions. The results are:

r2339: OK/TO/OK/OK/OK
r2340: EX/TO/EX/EX/EX
r2354: EX/TO/EX/EX/EX
r2355: TO/TO/TO/TO/TO

It was known that a bug was introduced in r2340 and fixed in r2355, see commit log for details.

Note: the discrepancy between 2 timing out but being in tstp_non_trivial_termset.csv seems to be explained by me running these tests on my machine but Giselle having generated tstp_non_trivial_termset.csv on hers.

**Comment by gebner** [comment]
This is probably no longer applicable to lkNew.  If new performance problems surface, please file a separate issue for them.
