### ISSUE TITLE
loadProver9LKProof fails with Clause [ :- ] is not reflexivity and not contained in CNF

### ISSUE THREAD

**Issue by gisellemnr** [gapt/gapt#287]
Loading fails for:
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")

with error: Clause [ :- ] is not reflexivity and not contained in CNF(-s) [ some tautology ]

**Comment by frehn** [comment]
This should be fixed in d4fe1c79435a3afa639a024a38f0f494b88d6dff. Giselle, may I ask you to confirm the fix and close this issue?

**Comment by gisellemnr** [comment]
Yes, they work. Thanks Daniel!!

I saw now that I accidently assigned this issue to you... what I meant to do was tag Stefan, Martin and you on the issue, but I am not familiar with this interface yet. I am glad the right person saw it ;)

**Comment by frehn** [comment]
I'm glad they do - thanks for checking and closing :-)
