### ISSUE TITLE
loadProver9LKProof fails

### ISSUE THREAD

**Issue by frehn** [gapt/gapt#289]
Loading the following prover9 proof fails:

gapt> loadProver9LKProof("testing/TSTP/prover9/SYN/SYN933+1/Prover9---1109a.THM-Ref.s.out")

The reason for this is the following:

* The statement being proven in the .out file is  "(\forall x. c) <-> c", where x a variable of type i and c a constant of type o.
* Since the statement contains a strong quantifier, GAPT tries to convert the imported prover9 proof into a proof of the sequent "clauses :-", where clauses are the initial clauses found in the imported prover9 proof.
* Since prover9's CNF transformation transforms the statement directly into the empty clause, "clauses" is the set consisting of the empty clause. This case is not handled in the import code, and it fails.

One possible fix would be to to eventually output a proof of "\bottom :-" (which should be allowed as an axiom). The main question seems to be how to best integrate this in the existing algorithms.

**Comment by gebner** [comment]
The import works after merging #348, and returns the LK proof `InitialRuleType(⊥ :- )`.
