### ISSUE TITLE
bug in cut-formula computation for cut-introduction with n>1 cuts

### ISSUE THREAD

**Issue by frehn** [gapt/gapt#291]
Running

:load examples/ProofSequences.scala
val p = LinearExampleProof(18)
cutIntro.many_cuts_one_quantifier( p, 2 )

yields

Cut formulas found: 
(((∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0))))))))∧∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0)))))))))∧∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0)))))))))∧((∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0))))))))∧∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0)))))))))∧∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0))))))))))
((∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0))))))))∧∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0)))))))))∧∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0)))))))))
∀x_0.((((P(s(s(s(s(s(s(s(s(x_0)))))))))⊃P(s(s(s(s(s(s(s(s(s(x_0)))))))))))∧(P(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0))))))))))))))⊃P(s(s(s(s(s(s(s(s(s(s(s(s(s(s(x_0)))))))))))))))))∧(P(x_0)⊃P(s(x_0))))∧(P(s(s(s(s(x_0)))))⊃P(s(s(s(s(s(x_0))))))))

Theoretically, we expect 2 cuts of the form \forall x F_1(x) and \forall x F_2(x), with F_1(x) and F_2(x) quantifier-free. Note that these formulas are prenex, and contain exactly one quantifier.

On the other hand, parsing the output above reveals that the two cut-formulas in this example are of the form

(\forall x G(x)) \land (\forall x H(x)).

These formulas are neither prenex, nor do they contain exactly one quantifier. Giselle, may I ask you to investigate what the problem is?

**Comment by gisellemnr** [comment]
Yes, I'll investigate the problem.

**Comment by gisellemnr** [comment]
@shetzl I have one question... when we do the replacement C_i [a_i / w_j], if w_j is a term that contains only constants, can we drop this C_i it from the cut-formula conjunction?

**Comment by gisellemnr** [comment]
@frehn Daniel, can you please check if commit 0b5501bff97659df03818878eb73257837ef6411 solves the issue?

**Comment by frehn** [comment]
@gisellemnr Thanks for the fast fix, it looks good! I literally just "looked" at it so far, but I will cherry-pick 0b5501b into the ncuts branch and see whether I am able to construct a proof using the cut-formulas. If this works we have strong evidence that the proof- as well as the cut-formula computation are working fine ^^

**Comment by frehn** [comment]
@gisellemnr, I can construct a proof using the cut-formulas you provide, so I'm closing this issue. Thanks!
