### ISSUE TITLE
file deletion fails occasionally on compile server

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#293]
In build #23 of the "gapt extended testing" in Jenkins were 5 regressions:

  at.logic.testing.tstp.TstpProver9ImportValidation.TSTP Prover9 proof import and validaton should::RNG112+1/Prover9---1109a.THM-Ref.s.out
  at.logic.testing.tstp.TstpProver9ImportValidation.TSTP Prover9 proof import and validaton should::HEN008-3/Prover9---1109a.UNS-Ref.s.out
  at.logic.testing.tstp.TstpProver9ImportValidation.TSTP Prover9 proof import and validaton should::RNG101+2/Prover9---1109a.THM-Ref.s.out
  at.logic.testing.tstp.TstpProver9ImportValidation.TSTP Prover9 proof import and validaton should::SCT123+1/Prover9---1109a.THM-Ref.s.out
  at.logic.testing.tstp.TstpProver9ImportValidation.TSTP Prover9 proof import and validaton should::GEO066-2/Prover9---1109a.UNS-Ref.s.out

which failed on deletion of either the veriT-input or the -output file.

In build #24 there was one regression:

  at.logic.testing.tstp.TstpProver9ImportValidation.TSTP Prover9 proof import and validaton should::SWV367+1/Prover9---1109a.THM-Ref.s.out

with the same problem.

This distorts the results of the regression tests hence I have marked it has high priority.

**Comment by gebner** [comment]
This was an example of how *not* to create temporary files:
```scala
val filename = "toProve" + System.currentTimeMillis + ".smt"
```
 
I have removed all temporary files from the veriT interface; we're piping it into veriT directly now:
```scala
val veritOutput = "veriT" #< new ByteArrayInputStream( veritInput.getBytes ) !!
```
