### ISSUE TITLE
veriT import does not generate sufficient symmetry instances

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#300]
The following script illustrates the problem:
val A = parseProver9( "f(f(a,b),c) = f(a,f(b,c))" )
val T = parseProver9( "f(a,b)=a -> ( f(b,c)=b -> f(a,c)=a )" )
val s = FSequent( List( A ), List( T ))
val verit = new at.logic.provers.veriT.VeriTProver
val E = verit.getExpansionSequent( s ).get
val minisat = new at.logic.provers.minisat.MiniSATProver
val Edeep = at.logic.calculi.expansionTrees.toDeep( E )
minisat.isValid( Edeep ) // returns false but should return true
proveProp( Edeep ) // returns None but should return a proof

val S1 = parseProver9( "f(f(a,b),c)=f(a,f(b,c)) -> f(a,f(b,c))=f(f(a,b),c)" )
val S2 = parseProver9( "a=f(a,c) -> f(a,c)=a" )
val Edeep_ok = Edeep.union( FSequent( S1::S2::Nil, Nil ))
minisat.isValid( Edeep_ok ) // returns true
proveProp( Edeep_ok ) // returns a proof

S1 and S2 are instances of symmetry for atoms contained in the (quantifier-free) input sequent s.

@gisellemnr

**Comment by gisellemnr** [comment]
Fixed in commit 8eed78a2beaa5e014a43979dc4956e9121427595.

This is Sparta!
