### ISSUE TITLE
veriT export fails with error message of veriT

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#301]
Uncomment any of the following lines starting with "val fn" to obtain a script which leads to a failure in the call to veriT.

//val fn = "testing/TSTP/prover9/CSR/CSR024+1.009/Prover9---1109a.THM-Ref.s.out" // push
//val fn = "testing/TSTP/prover9/CSR/CSR024+1.010/Prover9---1109a.THM-Ref.s.out" // push
//val fn = "testing/TSTP/prover9/LCL/LCL153-1/Prover9---1109a.UNS-Ref.s.out" // unresolved symbol: xor
//val fn = "testing/TSTP/prover9/LCL/LCL158-1/Prover9---1109a.UNS-Ref.s.out" // unresolved symbol: xor
//val fn = "testing/TSTP/prover9/LCL/LCL154-1/Prover9---1109a.UNS-Ref.s.out" // unresolved symbol: xor
//val fn = "testing/TSTP/prover9/LCL/LCL155-1/Prover9---1109a.UNS-Ref.s.out" // unresolved symbol: xor
val p = loadProver9LKProof( fn )
val E = extractExpansionSequent( p )
val deep = at.logic.calculi.expansionTrees.toDeep( E )
(new at.logic.provers.veriT.VeriTProver).isValid( deep )

In all 5 cases veriT complains about its input generated by gapt veriT export. This problem seems connected to some keywords reserved by veriT because the offending objects are called "push" and "xor" and are parsed with these names from prover9 TSTP import.

@gisellemnr: these are the only 5 cases with that failure from all prover9 TSTP proofs which contain equality reasoning hence I am marking this as low priority.

**Comment by gisellemnr** [comment]
Fixed on commit c3df5494e0357e82032fd73a1bbae00dfccd4d9a.
Now there are 0 cases with that failure ;)
