### ISSUE TITLE
minimality of symmetry-instances of veriT-import

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#306]
Since veriT considers equations as unordered pairs it is necessary to add instances of the symmetry-axiom to the instances of the theory of equality that we obtain from veriT. Currently both directions of the symmetry-instance are added but often one will be enough.

Since the size of the term set is the most crucial factor for the efficiency of the grammar computation in cut-introduction we should strive to minimize the number of instances delivered by veriT-import.

Below I am pasting the result of running testSymmetry.testSizes( "testing/veriT-SMT-LIB/QF_UF" ). The left column is the total number of instances, the right column is the number of instances which are _not_ symmetry-instances. The difference is the number of symmetry instances.

testSymmetry.testMinimization will compute minimal expansion proofs whose set of instances is a subset of the one generated by veriT-import.

@gisellemnr may I ask you to run testSymmetry.testMinimization( "testing/veriT-SMT-LIB/QF_UF" ) on the experiments server? A very rough estimate is 2sec per symmetry-instance which would total to about 48 hours.

Having the result of testMinimization should give an indication how much can be saved by being more careful with adding symmetry-instances.

filename: expseq_size, expseq_wosym_size
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ042_size2.smt2.proof_flat: 481, 251
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ020_size2.smt2.proof_flat: 207, 33
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ004_size5.smt2.proof_flat: 451, 146
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ032_size2.smt2.proof_flat: 354, 196
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ004_size6.smt2.proof_flat: 759, 255
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ017_size5.smt2.proof_flat: 2364, 548
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ050_size2.smt2.proof_flat: 371, 181
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ020_size3.smt2.proof_flat: 754, 93
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ011_size2.smt2.proof_flat: 193, 21
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ011_size3.smt2.proof_flat: 769, 108
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ009_size7.smt2.proof_flat: 1717, 590
testing/veriT-SMT-LIB/QF_UF/SEQ/SEQ009_size8.smt2.proof_flat: 1964, 438
testing/veriT-SMT-LIB/QF_UF/NEQ/NEQ015_size4.smt2.proof_flat: 7804, 322
testing/veriT-SMT-LIB/QF_UF/NEQ/NEQ046_size3.smt2.proof_flat: 2938, 153
testing/veriT-SMT-LIB/QF_UF/NEQ/NEQ015_size3.smt2.proof_flat: 2812, 147
testing/veriT-SMT-LIB/QF_UF/NEQ/NEQ033_size3.smt2.proof_flat: 5381, 2175
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn1225.smt2.proof_flat: 671, 131
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl032.smt2.proof_flat: 632, 108
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn774.smt2.proof_flat: 672, 148
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn060.smt2.proof_flat: 686, 152
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl104.smt2.proof_flat: 567, 95
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1044.smt2.proof_flat: 737, 173
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl654.smt2.proof_flat: 771, 168
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1039.smt2.proof_flat: 683, 157
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn059.smt2.proof_flat: 579, 107
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl263.smt2.proof_flat: 785, 151
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl069.smt2.proof_flat: 734, 196
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl036.smt2.proof_flat: 705, 171
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl414.smt2.proof_flat: 642, 95
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl274.smt2.proof_flat: 677, 139
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl268.smt2.proof_flat: 555, 83
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl007.smt2.proof_flat: 577, 82
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl067.smt2.proof_flat: 667, 127
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl788.smt2.proof_flat: 689, 167
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn005.smt2.proof_flat: 687, 140
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl790.smt2.proof_flat: 670, 144
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl498.smt2.proof_flat: 745, 192
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl004.smt2.proof_flat: 685, 138
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl224.smt2.proof_flat: 617, 131
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl058.smt2.proof_flat: 571, 76
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1015.smt2.proof_flat: 726, 232
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1246.smt2.proof_flat: 597, 115
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1271.smt2.proof_flat: 675, 127
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl005.smt2.proof_flat: 593, 98
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl470.smt2.proof_flat: 785, 234
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn056.smt2.proof_flat: 587, 92
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl739.smt2.proof_flat: 535, 65
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl313.smt2.proof_flat: 738, 187
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl749.smt2.proof_flat: 692, 160
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl006.smt2.proof_flat: 603, 100
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl060.smt2.proof_flat: 648, 132
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl499.smt2.proof_flat: 661, 164
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1262.smt2.proof_flat: 657, 135
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1017.smt2.proof_flat: 747, 201
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl418.smt2.proof_flat: 704, 123
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl237.smt2.proof_flat: 562, 92
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1117.smt2.proof_flat: 663, 153
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl357.smt2.proof_flat: 765, 190
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1041.smt2.proof_flat: 703, 153
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl415.smt2.proof_flat: 621, 101
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl958.smt2.proof_flat: 577, 105
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl738.smt2.proof_flat: 564, 92
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn820.smt2.proof_flat: 693, 163
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl870.smt2.proof_flat: 682, 154
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl049.smt2.proof_flat: 1238, 740
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl913.smt2.proof_flat: 847, 255
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl439.smt2.proof_flat: 667, 115
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl465.smt2.proof_flat: 700, 147
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1264.smt2.proof_flat: 640, 112
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1038.smt2.proof_flat: 667, 137
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl789.smt2.proof_flat: 638, 110
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl247.smt2.proof_flat: 615, 121
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl069.smt2.proof_flat: 707, 160
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl993.smt2.proof_flat: 637, 151
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl068.smt2.proof_flat: 675, 159
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl057.smt2.proof_flat: 589, 92
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl269.smt2.proof_flat: 661, 141
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/dead_dnd002.smt2.proof_flat: 51, 1
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn061.smt2.proof_flat: 591, 119
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1242.smt2.proof_flat: 796, 244
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1010.smt2.proof_flat: 699, 151
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl062.smt2.proof_flat: 816, 280
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl162.smt2.proof_flat: 621, 143
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl1190.smt2.proof_flat: 1174, 650
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl742.smt2.proof_flat: 719, 177
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl379.smt2.proof_flat: 856, 237
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl034.smt2.proof_flat: 743, 189
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl059.smt2.proof_flat: 670, 154
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl068.smt2.proof_flat: 785, 235
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn054.smt2.proof_flat: 563, 93
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl490.smt2.proof_flat: 713, 160
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl216.smt2.proof_flat: 763, 169
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn1181.smt2.proof_flat: 767, 223
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl356.smt2.proof_flat: 647, 132
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl056.smt2.proof_flat: 611, 110
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl055.smt2.proof_flat: 627, 88
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn063.smt2.proof_flat: 677, 145
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl398.smt2.proof_flat: 657, 142
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl061.smt2.proof_flat: 643, 117
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl015.smt2.proof_flat: 743, 167
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl051.smt2.proof_flat: 683, 147
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl285.smt2.proof_flat: 609, 105
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl396.smt2.proof_flat: 798, 229
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl039.smt2.proof_flat: 677, 157
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl142.smt2.proof_flat: 617, 93
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl524.smt2.proof_flat: 694, 154
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl060.smt2.proof_flat: 614, 86
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl223.smt2.proof_flat: 640, 150
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn057.smt2.proof_flat: 590, 93
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl935.smt2.proof_flat: 661, 121
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl242.smt2.proof_flat: 594, 112
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn055.smt2.proof_flat: 596, 101
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl002.smt2.proof_flat: 617, 108
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl001.smt2.proof_flat: 671, 176
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn006.smt2.proof_flat: 621, 124
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn1059.smt2.proof_flat: 694, 152
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl407.smt2.proof_flat: 702, 171
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl872.smt2.proof_flat: 628, 144
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl003.smt2.proof_flat: 568, 73
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn776.smt2.proof_flat: 581, 111
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl063.smt2.proof_flat: 767, 235
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_brn066.smt2.proof_flat: 683, 139
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl065.smt2.proof_flat: 638, 114
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1240.smt2.proof_flat: 685, 173
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl740.smt2.proof_flat: 564, 92
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl1228.smt2.proof_flat: 652, 120
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/gensys_icl057.smt2.proof_flat: 586, 91
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl419.smt2.proof_flat: 645, 99
testing/veriT-SMT-LIB/QF_UF/QG-classification/qg5/iso_icl420.smt2.proof_flat: 766, 213
testing/veriT-SMT-LIB/QF_UF/QG-classification/loops6/dead_dnd009.smt2.proof_flat: 1185, 171
testing/veriT-SMT-LIB/QF_UF/QG-classification/loops6/dead_dnd008.smt2.proof_flat: 633, 69
testing/veriT-SMT-LIB/QF_UF/QG-classification/loops6/dead_dnd006.smt2.proof_flat: 633, 69
testing/veriT-SMT-LIB/QF_UF/QG-classification/loops6/dead_dnd007.smt2.proof_flat: 1190, 176
testing/veriT-SMT-LIB/QF_UF/QG-classification/loops6/dead_dnd017.smt2.proof_flat: 633, 69
testing/veriT-SMT-LIB/QF_UF/QG-classification/loops6/iso_brn006.smt2.proof_flat: 1106, 198
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond2.smt2.proof_flat: 13, 3
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond5.smt2.proof_flat: 53, 19
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond4.smt2.proof_flat: 37, 11
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond7.smt2.proof_flat: 91, 41
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond6.smt2.proof_flat: 69, 27
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond3.smt2.proof_flat: 25, 7
testing/veriT-SMT-LIB/QF_UF/eq_diamond/eq_diamond1.smt2.proof_flat: 3, 2

**Comment by frehn** [comment]
Let me remind you, in case you do decide to improve the treatment of symmetry in the VeriT export, that there exists code in at.logic.algorithms.resolution.fixDerivation (namely the functions deriveBySymmetry etc) that check whether a clause can be derived from another clause using symmetry axioms, and that performs this derivation by paramodulation and factoring.

This code may come in handy, and it seems that it can be trivially refactored to produce LKProofs instead of resolution proofs if that is required.

**Comment by gisellemnr** [comment]
Hi all,

after the recent optimizations on the symmetry instances of veriT import, I ran the testSymmetry.testSizes again. Here's a comparison, first column is with symmetry and second column is without symmetry.

Stefan's file:

Value | WS | WOS
--- | --- | ---
Total | 110.826 | 23.607
Mean | 667 | 141,5

Running the test as is, today (03/06/15):

Value | WS | WOS
--- | --- | ---
Total | 33.642 | 23.607
Mean | 206,5 | 141,5

We cut the number of symmetry instances by a third :)
Could we close this issue?

Best,
Giselle

**Comment by shetzl** [comment]
Yes, that's fine for me :)
