### ISSUE TITLE
Support SAT4J as a Max-SAT solver

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#307]
It seems SAT4J can do Max-SAT.  Similar to how we have a pure-java fallback for SAT, it would be nice to have a fallback for Max-SAT as well.  See http://www.sat4j.org/products.php#maxsat

**Comment by frehn** [comment]
Great idea! I am very much for this, and it should not be much work - but I do believe issue #308 should be solved before tackling this.

**Comment by frehn** [comment]
Fixed in 2c1bb946489b2517852c3614b3e8de81c08aa2a9.
