### ISSUE TITLE
Improve fast CNF transformation

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#311]
- [ ] Use Plaisted transformation (i.e. Tseitin with polarity)
- [ ] Don't generate auxiliary atoms for top-level conjunctions.
- [ ] Generate larger clauses? (I don't think we need to produce 3-SAT problems.)
- [ ] Handle top and bottom directly.
- [ ] Clean up auxiliary atom name creation.

**Comment by gebner** [comment]
Look into [Thierry Boy de la Tour: An optimality result for clause form translation](http://www.sciencedirect.com/science/article/pii/074771719290009S).

**Comment by shetzl** [comment]
Gabriel, did you consider more efficient normal form transformations for treating the poset-example with the MaxSAT-algorithm?

Note: the original TseitinCNF-transformation should be preserved for examples/exercises/.

**Comment by gebner** [comment]
> Gabriel, did you consider more efficient normal form transformations for treating the poset-example with the MaxSAT-algorithm?

Not yet, this would be part of the performance evaluation of the new clausification code.

> Note: the original TseitinCNF-transformation should be preserved for examples/exercises/.

Hmm, in this case we might keep the current implementation for a while, it's would be "just" a maintanance burden.  But in general this is a good question: what should we do with the exercises?

* Preserve them literally for history's sake, even if they no longer work due to changes in gapt?
* Adapt them to the changes in gapt; this makes them useful for people doing them now, and also for future courses.  But then we should change the exercises readme so that it doesn't say "these are the exercises from the course in 2015" as that would be IMHO misleading.

For what it's worth, earlier today I adapted the one existing exercise to the changes in the SAT solver interface; I'd update them for the new clausification code as well.

**Comment by shetzl** [comment]
>  But in general this is a good question: what should we do with the exercises?

They should be kept up-to-date with the current gapt version. I will use them again next summer term. I will change the README and I will also integrate some missing exercises from last summer term into the system.

The point is just that in the course I will only describe the basic Tseitin-transformation (without the further improvements of this issue) so there should remain a way to compute the basic Tseitin-transformation.
