### ISSUE TITLE
PCNF transformation not compatible with revised CNF transformation

### ISSUE THREAD

**Issue by frehn** [gapt/gapt#312]
The previous behaviour of our internal CNF transformation was

CNF(\bot) = { :- \bot }

The new behaviour is

CNF(\bot) = { :- }

It seems that the PCNF transformation assumes the former, not the latter behaviour. In my opinion, the second behaviour is "the correct one".

I see two solutions to the problem at hand:

A) Parameterize the CNF transformation to have both the first and the second variant from above in the system, and use the first variant in context of the PCNF transformation.

B) Change the PCNF transformation to use the second variant (e.g. in this particular case, by cutting with the axiom "\bot :-").

I'd prefer B.

@quicquid, @shaolintl I believe you wrote most of the PCNF.scala code - do you have time to have a look at this issue?

**Comment by quicquid** [comment]
@frehn Sure, I'll have a look

**Comment by frehn** [comment]
Thank you!

**Comment by frehn** [comment]
In the original issue, I omitted the information how to reproduce this bug - sorry!

Try any of the following:

loadProver9LKProof("testing/TSTP/prover9/NUM/NUM484+3/Prover9---1109a.THM-Ref.s.out")
loadProver9LKProof("testing/TSTP/prover9/NUM/NUM626+1/Prover9---1109a.THM-Ref.s.out")
loadProver9LKProof("testing/TSTP/prover9/NUM/NUM530+3/Prover9---1109a.THM-Ref.s.out")
loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915+1/Prover9---1109a.THM-Ref.s.out")
loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915-1/Prover9---1109a.UNS-Ref.s.out")
loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128+1/Prover9---1109a.THM-Ref.s.out")
loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")

**Comment by quicquid** [comment]
I think I fixed the issue in the latest commit. Instead of cutting with \bot :- , I use the axiom \bot :- instead of \bot :- \bot . This should have the same effect.  The examples you mentioned are loaded now, I put the first one into the misc tests.

**Comment by frehn** [comment]
Perfect, thanks for the fix!
