### ISSUE TITLE
Don't create temporary files

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#313]
... or at least delete them afterwards.

I have just cleaned more than 5 gigabytes worth of temporary files from our Jenkins build server.  Most of our external tools (prover9, etc.) can read just fine from standard input, there really is no need to use temporary files.

**Comment by gebner** [comment]
#314 solves part of this.

**Comment by frehn** [comment]
Thanks, Gabriel!

I did a `grep -r src/ "createTempFile"` and verified that all temporary files created by that function are now deleted. From my point of view, this issue is fixed and can be closed.

**Comment by gebner** [comment]
Scala's process handling doesn't quite seem to be thread-safe (see #338), so I don't think using stdin/stdout for everything is an option.

However I think we should use guards for temporary files that automatically delete them as soon as they're out of scope, as I've started to use in fd0e3be6accf7bc0c4b0cdc7e0443094a2ae46cf with `withTempFile`.

The other issue that remains is that I think we should only use temporary files for communicating with external programs, not as an internal interface (c.f. all the parsing methods that accept file names).
