### ISSUE TITLE
Weird top/bottom handling in prover9

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#315]
See Prover9TermParser.scala:

```
  //we don't have top and bottom in the algorithms, so we simulate it
  val topformula = { fol.Or( fol.TopC, fol.Neg( fol.TopC ) ) }
  val bottomformula = { fol.And( fol.BottomC, fol.Neg( fol.BottomC ) ) }
```

**Comment by frehn** [comment]
Thanks, Gabriel. I changed this in d3d74d7492e8d3701007d0c320d649a90ab86b51 - let's see whether the next round of regression tests will find some problems with this.

**Comment by gebner** [comment]
:+1: Let's hope for the best!

**Comment by quicquid** [comment]
I think it will work - the algorithms i had in mind when i wrote this were cnf / pcnf, which are fixed now.
