### ISSUE TITLE
LKProver non-set-sequents redundancy

### ISSUE THREAD

**Issue by frehn** [gapt/gapt#319]
The LKProver proof search code should fulfill the invariant that the current sequent-to-be-proven should be set-normalized, i.e. it should not contain duplicate formulas.

This is not the case; the following code produces a proof containing a sequent A, A :- B, ¬B:

```scala
val a = FOLAtom("A", Nil)
val b = FOLAtom("B", Nil)

val s = FSequent( a::Nil, FOLImp(a, b)::FOLNeg(b)::Nil )

new at.logic.gapt.proofs.lk.algorithms.LKProver(false).getLKProof( s )
```

Fixing this should speed up proof search using LKProver.

**Comment by shetzl** [comment]
The regression tests show that there is a single case in the Prover9TestCase where this still happens. To reproduce do:
val p = loadProver9LKProof( "testing/TSTP/prover9/NUM/NUM341+1/Prover9---1109a.THM-Ref.s.out" )
val E = LKToExpansionProof( p )
val deep = at.logic.gapt.proofs.expansionTrees.toDeep( E )
proveProp( deep )
