### ISSUE TITLE
nTapeTest hangs in "Computing projections" in the regular-layers branch

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#330]
When running the nTapeTest in the regular-layers branch, it is stuck forever in the "Computing projections" part.

```
> testOnly at.logic.gapt.integration_tests.nTapeTest
+++++++++ Loading file ++++++++++
+++++++++ Eliminating definitions, expanding tautological axioms ++++++++++
+++++++++ Skolemizing ++++++++++
+++++++++ Extracting struct ++++++++++
+++++++++ Computing projections ++++++++++
+++++++++ Loading file ++++++++++
+++++++++ Eliminating definitions, expanding tautological axioms ++++++++++
+++++++++ Skolemizing ++++++++++
+++++++++ Extracting struct ++++++++++
+++++++++ Computing projections ++++++++++
```

The first "Computing projections" also takes ages; maybe this is just a performance problem?  @quicquid Any ideas?

**Comment by quicquid** [comment]
I'm not sure if it is the performance, since also the much smaller first-order tape proof was looping, when we were talking about the replay bug ( sbt 'testOnly (star)TapeTest(star)' ; # replace (star) by * ). I'll have a look at it in the evening, perhaps I can find out what's happenening.

**Comment by gebner** [comment]
Thank you very much, Martin!

However the TapeTest was hanging in the ATP code, not in Projections.

**Comment by quicquid** [comment]
It seems the projections are just getting horribly slow - the number of projections (which is a set of LKProofs) grows over 120k, when in the master branch, it is never greater than 14.

**Comment by gebner** [comment]
> set of LKProofs

AFAICT we don't implement equality of LKProofs (neither in master nor in regular-layers), is the usage of set supposed to filter out duplicate proofs?

**Comment by quicquid** [comment]
That was my first thought, but this is not the reason. The problem occurs with the containsQuantifier predicate, which has different semantics now. I found one source for the different behaviour already, but there is moe missing. If you like, i can give instructions to reproduce it.
