### ISSUE TITLE
Prover9 formula parser doesn't allow excessive use of parentheses

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#339]
```
scala> Prover9TermParserLadrStyle.parseFormula("(x) = x")
java.lang.Exception: Error parsing prover9 formula '(x) = x' at position 1.5. Error message: string matching regex `\z' expected but `=' found
  at at.logic.gapt.formats.prover9.Prover9TermParserA$class.parseFormula(Prover9TermParser.scala:56)
  at at.logic.gapt.formats.prover9.Prover9TermParserLadrStyle$.parseFormula(Prover9TermParser.scala:35)
  ... 43 elided
```

**Comment by shetzl** [comment]
In addition, gapt's prover9 parser sometimes requires parentheses where prover9 does not. E.g. the
file:
formulas(goals).
all x x = x.
end_of_list.
is accepted by prover9, but
gapt> parseProver9( "all x x=x" )
returns
java.lang.Exception: Error parsing prover9 formula 'all x x=x' at position 1.5. Error message: `<-' expected but `x' found
On the other hand,
parseProver9( "(all x x=x)" )
works as expected.

**Comment by gebner** [comment]
The Prover9 parser is only used in the Prover9 import now--and AFAICT it can parse all Prover9 output.  Closing since there is no more need to add user-friendlyness to this parser.
