### ISSUE TITLE
n-ary matcher needs casting

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#343]
@gebner Using the n-ary matcher for a conjuction requires casting to LambdaExpression, see src/test/scala/at/logic/gapt/expr/ExprTest.scala:45. Removing the cast leads to an exception. If I understand the intention of the code in the Nary matcher correctly it should work without casting.

**Comment by gebner** [comment]
Just for the record, this is the exception:
```
[info] N-ary connectives should
[error]   ! match correctly
[error]    scala.Some cannot be cast to scala.runtime.Nothing$ (constructors.scala:147)
[error] at.logic.gapt.expr.MonoidalBinaryPropConnectiveHelper$nAry$.unapply(constructors.scala:147)
[error] at.logic.gapt.expr.ExprTest$$anonfun$2$$anonfun$apply$28.apply(ExprTest.scala:45)
[error] at.logic.gapt.expr.ExprTest$$anonfun$2$$anonfun$apply$28.apply(ExprTest.scala:37)
```
