### ISSUE TITLE
regression in leanCoP-import

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#352]
@gisellemnr: last week's changes to the leanCoP import have improved the number of files we can import (see Jenkins server) but there were still many regressions (see the jenkins_test_diff.py - script). For example
```scala
val fn = "testing/TSTP/leanCoP/SWB/SWB018+2/leanCoP---2.2.THM-Prf.s.out"
val E = loadLeanCoPProof( fn )
```
fails in commit 74c3272241129c16dbabe11ded2546e23bbee633 but works in the commit immediately preceding it.

**Comment by gisellemnr** [comment]
Hi Stefan,

What is the build number?
Is the number of regressions bigger than the number of improvements?

The change I did results on a different order of the clauses computed by
gapt.
Consequently, some clauses that were previously matched with those computed
by leanCoP may now fail, whereas others may succeed. I believe that this is
the
more accurate way of computing... So I am reluctant to revert it.

I want to take a look at the failed examples anyway, but for that I need
the build
numbers. Do you know where I can get them?

Thank you!

Best,
Giselle

**Comment by gisellemnr** [comment]
By the way... I am trying to run the jenkins_test_diff.py script without
success... It returns "Name or service not known". I tried from my machine
and then logged on the experiments server, same result for both. From the
login.logic server I get 404.
What is the correct place for executing this?

Thank you!

**Comment by shetzl** [comment]
The Jenkins builds before and after the change 74c3272 are "extended testing" 57 and 58. The number of improvements is bigger than the number of regressions. I did not mean to suggest to revert this change. This only serves the purpose to notify you that the change even though it is an improvement was not a monotone one ;-)

The jenkins_test_diff.py script needs to be run from inside logic.at. For me, the current repo-version works from login.logic.at - if you run into problem with this, please ask Gabriel.

**Comment by gebner** [comment]
Closing as this is just about the general state of the leanCoP import.  If there is a concrete bug, feel free to reopen.
