### ISSUE TITLE
Exception thrown by ExistsLeftRule

### ISSUE THREAD

**Issue by seimes** [gapt/gapt#358]
A call to ExistsLeftRule yields the following exception:

```javascript
java.lang.IllegalArgumentException: Types don't fit while constructing application ((¬P(a)∨Q(y)) : ο) (v : ι)
  at at.logic.gapt.expr.App.<init>(typedLambdaCalculus.scala:183)
  at at.logic.gapt.expr.determineTraits$App_with_FOLLambdaTerm.<init>(traits.scala:85)
  at at.logic.gapt.expr.determineTraits$.forApp(traits.scala:97)
  at at.logic.gapt.expr.App$.apply(typedLambdaCalculus.scala:238)
  at at.logic.gapt.proofs.lk.StrongRuleHelper$$anonfun$getTerms$8.apply(quantificationRules.scala:462)
  at at.logic.gapt.proofs.lk.StrongRuleHelper$$anonfun$getTerms$8.apply(quantificationRules.scala:462)
  at scala.Predef$.assert(Predef.scala:165)
  at at.logic.gapt.proofs.lk.StrongRuleHelper.getTerms(quantificationRules.scala:462)
  at at.logic.gapt.proofs.lk.ExistsLeftRule$.apply(quantificationRules.scala:352)
  at at.logic.gapt.proofs.lk.ExistsLeftRule$.apply(quantificationRules.scala:330)
  ... 53 elided
at.logic.gapt.proofs.lk.base.LKUnaryRuleCreationException: Could not create lk rule all:l from parent (P(a)∨Q(b)),∀x.¬P(x) :- ∃z.Q(z) with auxiliary formulas ∃y.(¬P(a)∨Q(y))
  at at.logic.gapt.proofs.lk.ForallLeftRule$.apply(quantificationRules.scala:53)
  ... 53 elided
```

The following code (in particular the declaration of p16) was responsible for throwing the exception:

```javascript
val a = FOLVar("a")
val v = FOLVar("v")
val u = FOLVar("u")

val pu = FOLAtom("P", u::Nil)
val qu = FOLAtom("Q", u::Nil)
val qv = FOLAtom("Q", v::Nil)
val pa = FOLAtom("P", a::Nil)

val npu = Neg(pu)
val npuorqu = Or(npu,qu)
val enpuorqy = parse.fol("Exists y Or Neg P(u) Q(y)")
val aporq = parse.fol("Forall x Or Neg P(x) Q(x)")
val aenpuorqy = parse.fol("Forall x Exists y Or Neg P(x) Q(y)")
val npa = Neg(pa)
val npaorqv = Or(npa,qv)
val eqy = parse.fol("Exists y Q(y)")
val enpaorqy = parse.fol("Exists y Or Neg P(a) Q(y)")

val ax1 = Axiom(pu::Nil, qu::pu::Nil)
val ax2 = Axiom(qu::pu::Nil,qu::Nil)
val ax3 = Axiom(Nil, qv::pa::Nil)
val ax4 = Axiom(qv::Nil, qv::Nil)

val p1 = NegLeftRule(ax1,pu)

val p2 = OrLeftRule(p1,ax2,npu,qu)
val p3 = ContractionRightRule(p2,qu)
val p4 = ContractionLeftRule(p3,pu)
val p5 = NegRightRule(p4,pu)
val p6 = OrRight1Rule(p5,npu,qu)
val p7 = OrRight2Rule(p6,npu,qu)
val p8 = ContractionRightRule(p7,npuorqu)
val p9 = ExistsRightRule(p8,npuorqu,enpuorqy,u)
val p10 = ForallLeftRule(p9,npuorqu,aporq,u)
val p11 = ForallRightRule(p10,enpuorqy,aenpuorqy,u)

val p12 = NegLeftRule(ax3,pa)

val p13 = OrLeftRule(p12,ax4,npa,qv)
val p14 = ContractionRightRule(p13,qv)
val p15 = ExistsRightRule(p14,qv,eqy,v)
val p16 = ExistsLeftRule(p15,npaorqv,enpaorqy,v)
val p17 = ForallLeftRule(p16,enpaorqy,aenpuorqy,a)
```

**Comment by quicquid** [comment]
There was a bug while generating the error message.  What you should see now is the follwing:

    java.lang.AssertionError: assertion failed: assert 2 in getTerms of Strong Quantifier Rule fails!
    (¬P(a)∨Q(v)) != (¬P(a)∨Q(v))

which is also not that helpful. In this situation, two things can happen:

1) some types don't match
2) some constants are variables and vice versa

Here case 2 applies:

    gapt> freeVariables(p15.root.antecedent(0).formula)
    res1: Set[at.logic.gapt.expr.Var] = Set(a, v)

but

    gapt> freeVariables(enpaorqy)
    res5: Set[at.logic.gapt.expr.FOLVar] = Set()

i.e. a is parsed as constant. There is a parser with explicit type and constant declarations which works:

    val enpaorqy = parseLLKFormula("var a,y:i; const P,Q:i>o; (exists y (-P(a) | Q(y)))")
    val p16 = ExistsLeftRule(p15,npaorqv,enpaorqy,v)
    p16: at.logic.gapt.proofs.lk.base.LKProof = ExistsLeftRuleType(∃y.(¬P(a)∨Q(y)) :- ∃y.Q(y), ExistsRightRuleType((¬P(a)∨Q(v)) :- ∃y.Q(y), ContractionRightRuleType((¬P(a)∨Q(v)) :- Q(v), OrLeftRuleType((¬P(a)∨Q(v)) :- Q(v),Q(v), NegLeftRuleType(¬P(a) :- Q(v), InitialRuleType( :- Q(v),P(a))), InitialRuleType(Q(v) :- Q(v))))))

**Comment by seimes** [comment]
Thanks for the answer. I already expected that it might have something to do with the use of parse.fol(). In the future, I will try to use parseLLKFormula instead.

**Comment by quicquid** [comment]
An alternative is to follow the syntax conventions of the parser you use:

* parse.fol and parse.folterm : variables start with u-z, constants start with a-z, predicates start with A-Z

* parse.p9 and parse.p9term:  follow [Prover9 Syntax](https://www.cs.unm.edu/~mccune/mace4/manual/2009-11A/syntax.html), by default it's the LADR format (starts with x-z variables, rest constants) but adding "false" as additional argument you get the Prolog Style variables (starts with A-Z variables, rest constants).

* parse.llk : is prover9 syntax, but you need to declare every constant and variable with their respective types before. This is especially useful if you use higher-order logic, which is it was made for.

In case of the first two you can also just use the parser for all terms in your proof:

    val v = parsep9term("x")

Eigenvariables need to be of type Var though, so you need to cast (v.asInstanceOf[Var]) before you pass it to a strong quantifier rules.

**Comment by seimes** [comment]
Cool, thanks for the brief overview. I did not know that there is a specific naming convention for the parser arguments w.r.t. variables, etc.

**Comment by quicquid** [comment]
Actually I should put this info into the user manual (chapter 5 of gapt/doc/user_manual.tex) but so far I didn't get to it.

**Comment by quicquid** [comment]
The user manual is now updated (The information is in the appendix).
