### ISSUE TITLE
We bring veriT to its knees

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#365]
This makes veriT take an insane amount of memory (followed by an invalid memory access, presumably):
```scala
val q = new Prover9Prover().reconstructLKProofFromFile("./testing/TSTP/prover9/GRP/GRP098-1/Prover9---1109a.UNS-Ref.s.out")
val e = LKToExpansionProof(q)
println(new VeriTProver().isValid(toDeep(e)))
```

[This is the SMT-LIB output we generate.](https://gist.github.com/gebner/434e9ac403d5462465ab)

Are we doing something wrong here?  Note that line 20 is 895K large...

**Comment by quicquid** [comment]
If you have an input file for veriT, i can ask Pascal to have a look too.

**Comment by gebner** [comment]
@quicquid 
https://gist.github.com/gebner/434e9ac403d5462465ab

**Comment by gebner** [comment]
Splitting the large conjunction under (assert) into multiple asserts doesn't help.

**Comment by quicquid** [comment]
I've talked to Pascal in the meantime - he didn't find the source of the invalid memory access but said that it's most likely just running out of memory. Since the problem carries over to veriT 2015, I don't think it will be solved soon there.

**Comment by gebner** [comment]
Closing since bug has been reported upstream.  There doesn't seem to be anything we can do here to fix this (other than use z3 in the meantime).
