### ISSUE TITLE
Cut introduction blows up some proofs by a factor of 100

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#370]
```scala
val p = new Prover9Prover().reconstructLKProofFromFile("testing/TSTP/prover9/CAT/CAT009-1/Prover9---1109a.UNS-Ref.s.out")
CutIntroduction.execute(p, MaxSATMethod(1), verbose=true)
```
Highlights from the output:
```
Total inferences in the input proof: 318
Quantifier inferences in the input proof: 71
Size of term set: 29
Smallest grammar-size: 22
Size of the minimized solution: 41
Number of cuts introduced: 5681
Total inferences in the proof with cut(s): 33906
Quantifier inferences in the proof with cut(s): 52
```

@shetzl @gisellemnr Any ideas? In particular the number of introduced cuts seems a bit worrying.

**Comment by gisellemnr** [comment]
Buuut... the number of quantifiers inferences has reduced, so our job is done!
Just kidding :D

I have investigated, and our algorithm introduces only one cut. The rest comes from the propositional proof construction by Prover9:

    Prover used: class at.logic.gapt.provers.eqProver.EquationalProver
    Cuts in L_1: 5637
    Cuts in R_i: 43

I did not know the proofs we imported from prover9 had cuts... Any ideas there?

**Comment by gebner** [comment]
> I did not know the proofs we imported from prover9 had cuts... Any ideas there?

Conceptually, the way we convert resolution proofs to LK is by first grounding them (i.e. instead of applying a unifier inside the resolution inference, we apply the substitution to the subproofs).  And then we replace resolution inferences by atomic LK cuts (that's where they come from), and double up the literals in the initial clauses so that they're LK axioms (these new literals propagate downwards to become hypotheses in the end-sequent; well, we need to do a bit more work if the end-sequent is not in CNF).

In this case, the L_1 resolution proof has 113 inferences if we count them as nodes in a DAG; but it has 13572 inferences if we count them as a tree (i.e. when we ignore the sharing of subtrees).  The resulting LK proof has 33573 inferences.

I was under the impression that while there is an exponential blow-up in the conversion of resolution proofs to LK, that this is only because of grounding.  Interestingly however, this is a completely propositional proof.

**Comment by gebner** [comment]
In the cut-intro meeting of 2015-09-02, we decided to measure the proof compression by comparing the following:
* Sizes of automatically generated resolution proofs of the Herbrand sequent and the extended Herbrand sequent.
* Logical/symbolic complexities of the Herbrand sequent and the extended Herbrand sequent.
* Expansion proof and expansion proof with (the introduced) cuts (if we get around to implementing it)

In any case, we never did or intend to publish comparisons of LK proof sizes.
