### ISSUE TITLE
veriT import unconditionally adds quantifier-free formulas to the expansion sequent

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#371]
Is there a reason for that?  https://github.com/gapt/gapt/blob/2a23f8b145cf50b30146424e300016ddd18ffd65/src/main/scala/at/logic/gapt/provers/veriT/VeriTProver.scala#L45-L53

(Use case: I'd like to use veriT as a relevancy filter for quasi-tautological problems.  It might also be useful to support unsat core extraction via the veriT interface as well.)

**Comment by gisellemnr** [comment]
Hi Gabriel,

please see this commit for an explanation: https://github.com/gapt/gapt/commit/40c8d7140ee812f14493db04efcca5101a596d8a

Regarding the quasi-tautological filter, I wouldn't remove the addition of symmetry instances from the VeriTProver... I guess it should behave as all the other provers, which return a tautological expansion tree. I see two alternatives: (1) check if there are symmetry instances on the shallow sequent of the expansion proof returned or (2) implement a getQuasiTautologicalExpansionSequent for VeriTProver.

By the way, the commit did not show on the history for the VeriTProver.scala file... do you know why? Seems we lost the history when the package 'gapt' was added.

Best,
Giselle

**Comment by gebner** [comment]
> please see this commit for an explanation: 40c8d71

Ah ok, this makes sense.  Still, I think we should try to match up the (possibly negated) formulas used in the veriT proof with the formulas (and the correct polarity) in the end sequent.

With relevancy filter, I meant the following problem: I give you a valid sequent with 10000 formulas, please give me a subsequent with 5 formulas that is still valid (i.e. the 5 formulas that you used in the proof). And I had hoped that I could just look at the expansion sequent to find those 5 formulas (this works with the prover9 interface BTW).

As to whether getExpansionSequent should return tautological or quasi-tautological expansion sequents: IMHO it makes sense for veriT to return at least the congruence instances (as we can reasonably extract them from veriT proofs as far as I can tell).  However *none* of the other sources of expansion proofs (leancop, prover9, LKToExpansionProof, RobinsonToExpansionProof) include instances of the equality axioms.

> By the way, the commit did not show on the history for the VeriTProver.scala file...

Works for me: https://github.com/gapt/gapt/blame/2a23f8b145cf50b30146424e300016ddd18ffd65/src/main/scala/at/logic/gapt/provers/veriT/VeriTProver.scala#L43

**Comment by shetzl** [comment]
This is not a bug, this is a feature ;-) The idea is: you give VeriTProver a quantifer-free sequent which is a quasi-tautology and he will add all the instances of equality-axioms needed to turn it into a tautology.

If you need a relevance filter, use minimalExpansionSequent(s) on the output of VeriTProver.

I agree though that it is not very elegant that most provers return a quasi-tautological expansion sequent but veriT returns a tautological expansion sequent. However, making this distinction using scala types seems like an overkill to me at the moment.

Matching up the input sequent with the output of veriT is annoying difficult since veriT (much like all other external provers) uses a rather complicated normal form transformation which we would have to re-program in gapt to make that work.

**Comment by gebner** [comment]
> If you need a relevance filter, use minimalExpansionSequent(s) on the output of VeriTProver.

Unfortunately, minimalExpansionSequent is really slow--at least compared to obtaining a proof from veriT.  The SMT solver interface needs rethinking anyways; I'd like at least push/pop, more logics, multiple sorts, and unsat cores.  But that's not in this issue then.

> Matching up the input sequent with the output of veriT is annoying difficult since veriT (much like all other external provers) uses a rather complicated normal form transformation which we would have to re-program in gapt to make that work.

Ah, veriT does at least double negation elimination; so this would really be some work (and probably not that reliable to begin with).
