### ISSUE TITLE
S-Expression parser is slow

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#375]
On my laptop, the s-expression parsing takes 400ms out of 550ms when parsing this proof:
```scala
Prover9Importer.robinsonProofFromFile("testing/TSTP/prover9/GRP/GRP209-1/Prover9---1109a.UNS-Ref.s.out")
```
(The ivy file is just 30K large, with 4k lines.)

**Comment by gebner** [comment]
Oh my god, I think I can see where the problems come from...
```scala
class ListReader( val list: immutable.List[tokens.Token], val full: immutable.List[tokens.Token] )
    extends Reader[tokens.Token] {
  //lazy val rest-full = (rest, full) //used as index in the hashtable
  lazy val position = IntPosition( full.size - list.size )
```

**Comment by quicquid** [comment]
The switch to IntPosition sped up the parser at the time, but feel free to exchange it for something more efficient.
