### ISSUE TITLE
Cut-intro experiments: zombie prover9s ahoy!

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#377]

**Comment by shetzl** [comment]
Please be more verbose. An issue is intended to describe a problem in such a way that everybody on the development team can understand the problem.

**Comment by gebner** [comment]
Sentry gun is up and trigger-happy:
```shell
while :; do ps -C prover9 --no-headers -o pid,comm,etimes | awk '($3 > 300) { print $1 }' | xargs kill; sleep 10; done
```

**Comment by gebner** [comment]
Sorry, was busy getting rid of the immediate problems.

It's the same problem we've already run into with the MaxSAT solver: upon a ThreadDeath exception (i.e. a timeout), external processes are not automatically terminated.  Now that we're running prover9 to measure sizes of resolution proofs of the (extended) Herbrand sequents, this can happen to prover9 as well.
