### ISSUE TITLE
Duplicates edges in weak quantifier nodes in expansion trees

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#384]
Looking through the CSV file listing the non-trivial termsets of the prover9 import, the termset sizes usually change by a few terms every time we generate them.

After the recent switch to the new resolution calculus, there are 221 proofs that have smaller term sets now, among those this is a fairly interesting one where the termset size almost halved compared to two weeks ago:
```
file         LCL090-1
nfuns_old           3
terms_old        1745
nfuns_new           3
terms_new        1019
```

(Looking at the older lists as well, we have always obtained 1745 or 1746 terms for this proof.)

Investing a bit turned up a weird situation:
```scala
val expansion = Prover9Importer.expansionProofFromFile("testing/TSTP/prover9/LCL/LCL090-1/Prover9---1109a.UNS-Ref.s.out")
println(extractInstances(expansion).size)
println(extractInstances(expansion).distinct.size)
println(new InstanceTermEncoding(toShallow(expansion)).encode(expansion).distinct.size)
println(new VeriTProver().isValid(extractInstances(expansion)))
```
prints
```
1572
1019
1019
true
```

I.e. `extractInstances` returns many duplicate instances.  This seems to happen because the ETWeakQuantifier node contains duplicate edges.  The expansion trees are generated by `formulaToExpansionTree`.

(ETWeakQuantifier doesn't do any kind of validation at the moment.)

**Comment by gebner** [comment]
So, now `extractInstances` returns a set.  But there are still duplicate edges in the expansion tree.

**Comment by shetzl** [comment]
A quick note without having looked at the code: our expansion proofs *should* not have *any* duplicate edges at the weak quantifier nodes. The purpose of merging two expansion proofs is precisely to avoid such duplicate edges. At some point, corresponding to the constructors of LK, we may even want to verify this property in the construction...

As of now, if an expansion tree with such duplicate edges is created this is a bug in the code that creates it (there may be an easy way to fix this bug using the merge operation).

**Comment by gebner** [comment]
Yes, there are definitely duplicate edges:
```scala
val expansionSequent = Prover9Importer.expansionProofFromFile("testing/TSTP/prover9/LCL/LCL090-1/Prover9---1109a.UNS-Ref.s.out")
val et @ ETWeakQuantifier(shallow, instances) = expansionSequent(Ant(0))
instances.groupBy(_._2).mapValues(_.size).toSeq.sortBy(-_._2).take(10) foreach println
```
The top ten together with their duplicity:
```
(arbitrary,99)
(implies(arbitrary,arbitrary),84)
(implies(arbitrary,implies(arbitrary,arbitrary)),58)
(a,43)
(implies(a,a),35)
(implies(implies(arbitrary,arbitrary),implies(arbitrary,implies(arbitrary,arbitrary))),26)
(implies(implies(arbitrary,arbitrary),implies(implies(arbitrary,arbitrary),implies(arbitrary,implies(arbitrary,arbitrary)))),23)
(implies(implies(arbitrary,arbitrary),implies(arbitrary,arbitrary)),19)
(implies(arbitrary,implies(implies(arbitrary,arbitrary),implies(arbitrary,arbitrary))),18)
(implies(a,implies(a,a)),16)
```

However, merge doesn't seem to help:
```scala
val ETWeakQuantifier(shallow_, instances_) = merge(et)
println(instances.size -> instances_.size)
```
The merged expansion tree doesn't have fewer edges:
```
(740,740)
```

I definitely agree that we should add verification during the construction of weak quantifier nodes...

**Comment by gebner** [comment]
I have only included validation for this case now.  We can add full validation when we refactor the expansion trees.
