### ISSUE TITLE
lkNew: applySubstitution should rename eigenvariables if they occur in the substitution

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#394]

**Comment by shetzl** [comment]
As a general rule of thumb one should never rename free variables, only bound variables. The reason for that is that a free variable is often "implicitely bound" (i.e. its name is of relevance) in the context. Think, e.g. about a grammar whose nonterminals have the same names as eigenvariables. As with all rules there are also exceptions to this but one should be careful. Without a compelling reason why we should rename eigenvariables I am rather in favor of throwing an exception when an eigenvariable condition is violated (which - I believe - is what is currently done). Let's discuss this in the gapt meeting on Wednesday.

**Comment by gebner** [comment]
:+1: for discussing this on Wednesday.

However, I'm not talking about renaming free variables here; just the ones that are bound by strong quantifier inferences.  (BTW the check is incomplete at the moment, it only makes sure that the eigenvariable doesn't occur in the domain, it could still occur in the range of a substitution.)

As far as I can tell, renaming eigenvariables is necessary for RobinsonToLK to work correctly (at the moment we're just lucky that we always use the right variables, I tried a small change in the prover9 import and this broke down...).
