### ISSUE TITLE
Reductive cut-elimination is not thread-safe

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#396]

**Comment by shetzl** [comment]
Please provide more information. Which part of the code violates thread-safety? Which problem arises? Is there a way to reproduce it?

**Comment by gebner** [comment]
Cut-elimination produces a sequence of proofs, leading from the proof with cuts to the cut-free proof.  This list is stored as a global variable: https://github.com/gapt/gapt/blob/master/src/main/scala/at/logic/gapt/proofs/lk/ReductiveCutElim.scala#L26
