### ISSUE TITLE
LK conversion of imported Prover9 proof of (all x exists y -x=y) fails

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#397]
[neq.txt](https://github.com/gapt/gapt/files/9472/neq.txt)
The import of the attached prover9 output fails in gapt 1.10 (I could not build the current version because of problems updating sbt):

    gapt> loadProver9LKProof("neq.txt")
    WARN  fixDerivation$ - Could not derive -(c1)=v0 :-  from List( :- c1=x) by symmetry or propositional resolution
    at.logic.gapt.proofs.resolution.ResolutionException: Resolution Exception: Clause [-(c1)=v0 :- ] is not reflexivity and not contained in CNF(-s) [
     :- c1=x
    ]
      at at.logic.gapt.proofs.resolution.PCNF$.apply(PCNF.scala:71)
      at at.logic.gapt.proofs.resolution.RobinsonToLK$PCNFMemoTable.getPCNF(RobinsonToLK.scala:21)
    [...]

Can you confirm this in the current snapshot, @gebner ?

**Comment by gebner** [comment]
![neq](https://cloud.githubusercontent.com/assets/313929/10343158/ccadd530-6d1c-11e5-8e93-91c226b328c8.png)
Works for me.

**Comment by gebner** [comment]
BTW, can you tell me what sbt problems you ran into?

**Comment by quicquid** [comment]
I updated to sbt 0.13.19, but then sbt hangs with "Getting org.scala-sbt sbt 0.13.9 ...". Looks like a network problem.

**Comment by quicquid** [comment]
By the way, thanks for checking :)
