### ISSUE TITLE
lkNew: LKsk

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#401]
Is any method from LK (cut-elim, regularization, ...) used on LKsk at the moment?

**Comment by quicquid** [comment]
Yes, regularization and definition elimination for the work from my thesis (ntape test) - there should also be corresponding algorithms in the lksk package. I need to check if I more is needed.

**Comment by gebner** [comment]
Ah, definition elimination is already duplicated, good.  I can't find any code which regularizes LKsk proofs however, can you give me a pointer?

**Comment by quicquid** [comment]
Hm, i just checked - the code in definition elimination is not related to the code in rewriting. For the nTape integration test, the algorithms are performed on ordinary LK proofs before the conversion to LKsk. The algorithms applied to LKsk proofs in it are: 

* StructCreators.extract
* Projections

I'll check the code of ceres_omega and extend the list if necessary.

**Comment by gebner** [comment]
Thanks, that looks manageable--my current plan of action for the transition to the new calculi is to keep LKsk separate from LK and duplicate the stuff that's needed for both.

**Comment by gebner** [comment]
Todo: add non-skolem quantifier rules to LKsk and use them for infereces on cut-ancestors.

**Comment by quicquid** [comment]
Just a remark: because the new lksk is a completely new calculus now, we will need to duplicate the mentioned algorithms. In this case the effort is acceptable, but we might want to think about what to do in the general case.

**Comment by gebner** [comment]
`StructCreators.extract` is already duplicated (see `extractStructFromLKsk`).  Substitution is on my todo list, for the projections it would be good if someone with CERES knowledge would help.

For the lattice proof, I can extract a struct that generates a clause set that prover9 can refute; for the other proofs I think we need the modifications for the unary equality rule conversion.

Regarding prooftool: you can view LKsk proofs right now (see DrawSequentProof.scala; but without labels, I didn't figure out how/whether prooftool showed labels before).

**Comment by quicquid** [comment]
This afternoon i did the split up, I'll see to fix struct extraction and projections on the weekend - they need to take the unary equation rule into account anyway.

**Comment by gebner** [comment]
Fixed by merging #449.
