### ISSUE TITLE
TapeTest: lkNew conversion creates different clause set and proof profile

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#411]
After introducing the following change in the TapeTest, I get a different clause set and proof profile in `target/tape-cs.tptp` and `target/tape-prf.tptp`:
```diff
diff --git a/src/test/scala/at/logic/gapt/integration_tests/TapeTest.scala b/src/test/scala/at/logic/gapt/integration_tests/TapeTest.scala
index f2029eb..d07cb62 100644
--- a/src/test/scala/at/logic/gapt/integration_tests/TapeTest.scala
+++ b/src/test/scala/at/logic/gapt/integration_tests/TapeTest.scala
@@ -63,7 +63,7 @@ class TapeTest extends Specification {
       proofdb.proofs.size must beEqualTo( 1 )
       val proof = proofdb.proofs.head._2
 
-      val proof_sk = skolemize( proof )
+      val proof_sk = lkNew2Old( lkOld2New( skolemize( proof ) ) )
       val s = StructCreators.extract( proof_sk )
 
       val prf = deleteTautologies( proofProfile( s, proof_sk ).map( _.toHOLClause ) )
```
I.e. I'm just converting back and forth to the new LK.

The new clause set has 6 clauses instead of 3:
```
cnf( sequent0,axiom,'f'('+'(X0, X1)) = '0' | '+'(X0, X1) = '+'(X1, X0)).
cnf( sequent1,axiom,~'+'(X0, X1) = '+'(X1, X0) | 'f'('+'(X0, X1)) = '0' | 'f'('+'(X1, X0)) = '1').
cnf( sequent2,axiom,~'f'('+'(X0, X1)) = '0' | ~'f'('+'('+'('+'(X0, X1), '1'), X2)) = '0' | '+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2)).
cnf( sequent3,axiom,~'+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2) | ~'f'('+'(X0, X1)) = '0' | ~'f'('+'('+'('+'(X0, X1), '1'), X2)) = '0').
cnf( sequent4,axiom,~'f'('+'(X0, X1)) = '1' | ~'f'('+'('+'('+'(X0, X1), '1'), X2)) = '1' | '+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2)).
cnf( sequent5,axiom,~'+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2) | ~'f'('+'(X0, X1)) = '1' | ~'f'('+'('+'('+'(X0, X1), '1'), X2)) = '1').
```

And the proof profile is different from the clause set:
```
cnf( sequent0,axiom,'+'(X0, X1) = '+'(X1, X0)).
cnf( sequent1,axiom,~'+'(X0, X1) = '+'(X1, X0) | 'f'('+'(X0, X1)) = '0' | 'f'('+'(X1, X0)) = '1').
cnf( sequent2,axiom,'+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2)).
cnf( sequent3,axiom,~'+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2) | ~'f'('+'(X0, X1)) = '0' | ~'f'('+'('+'('+'(X0, X1), '1'), X2)) = '0').
cnf( sequent4,axiom,'+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2)).
cnf( sequent5,axiom,~'+'('+'(X0, X1), '+'('1', X2)) = '+'('+'('+'(X0, X1), '1'), X2) | ~'f'('+'(X0, X1)) = '1' | ~'f'('+'('+'('+'(X0, X1), '1'), X2)) = '1').
```

While the proof profile is easily refutable by prover9, both prover9 and eprover fail at the clause set...

I'm afraid that this is due to the new unary equation rules--the conversion from the old binary equation rules introduces a cut on the equation.  @quicquid Any ideas?  Do you see what's going wrong here?

**Comment by quicquid** [comment]
Hi it seems the source are indeed the cuts on equations. The clauses from the original papers are all sub-sequents of the ones in this set, hinting that an additional (sequent) merge is performed during ccs construction. I'll compare the structs to be absolutely sure. It's likely we can change the struct to accomodate for the equational theories, but I think this needs to be formally proved. I'm thinking of the case where a cut on an equation does not come (directly) from the translation of the binary equation rule. But maybe we could just add it to the equational theory anyway.

**Comment by quicquid** [comment]
I created the clause set by hand from the cli, calling:

    import at.logic.gapt.proofs.ceres.struct._
    import at.logic.gapt.formats.tptp._

    val pdb = XMLProofDatabaseParser("examples/tape/tape-in.xml.gz")
    val tapecl = StandardClauseSet.transformStructToClauseSet( StructCreators.extract( lkNew2Old(elp) ) )
    val cl = tapecl.map(x => Sequent(x.negative.map(_.formula),x.positive.map(_.formula)))
    println(TPTPFOLExporter.tptp_problem(cl))

    val smallcl = at.logic.gapt.proofs.lk.subsumedClausesRemoval(cl)
    println(TPTPFOLExporter.tptp_problem(smallcl))

and obtained a clause set of 14 / 10 formulas. Prover9 chokes on them, but SPASS manages.

[newtape.tptp.txt](https://github.com/gapt/gapt/files/13442/newtape.tptp.txt)
[newtape2.tptp.txt](https://github.com/gapt/gapt/files/13443/newtape2.tptp.txt)

**Comment by gebner** [comment]
This works in the new CERES for the unary equational rules, at least if you pass `CERES.skipEquations`.
