### ISSUE TITLE
prooftool: menus should be redesigned

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#413]
The menus of prooftool are in a rather incoheret state - some functionality of gapt is excessively available (e.g. schematic ceres) while other is not accessible at all (e.g. cut-introduction). The separation between "View" and "Edit" is quite unclear. Examples should be not hardcoded as menu items.

As a general design principle for prooftool I would suggest the following: it is primarily a viewer, therefore viewing functionality (e.g. cycle through cuts, hide sequent contexts, etc.) can and should be available in detail. For actual proof transformations, the CLI should be used - it is much more versatile and easier to keep up to date with the development of the system.

Nevertheless, I believe it makes some to make some logical / proof-theoretic functionality of gapt available in prooftool, if only to have the gui carry around an advertisement of (and easy access to) the functionality of gapt. It seems to me that a good level of abstraction for that is something like: one menu item "cut-introduction", one menu item "ceres", one menu item "Gentzen cut-elimination", etc.

**Comment by shetzl** [comment]
A draft proposal for the new menu structure (as discussed today in the gapt meeting):

* File
  * Open...
  * Save as...
  * Save all as...
  * Import... [ veriT, prover9, etc. ]
  * Export... [ open file dialog with file format choice ]
  * Exit

* Edit [ editing/transforming currently displayed object, extracting new object ]
  * Skolemize
  * Regularize
  * Eliminate definitions
  * -----
  * Extract expansion tree
  * Generate LK proof
  * -----
  * Gentzen cut-elimination
  * Cut-elimination by resolution
  * Cut-introduction
  
* View [ viewing options pertaining to currently displayed object ]
  * Zoom In
  * Zoom Out
  * -----
  * (yes/no checkmark) Hide structural rules [ subsumes show all rules ]
  * (yes/no checkmark) Hide sequent contexts [ subsumes show all formulas ]
  * (yes/no checkmark) Mark cut-ancestors [ subsumes remove marking ]
  * -----
  * Sunburst
  
*  ( History ? ) / Window [ viewing options pertaining to all objects currently available, also, e.g., switching between them ]

---------

old stuff which propose to delete

"(!?)" means I could not get it to work reliably / do not know what it does

* Edit
  * (!?) Search...
  * (!?) Show Leaves
  * (!?) Hide Leaves
  * Hide all formulas [ essentially subsumed by sunburst ]
  * Extract cut formulas [ should go to CLI ]
  * (!?) Mark Omega-ancestors

* View
  * Jump To End-sequent
  * (!?) Find Cuts
  * (!?) Cycle through cuts
  * View Proof
  * View Clause List

* LK Proof
  * Compute clause set
  * Compute struct
  * Compute projections

* LKS Proof

* Help

* Tests

**Comment by quicquid** [comment]
I'll just fill in what the !? entries do: Search searches for a string in the formulas, e.g. a constant name and marks it in green. Show/hide leaves is used in the struct viewer, where the tree is only annotated by leaves. A click on a leaf allows hiding the formula, for big structs hiding all the leaves allows a better view on the branching stucture. The Omega Ancestors point highlights all possible cut-ancestors (in schematic ceres, there is a set of ancestor relationships because the same sub-proof can occur in multiple places with a different cut-ancestorship of the end-sequent). Find cuts marks all cut formulas, cycle through cuts enumerates the cuts and centers the screen on the next one.

**Comment by shetzl** [comment]
As discussed in yesterday's gapt meeting, our policy for prooftool for the 2.0 release is to keep the overall structure as it is (i.e. only one window) but to consider prooftool a viewer only. All proof transformations, etc. should be done in the CLI. Accordingly, the menus should be changed to:
* File [with current functionality]
* View
  * Zoom In
  * Zoom Out
  * -----
  * (yes/no checkmark) Hide structural rules [ subsumes show all rules ]
  * (yes/no checkmark) Hide sequent contexts [ subsumes show all formulas ]
  * (yes/no checkmark) Mark cut-ancestors [ subsumes remove marking ]
  * -----
  * Expansion proof
  * LK proof
  * Sunburst
  
The other menus and menu items should be removed.

**Comment by gebner** [comment]
Fixed by merging the prooftool-mw branch.
