### ISSUE TITLE
prooftool: closing windows kills CLI

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#415]
Start the CLI and - from within in the CLI - start prooftool, e.g. by:
```
gapt> prooftool( LinearExampleProof( 4 ))
```
Then close the prooftool window (through the window manager). This also closes the CLI. This behaviour is counterintuitive. Instead, when the prooftool window is closed via the window manager, the user should be dropped back into the CLI (this is the way File->Exit works).

**Comment by gebner** [comment]
Interestingly this "feature" only works in `cli.sh`, not in `sbt console`.
