### ISSUE TITLE
HOLPositions do not commute with substitution

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#418]
For first order terms the following is clear: if a term defined at a position and we apply a substitution, then the substituted term is also defined at that position, and substitution commutes with the operation of taking the subterm at that position:
```
t|_p σ = tσ |_p
```

This is true for LambdaPositions as well, but not for HOLPositions:
```scala
val X = Var("X", To -> (To -> To))
val p = FOLAtomHead("p", 1)
val c = FOLConst("c")
val q = FOLAtom("q")

val formula = X(p(c), q)
val position = HOLPosition(1, 2)
val subst = Substitution(X -> AndC())

println(subst(formula(position)))
println(subst(formula)(position))
```
prints
```
p(c)
c
```

**Comment by loewenheim** [comment]
This follows from the design of HOLPositions. The difference between them and LambdaPositions is that they handle logical connectives in a natural manner. This very fact screws you over if you turn a variable into a logical connective. I actually have no idea what to do about this. Stefan?

**Comment by gebner** [comment]
ccing @shetzl so that he sees it

**Comment by shetzl** [comment]
Is there a concrete problem caused by this non-commutation (like an algorithm who relies on it and fails)? If not, I would suggest to keep the HOLPositions as they are.But it is an important observation that the infix treatment of logical connectives implies this non-commutation. To avoid forgetting that, this could be mentioned, e.g., in the scaladoc of HOLPosition.

**Comment by gebner** [comment]
No there's nothing broken at the moment because of the non-commutativity; this came up when thinking about how to do cut-elimination with equality.  Come to think of it, another related interesting feature of HOLPositions is the following:  replacing subterms at two parallel positions can be non-commutative.

But I guess that for cut-elimination we cannot copy the positions anyhow as we're beta-normalizing in each step...
