### ISSUE TITLE
Create   a   scala   check   random   LKProof   generator

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#42]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 20, 2009 15:40:51_

In order to test algorithms on LK we would like to have a scala check LK
proof test cases.
The generator should conform to the scala check requirements and create
random proofs. It should always include the empty proof ( |- ) and also
include proofs with many axioms and not only ones with a linear structure

_Original issue: http://code.google.com/p/gapt/issues/detail?id=42_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on December 10, 2009 05:37:37_

first order term generation is complete, the next steps are generating proofs without
quantifiers and cuts and in the next two steps introducing both rules.

**Summary:** Create a scala check random LKProof generator  
**Owner:** Martin.Riener  
**Cc:** cdunchev

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 09:53:59_

**Labels:** -Priority-Medium Priority-Low

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 12:07:33_

**Labels:** Type-Feature

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:22:28_

**Labels:** -Component-Testings

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:38:19_

**Labels:** Component-Testing

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 23, 2011 13:42:35_

**Labels:** Milestone-Release3.0

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:38:28_

**Owner:** bruno...@gmail.com

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:42:38_

**Summary:** Create   a   scala   check   random   LKProof   generator  
**Owner:** ---  
**Cc:** -cdunc...@gmail.com

**Comment by shetzl** [comment]
I am closing this issue as "wontfix" since a) the concept of a random proof is not very meaningful and b) we have sufficient supply of proofs from the prover9-TSTP, leanCoP-TSTP and veriT-SMT-LIB for testing purposes.
