### ISSUE TITLE
Help command in cli missing

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#421]
Before the cli rewrite, there was a help command. Has it been renamed?

**Comment by gebner** [comment]
Yes, I removed the `help` command together with the CLI aliases.  The user manual still mentioned it, thanks for noticing it, the reference is gone now as well.

The rationale for the removal of the `help` command was the same as for the CLI wrappers:
* It only listed the CLI aliases.
* You had to use code from other packages anyhow, which were not documented in `help`, e.g. constructing formulas, proofs, etc..
* It was unmaintained and outdated.

Honestly, even if we'd find a maintainer for it, I don't know what to put in a `help` command:
* How to construct expressions, LK proofs, resolution proofs, etc.? (This is actually one of the first things our latest two newcomers wanted to do.  Looking at it from the other side, I had this very issue myself when trying out the OCaml code to Harrison's Handbook of Practical Logic and Automated Reasoning)
* How to call external provers?
* All the functionality necessary to try out the stuff presented in our papers?

Honestly, I think for the last point it's a better idea to have paper-specific "walkthroughs" in the user manual, with one section for each paper or so.

**Comment by quicquid** [comment]
My use case for the help was that I often forget if I should call loadProofDatabase, loadProofDB or loadProofDb. Then I found out the CLI simplifications needed to move that code into the XMLProofDatabaseParser object(a perfectly fine case of refactoring). For me this isn't a problem, but I guess as end-user, you'd like to have a list of advised commands available, because the API is too big.

Regarding maintenance: At some point I was thinking about putting a help string into the object itself and letting it register with the help object. Perhaps via a trait CLICommand which provides the interface. If you like the idea and I have time, I'll implement something like this.

**Comment by shetzl** [comment]
> I guess as end-user, you'd like to have a list of advised commands available in the system, because the API is too big.

I agree and I would suggest to put this information in the user's guide. It should contain in each subsection a brief description of a particular feature and an illustration how to use it by a sequence of CLI-commands. This way, a novice user can start to work with the system by reading the user's guide and trying out the commands described there in the CLI.
