### ISSUE TITLE
Unintuitive eigenvariable condition

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#423]
Currently, the `ForallRightRule` allows you to conclude `All(x, p(x,x))` from `p(x,y)`.  As far as I can tell this is sound, but does this make sense and do we want to allow that?

**Comment by shetzl** [comment]
This is a bug. In a ForallRightRule, if the main formula is \forall x. A, then the auxiliary formula must by A[x\y]. This is not the case here.
