### ISSUE TITLE
VeriT.getExpansionSequent: fails if x is a free variable

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#438]
```scala
VeriT getExpansionSequent (Sequent() :+ Eq(FOLVar("x"), FOLVar("x")))
```
prints
```
java.lang.AssertionError: assertion failed: formulaToExpansionTree: substitutions have variable capture.
  at scala.Predef$.assert(Predef.scala:165)
  at at.logic.gapt.proofs.expansionTrees.formulaToExpansionTree$.apply(expansionTrees.scala:463)
  at at.logic.gapt.formats.veriT.VeriTParser$$anonfun$proof$4$$anonfun$21.apply(VeriTParser.scala:307)
  at at.logic.gapt.formats.veriT.VeriTParser$$anonfun$proof$4$$anonfun$21.apply(VeriTParser.scala:294)
  at scala.collection.immutable.List.map(List.scala:273)
  at at.logic.gapt.formats.veriT.VeriTParser$$anonfun$proof$4.apply(VeriTParser.scala:294)
  at at.logic.gapt.formats.veriT.VeriTParser$$anonfun$proof$4.apply(VeriTParser.scala:263)
...
```

**Comment by loewenheim** [comment]
`formulaToExpansionTree` is called twice: once on the formula x ≠ x and once on ∀x. x = x. In the second case, the (pointless) substitution x → x is used, and this substitution violates the variable capturing condition. Do you have any idea what's going on here?

**Comment by gebner** [comment]
The veriT parser wants to create an expansion tree for `forall x, x = x` where the weak quantifier `x` is instantiated with `x`, hence it calls `formulaToExpansionTree(refl, List(Substitution(x->x)))`.

As far as I can tell, there is nothing wrong with such substitutions, at least if we only have weak quantifiers.  For strong quantifiers, we should do better validation anyhow (and this check would have been pointless anyway).

However, we get an interesting expansion sequent now:
```
scala> toDeep(VeriT getExpansionSequent (Sequent() :+ Eq(FOLVar("x"), FOLVar("x"))) get)
res2: at.logic.gapt.proofs.HOLSequent = (x=x⊃x=x), x=x :- x=x
```

**Comment by gebner** [comment]
Okay, of course there is something wrong with... the implementation.  We require that the bound variables in the shallow formula do not change in the recursive call, but they would change if we substitute terms that contain bound variables...

**Comment by shetzl** [comment]
In order to avoid variable capture it is enough to require that, whenever A\sigma is computed, then rge(\sigma) does not contain a variable that is bound in A.

This would allow to instantiate x with x in \forall x. x = x, because x is not bound in x=x. However, it would prevent to instantiate x with y in \forall x\exists y f(x)=y because y is bound in \exists y f(x)=y.

**Comment by gebner** [comment]
This is essentially the criterion that is checked now; but that fails as well if you want to instantiate `forall x, forall y, P(x,y)` with `x -> y` and `y -> x`, which is perfectly fine.

I guess one ugly workaround is to rename the variables in the formula and the domain of the substitution if they intersect.
