### ISSUE TITLE
prooftool: do not use latex formatting for formulas by default

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#440]
When viewing an LK proof imported from a prover9 TSTP solution file, it looks like this:
![unreadable-latexification](https://cloud.githubusercontent.com/assets/313929/10968350/dce12b2c-83c0-11e5-8962-70cb71c718fb.png)

While the latex typesetting is nice for constant names which are valid latex code, for most proofs the latex typesetting produces fairly unreadable rendering as can be seen above.

BTW, why does the font change in the middle of the formula?

(This is the code I ran:)
```scala
prooftool(CutIntroduction.compressLKProof(Prover9Importer.lkProofFromFile(glob("**/SWV596-1/Prover9*.s.out").head), verbose=true))
```

**Comment by quicquid** [comment]
When I was using unicode for the formulas in a very early version of prooftool, it looked horrible. That and the fact that all legacy proofs were using some Latex notation was the reason to use the Latex viewer instead. At some point there was also code for escaping underscore to fix TPTP proofs, but if i remember correctly it was removed.

**Comment by shetzl** [comment]
There should be a switch in prooftool to change between escaping or non-escaping of underscores.
