### ISSUE TITLE
Skolemization is not well-defined in presence of definitions

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#444]
I hit upon a problem while testing ProofContexts. Say both of these definitions occur in a proof:

    ∃x A, Γ :- Δ
    --------------(d:l)
       B, Γ :- Δ

     Π :- Λ, ∃x A
    -------------(d:r)
     Π :- Λ, B

Normally this is totally innocuous, but what if we want to Skolemize the proof? One of the occurrences of ```∃x A``` will be changed, the other one will be preserved. This means that ```B``` is now defined as two different formulas. In the branch where I have implemented ProofContexts, the ```PrimeProofTest``` fails for this reason. How should we handle this? One way would be to simply exclude defined formulas (```∃x A``` in this example) from Skolemization.

**Comment by quicquid** [comment]
The way we handled prooofs with definitions was to remove the rules and always rewrite to the defined formula. This does not work for the prime proof though, because it only contains the general definition D_n := ... but the proof contains the instances D_1, D_2, etc and our definition removal does not handle it at the moment.

**Comment by gebner** [comment]
We have at least 9 prime proofs in src/test/resources and none of the seem to contain the string `D_1`, where does this occur exactly?

The concrete definition in the prime proof that causes this problem is `DIV(l,k) = exists l, l*r = k`, can't we eliminate this one?

**Comment by gebner** [comment]
With the new definition rules (see #561), we have decided to drop support for definition rules in `skolemize`, i.e. the (first-order only) Skolemization that returns a proof of the Skolemized end-sequent.  As an alternative, there is `skolemizeInferences`, which uses the Skolem rules and trivially works with definitions.
