### ISSUE TITLE
Strange error message in CLI when using Top in HOLClause

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#451]
I tried the following at the CLI and recieved the expected error that Top() is not of the correct type:

     val x : HOLAtom = Top()

But then I tried the following:

    Prover9.getRobinsonProof(HOLClause(Top()::Nil, Nil) ) 

and recieved:

    java.lang.ClassCastException: at.logic.gapt.expr.determineTraits$Const_with_PropConnective_with_PropFormula cannot be cast to at.logic.gapt.expr.HOLAtom
      at at.logic.gapt.proofs.HOLClause$$anonfun$apply$10.apply(sequents.scala:454)
      at at.logic.gapt.proofs.HOLClause$$anonfun$apply$10.apply(sequents.scala:454)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
      at scala.collection.immutable.List.map(List.scala:285)
      at at.logic.gapt.proofs.HOLClause$.apply(sequents.scala:454)
      ... 30 elided

Funnily, calling:

          val x = HOLClause(Top()::Nil, Nil)
returns

    <console>:109: error: at.logic.gapt.proofs.HOLClause.type does not take parameters
          val x = HOLClause(Top()::Nil, Nil)

Apparently, scala's type inference is not good enough to verify the HOLAtom requirement before execution. I'm not sure if it makes sense to work around this in the code, my proposition would be to document this behaviour in the user manual.

@gebner, @shetzl what do you think?

**Comment by gebner** [comment]
Scala's type inference is just fine, we just had a bit of old code lying around from before we had type-parametric sequents:
```scala
def apply( negative: Seq[HOLFormula], positive: Seq[HOLFormula] ): HOLClause = {		
  HOLClause( negative map { _.asInstanceOf[HOLAtom] },
    positive map { _.asInstanceOf[HOLAtom] } )		
}
```

Regarding your remark at the end:
> `<console>:109: error: at.logic.gapt.proofs.HOLClause.type does not take parameters`

This is a different, although very interesting, bug:
```
scala> FOLAtom("p") +: Clause()
res0: at.logic.gapt.proofs.Sequent[at.logic.gapt.expr.FOLAtom] = p :-

scala> FOLAtom("p") +: Clause()
<console>:116: error: at.logic.gapt.proofs.Clause.type does not take parameters
       FOLAtom("p") +: Clause()
```

Yes, I have entered the same code twice.  The first time it works as expected, the second time I get an error.  I've got no idea what happens here.

**Comment by quicquid** [comment]
Well that's pretty weird... anyway, I guess this is just one more peculiarity of the CLI.

**Comment by gebner** [comment]
I think this happened because the companion object for `Clause` was defined in the package `proofs` while the type alias was defined in the package *object*.  This particular problem is fixed now:
```
scala> FOLAtom("p") +: Clause()
res0: at.logic.gapt.proofs.Sequent[at.logic.gapt.expr.FOLAtom] = p :-

scala> FOLAtom("p") +: Clause()
res1: at.logic.gapt.proofs.Sequent[at.logic.gapt.expr.FOLAtom] = p :-

```
