### ISSUE TITLE
Remove old LLK/LKsk and rename llkNew/lkskNew to llk/lksk

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#453]
@quicquid Do we need the old LLK implementation anymore?

**Comment by quicquid** [comment]
In principle not, but since i didn't manage to run the proofs i did for my phd with the new ceres omega yet, I'd feel safer to keep it for backup, if that's ok for you.

**Comment by gebner** [comment]
Ok, let's leave it for now.

**Comment by gebner** [comment]
We should also remove the old LKsk implementation and rename lkskNew to lksk as soon as your PhD thesis works again.

**Comment by quicquid** [comment]
Working on that :-) My generated clause sets already agree up to the names of skolem symbols. Unfortunately, it's not a bijection.
