### ISSUE TITLE
Test fails without Vampire on Windows 10

### ISSUE THREAD

**Issue by alexanderbirch** [gapt/gapt#461]
"sbt test" fails without the Vampire external software on Windows 10 with the following error:

   `[error] Error: Total 1275, Failed 0, Errors 5, Passed 1108, Skipped 162`
   `[error] Error during tests:`
   `[error]         at.logic.gapt.formats.tptp.TptpProofParserTest`
   `[error]         at.logic.gapt.provers.vampire.VampireTest`
   `[error] (root/test:test) sbt.TestsFailedException: Tests unsuccessful`

Unfortunately, I cannot provide a more detailed error log than this.

**Comment by gebner** [comment]
Can you please run in the sbt shell and copy the output here:
* `testOnly *.TptpProofParserTest`
* `testOnly *Vampire*`

And also try out the `vampire-v2` branch for the vampire test?

**Comment by alexanderbirch** [comment]
For the master branch I get the following errors:

    > testOnly *.TptpProofParserTest
    [info] TptpProofParserTest
    [info]
    [error] ! RNG103+2_E---1.9.THM-CRf.s
    [error]  scala.MatchError: [1.1] failure: `fof' expected but `%' found
    [error]
    [error]  %------------------------------------------------------------------------------
    [error]
    [error]  ^ (of class scala.util.parsing.combinator.Parsers$Failure) (tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParser$.parse(tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:26)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:25)
    [info]
    [error] ! ALG011-1_Metis---2.3.UNS-CRf.s
    [error]  scala.MatchError: [1.1] failure: `fof' expected but `%' found
    [error]
    [error]  %------------------------------------------------------------------------------
    [error]
    [error]  ^ (of class scala.util.parsing.combinator.Parsers$Failure) (tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParser$.parse(tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:26)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:25)
    [info]
    [info] o GEO008-3_iprover-1.4.tptp
    [info] skipped
    [error] ! LCL101-1_Vampire---4.0.UNS-REF.s
    [error]  scala.MatchError: [1.1] failure: `fof' expected but `%' found
    [error]
    [error]  %------------------------------------------------------------------------------
    [error]
    [error]  ^ (of class scala.util.parsing.combinator.Parsers$Failure) (tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParser$.parse(tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:26)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:25)
    [info]
    [error] ! HEN005-6_SPASS-3.7.UNS-Ref.s
    [error]  scala.MatchError: [1.1] failure: `fof' expected but `%' found
    [error]
    [error]  %------------------------------------------------------------------------------
    [error]
    [error]  ^ (of class scala.util.parsing.combinator.Parsers$Failure) (tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParser$.parse(tptpProofParser.scala:42)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:26)
    [error] at.logic.gapt.formats.tptp.TptpProofParserTest$$anonfun$1$$anonfun$apply$3.apply(TptpProofParserTest.scala:25)
    [info]
    [info]
    [info]
    [info] Total for specification TptpProofParserTest
    [info] Finished in 603 ms
    [info] 5 examples, 0 failure, 4 errors, 1 skipped
    [info]
    [error] Error: Total 5, Failed 0, Errors 4, Passed 0, Skipped 1
    [error] Error during tests:
    [error]         at.logic.gapt.formats.tptp.TptpProofParserTest
    [error] (root/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
    [error] Total time: 7 s, completed 18-12-2015 14:40:39
    
    
    
    > testOnly *Vampire*
    [error]
    [error] cannot create an instance for class at.logic.gapt.provers.vampire.VampireTest
    [error]   caused by at.logic.gapt.provers.vampire.VampireException: Unable to determine vampire's binary name for your OS!
    [error]
    [error] STACKTRACE
    [error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    [error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    [error]   java.lang.reflect.Constructor.newInstance(Unknown Source)
    [error]   org.specs2.reflect.Classes$$anonfun$org$specs2$reflect$Classes$$createInstanceForConstructor$1.apply(Classes.scala:104)
    [error]   org.specs2.control.ActionT$$anonfun$safe$1.apply(ActionT.scala:88)
    [error]   org.specs2.control.ActionT$$anonfun$reader$1$$anonfun$apply$6.apply(ActionT.scala:79)
    [error]   org.specs2.control.Status$.safe(Status.scala:100)
    [error]   org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
    [error]   org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
    [error]   scalaz.syntax.ToApplicativeOps$$anon$1.self$lzycompute(ApplicativeSyntax.scala:29)
    [error]   scalaz.syntax.ToApplicativeOps$$anon$1.self(ApplicativeSyntax.scala:29)
    [error]   scalaz.syntax.ToApplicativeOps$ApplicativeIdV$$anonfun$point$1.apply(ApplicativeSyntax.scala:33)
    [error]   scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:309)
    [error]   scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:309)
    [error]   scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
    [error]   scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
    [error]   scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
    [error]   scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
    [error]   scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
    [error]   scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
    [error]   scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
    [error]   scalaz.Free.go2$1(Free.scala:119)
    [error]   scalaz.Free.go(Free.scala:122)
    [error]   scalaz.Free.run(Free.scala:172)
    [error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22
    [error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1$$anonfun$3.apply(Classes.scala:37)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1$$anonfun$3.apply(Classes.scala:36)
    [error]   scala.collection.immutable.List.map(List.scala:273)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1.apply(Classes.scala:36)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1.apply(Classes.scala:29)
    [error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    [error]   org.specs2.control.Status$class.fold(Status.scala:30)
    [error]   org.specs2.control.Ok.fold(Status.scala:95)
    [error]   org.specs2.control.Status$class.flatMap(Status.scala:48)
    [error]   org.specs2.control.Ok.flatMap(Status.scala:95)
    [error]   org.specs2.control.Status$class.map(Status.scala:45)
    [error]   org.specs2.control.Ok.map(Status.scala:95)
    [error]   org.specs2.control.StatusT$$anonfun$map$1.apply(StatusT.scala:16)
    [error]   org.specs2.control.StatusT$$anonfun$map$1.apply(StatusT.scala:16)
    [error]   scalaz.WriterT$$anonfun$map$1.apply(WriterT.scala:46)
    [error]   scalaz.WriterT$$anonfun$map$1.apply(WriterT.scala:46)
    [error]   scalaz.effect.IO$$anonfun$map$1$$anonfun$apply$8.apply(IO.scala:56)
    [error]   scalaz.effect.IO$$anonfun$map$1$$anonfun$apply$8.apply(IO.scala:55)
    [error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    [error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    [error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
    [error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
    [error]   scalaz.Free.resume(Free.scala:72)
    [error]   scalaz.Free.go2$1(Free.scala:118)
    [error]   scalaz.Free.go(Free.scala:122)
    [error]   scalaz.Free.run(Free.scala:172)
    [error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
    [error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
    [error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:37)
    [error]   sbt.ForkMain$Run$2.call(ForkMain.java:296)
    [error]   sbt.ForkMain$Run$2.call(ForkMain.java:286)
    [error]   java.util.concurrent.FutureTask.run(Unknown Source)
    [error]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    [error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    [error]   java.lang.Thread.run(Unknown Source)
    [error]
    [error]   CAUSED BY at.logic.gapt.provers.vampire.VampireException: Unable to determine vampire's binary name for your OS!
    [error]   at.logic.gapt.provers.vampire.Vampire$.exec(vampire.scala:32)
    [error]   at.logic.gapt.provers.vampire.Vampire$.refute(vampire.scala:52)
    [error]   at.logic.gapt.provers.vampire.Vampire$.refuteNamed(vampire.scala:61)
    [error]   at.logic.gapt.provers.vampire.Vampire$.refute(vampire.scala:70)
    [error]   at.logic.gapt.provers.vampire.Vampire$.refute(vampire.scala:77)
    [error]   at.logic.gapt.provers.vampire.Vampire$.isInstalled(vampire.scala:97)
    [error]   at.logic.gapt.provers.vampire.VampireTest$$anonfun$1.apply$mcZ$sp(vampireTest.scala:14)
    [error]   at.logic.gapt.provers.vampire.VampireTest$$anonfun$1.apply(vampireTest.scala:14)
    [error]   at.logic.gapt.provers.vampire.VampireTest$$anonfun$1.apply(vampireTest.scala:14)
    [error]   org.specs2.control.Property$$anonfun$apply$2.apply(Property.scala:67)
    [error]   org.specs2.control.Property$$anonfun$apply$2.apply(Property.scala:67)
    [error]   org.specs2.control.Property.execute(Property.scala:51)
    [error]   org.specs2.control.Property.optionalValue(Property.scala:17)
    [error]   org.specs2.control.Property.toOption(Property.scala:19)
    [error]   org.specs2.main.ArgProperty.toOption(ArgumentsArgs.scala:154)
    [error]   org.specs2.main.ArgumentsCreation$ArgumentsNamespace.execute(ArgumentsArgs.scala:87)
    [error]   org.specs2.main.ArgumentsCreation$class.args(ArgumentsArgs.scala:43)
    [error]   org.specs2.mutable.Specification.org$specs2$specification$dsl$mutable$ArgumentsCreation$$super$args(Specification.scala:15)
    [error]   org.specs2.specification.dsl.mutable.ArgumentsCreation$class.args(ArgumentsDsl.scala:41)
    [error]   org.specs2.mutable.Specification.args(Specification.scala:15)
    [error]   at.logic.gapt.provers.vampire.VampireTest.<init>(vampireTest.scala:14)
    [error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    [error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    [error]   java.lang.reflect.Constructor.newInstance(Unknown Source)
    [error]   org.specs2.reflect.Classes$$anonfun$org$specs2$reflect$Classes$$createInstanceForConstructor$1.apply(Classes.scala:104)
    [error]   org.specs2.control.ActionT$$anonfun$safe$1.apply(ActionT.scala:88)
    [error]   org.specs2.control.ActionT$$anonfun$reader$1$$anonfun$apply$6.apply(ActionT.scala:79)
    [error]   org.specs2.control.Status$.safe(Status.scala:100)
    [error]   org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
    [error]   org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
    [error]   scalaz.syntax.ToApplicativeOps$$anon$1.self$lzycompute(ApplicativeSyntax.scala:29)
    [error]   scalaz.syntax.ToApplicativeOps$$anon$1.self(ApplicativeSyntax.scala:29)
    [error]   scalaz.syntax.ToApplicativeOps$ApplicativeIdV$$anonfun$point$1.apply(ApplicativeSyntax.scala:33)
    [error]   scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:309)
    [error]   scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:309)
    [error]   scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
    [error]   scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
    [error]   scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
    [error]   scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
    [error]   scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
    [error]   scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
    [error]   scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
    [error]   scalaz.Free.go2$1(Free.scala:119)
    [error]   scalaz.Free.go(Free.scala:122)
    [error]   scalaz.Free.run(Free.scala:172)
    [error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
    [error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1$$anonfun$3.apply(Classes.scala:37)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1$$anonfun$3.apply(Classes.scala:36)
    [error]   scala.collection.immutable.List.map(List.scala:273)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1.apply(Classes.scala:36)
    [error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1.apply(Classes.scala:29)
    [error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    [error]   org.specs2.control.Status$class.fold(Status.scala:30)
    [error]   org.specs2.control.Ok.fold(Status.scala:95)
    [error]   org.specs2.control.Status$class.flatMap(Status.scala:48)
    [error]   org.specs2.control.Ok.flatMap(Status.scala:95)
    [error]   org.specs2.control.Status$class.map(Status.scala:45)
    [error]   org.specs2.control.Ok.map(Status.scala:95)
    [error]   org.specs2.control.StatusT$$anonfun$map$1.apply(StatusT.scala:16)
    [error]   org.specs2.control.StatusT$$anonfun$map$1.apply(StatusT.scala:16)
    [error]   scalaz.WriterT$$anonfun$map$1.apply(WriterT.scala:46)
    [error]   scalaz.WriterT$$anonfun$map$1.apply(WriterT.scala:46)
    [error]   scalaz.effect.IO$$anonfun$map$1$$anonfun$apply$8.apply(IO.scala:56)
    [error]   scalaz.effect.IO$$anonfun$map$1$$anonfun$apply$8.apply(IO.scala:55)
    [error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    [error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
    [error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
    [error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
    [error]   scalaz.Free.resume(Free.scala:72)
    [error]   scalaz.Free.go2$1(Free.scala:118)
    [error]   scalaz.Free.go(Free.scala:122)
    [error]   scalaz.Free.run(Free.scala:172)
    [error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
    [error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
    [error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:37)
    [error]   sbt.ForkMain$Run$2.call(ForkMain.java:296)
    [error]   sbt.ForkMain$Run$2.call(ForkMain.java:286)
    [error]   java.util.concurrent.FutureTask.run(Unknown Source)
    [error]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    [error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    [error]   java.lang.Thread.run(Unknown Source)
    [error]
    [error] Error: Total 1, Failed 0, Errors 1, Passed 0
    [error] Error during tests:
    [error]         at.logic.gapt.provers.vampire.VampireTest
    [error] (root/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
    [error] Total time: 4 s, completed 18-12-2015 14:42:03
    >

The `vampire-v2` branch seems to skip the Vampire test without problems.

    > testOnly *Vampire*
    ...
    [info] VampireTest
    [info]
    [info] The Vampire interface should
    [info]   o refute { :- P; P :- }
    [info] SKIPPED
    [info] The Vampire interface should
    [info]   o prove SKKx = Ix : { :- f(a,x) = x; :- f(f(f(b,x),y),z) = f(f(x,z), f(y,z)); :- f(f(c,x),y) = x; f(f(f(b,c),c),x) = f(a,x) :- }
    [info] SKIPPED
    [info] The Vampire interface should
    [info]   o not refute { :- P; Q :- }
    [info] SKIPPED
    [info] Vampire should
    [info]   o prove identity
    [info] SKIPPED
    [info]   o prove { A or B :- -(-A and -B)  }
    [info] SKIPPED
    [info]   o handle quantified antecedents
    [info] SKIPPED
    [info]   o prove top
    [info] SKIPPED
    [info]   o not prove bottom
    [info] SKIPPED
    [info]   o not refute top
    [info] SKIPPED
    [info]   o refute bottom
    [info] SKIPPED
    [info]   o ground sequents
    [info] SKIPPED
    [info]   o treat variables in sequents as constants
    [info] SKIPPED
    [info]   o handle weird sequents
    [info] SKIPPED
    [info]   o large cnf
    [info] SKIPPED
    [info]
    [info]
    [info] Total for specification VampireTest
    [info] Finished in 0 ms
    [info] 14 examples, 0 failure, 0 error, 14 skipped
    [info]
    [info] Passed: Total 14, Failed 0, Errors 0, Passed 0, Skipped 14

I hope this was helpful.

**Comment by gebner** [comment]
Can you try again with the latest master?

**Comment by alexanderbirch** [comment]
Now it simply skips both, which I guess is intended. So it should be fixed!
