### ISSUE TITLE
ExpansionProofToLK fails on expansion proof with weak formula

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#464]
Do the following in the CLI:
```
val et = LKToExpansionProof( CERES( Pi2Pigeonhole() ))
val p = ExpansionProofToLK( et )
```
This fails with
```
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:347)
  at scala.None$.get(Option.scala:345)
  at at.logic.gapt.proofs.expansionTrees.ExpansionProofToLK$.apply(expansionTrees.scala:434)
```

This may be related to the formula ∀x.∀y.(<=(s(x),y)⊃<=(x,y)) being without any instances in et.

**Comment by gebner** [comment]
Nope, the proof just uses equational reasoning.  The deep formula of the extracted expansion proof is only quasi-tautological, and hence `ExpansionProofToLK` can't prove it.

**Comment by gebner** [comment]
FWIW, one way to solve this would be to call a resolution prover on the quantifier-free subgoals in `ExpansionProofToLK`.
