### ISSUE TITLE
Scrolling works only in first Prooftool window opened

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#466]
On the cli call:

    val p = loadLLK("examples/hol-tape/ntape3.llk").proof("TAPEPROOF")
    prooftool(p)
    prooftool(p)

One window has scrolling, the other doesn't.

**Comment by loewenheim** [comment]
I think so far no one has been able to reproduce this.

**Comment by quicquid** [comment]
Yes, it vanished after updating to Java 8. Closing.
