### ISSUE TITLE
CERES with skip equations fails on new lattice proof

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#475]
On the cli try the following:

```
val elp = AtomicExpansion( DefinitionElimination( lattice.defs )( regularize( lattice.p ) ) )
val selp = skolemize(elp)
val cproof1 = CERES(selp, CERES.skipNothing)
val cproof2 = CERES(selp, CERES.skipEquations)
```

The last call yields a "Prover9 could not refute the characteristic clause set!" exception. Indeed the CSS seems satisfiable (see attached file lattice-skip), since the only equation simplifying a term is ```x \cap y = x```, but there is nothing simplifying a term with ```\cup``` in the root position.

[lattice-skip-css.pdf](https://github.com/gapt/gapt/files/117845/lattice-skip-css.pdf)
[lattice-noskip-css.pdf](https://github.com/gapt/gapt/files/117847/lattice-noskip-css.pdf)

**Comment by quicquid** [comment]
[lattice-veryold.pdf](https://github.com/gapt/gapt/files/119129/lattice-veryold.pdf)

Since it is not in the paper, that's the clause set generated from the old proof before the rewrite. (Definition elimination didn't work but the definitions don't appear in the clause set)

**Comment by gebner** [comment]
This has been working for almost two months now.
