### ISSUE TITLE
"Natural" notation for sequents

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#480]
If we wanted—and personally, I kind of do—we could add an operator (say `:-` or `|-`) to the `Seq` class that would allow us to write sequents rather elegantly:

```
Seq(1,2,3) :- Seq(4,5,6)
```
would produce the Sequent 1,2,3 :- 4,5,6.

**Comment by gebner** [comment]
Can we overload this to work on tuples?  IMHO the following looks even nicer:
```scala
(1,2,3) :- (4,5,6)
```

**Comment by quicquid** [comment]
I attempted to do

    def :-[T] (ant : T*)(succ : T*) = Sequent[T](ant,succ)

but this only works as a prefix operator:

    gapt> (:-) (1,2,3) (4,5,6)
    res6: at.logic.gapt.proofs.Sequent[Int] = 1, 2, 3 :- 4, 5, 6

Used infix it expands to:

    gapt> (1,2,3) :- (4,5,6)
    <console>:112: error: value :- is not a member of (Int, Int, Int)
          (1,2,3) :- (4,5,6)

I thought about trying some implicit magic of converting the antecedent list to the sequent ```1,2,3 :-``` and defining Sequent[T].:- on Iterable[T]. Not sure if it's a good idea to have implicit conversions for arbirary sequences lying around though.

**Comment by loewenheim** [comment]
What I wrote in the OP is definitely possible (indeed using dark implicit class magic), but I can't figure out a way to make it work with varargs, which would be the most aesthetically pleasing variant.

**Comment by quicquid** [comment]
Yeah, the Seq solution is surprisingly simple:

    implicit class VDash[T](val antecedent : Seq[T]) extends AnyVal { 
      def :- (succedent : Seq[T]) = Sequent[T](antecedent,succedent)
     }

It seems there is an approach using Product instead of T* works at the cost of type safety. It seems there's a lot of magic necessary to make it work - at least when I look at the answers to [http://stackoverflow.com/questions/16879175/magnet-pattern-with-repeated-parameters-varargs](url)

**Comment by loewenheim** [comment]
The Seq solution needs to be modified slightly:
```
implicit class VDash[T](val antecedent : Seq[T]) extends AnyVal { 
  def :-[S >: T] (succedent : Seq[S]) = Sequent[S](antecedent,succedent)
 }
```

Otherwise the variance won't work. I have a suspicion that this is as good as it's likely to get. Not that this isn't a marked improvement over the status quo, imho.

**Comment by loewenheim** [comment]
Since we have such a snazzy new parser now, maybe the best way to do it would be to extend said parser so that it can parse sequents in addition to formulas?

**Comment by gebner** [comment]
I think the syntax is clear--both `:-` and `⊢` are still available (`|-` is already used as a combination of logical connectives, and `ト` is an identifier).

I'm not so sure about the semantics, however.  What is there to decide?
* Does type inference work across elements of a sequent?  (for variables, for constants?)
* Do constants need to be consistent across elements?
* What about the types of the elements?  (Do they need to be of type `o`?)

In any case, one important property that I'd like to have is the following (for all sequents of lambda expressions, or at the very very least HOL formulas):
```scala
parseSequent(sequent.toString) == sequent
```

**Comment by gebner** [comment]
It would also be nice to have a string interpolator for clauses, then.

**Comment by gebner** [comment]
This would be really nice on the CLI.  To make this proposal a bit more concrete, any objections to the following?
```scala
Seq(f1,f2) :- Seq(f3,f4)
hos"a, b :- c, d"
hoc"a, b :- c, d"
fos"a, b :- c, d"
foc"a, b :- c, d"
hos"a, b ⊢ c, d"
hoc"a, b ⊢ c, d"
fos"a, b ⊢ c, d"
foc"a, b ⊢ c, d"
```

**Comment by gebner** [comment]
Ah, `hoc` is already used for higher-order constant.   Any ideas for higher-order clause?

**Comment by loewenheim** [comment]
I like all of these suggestions, but I can't think of a prefix for clauses either.

**Comment by quicquid** [comment]
What about ```hcl`` ? It (dis-)solves quite a lot of stuff :-)

**Comment by gebner** [comment]
Thanks for the suggestion, Martin!  It's now `hcl` and `fcl`.
