### ISSUE TITLE
Add examples to API documentation

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#483]
Right now, if I enter ```help(lattice)```, I get pointed to https://logic.at/gapt/api/#at.logic.gapt.examples.lattice$, which provides the api menu, but gives a 404 error for the concrete class. Is it possible to add the examples to the api documentation?

**Comment by gebner** [comment]
So this should work now if you have built the docs locally, i.e. using `sbt unidoc`.  For the logic.at version, I think the cron job needs to be updated, this is done from your account, right?

**Comment by quicquid** [comment]
Just saw this open: some paths needed to be adjusted in my script, it should work fine again.

**Comment by gebner** [comment]
Great!
