### ISSUE TITLE
Use of definitions in the prime proof

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#487]
In the prime proof (and in the paper it's based on), there are definitions like `m ∈ ν(k, l) ⇔ ∃n m = k + n*l`. This is not a definition in the sense we discussed: we're not strictly speaking defining the symbol `ν` but rather what it means to be a member of the set. The complement is similar.

How should we handle this? Arguably these formulas should be theory axioms or something similar.

**Comment by gebner** [comment]
Hmm, in some sense it actually is a definition in the sense we discussed.  If we define `in` as `\x\X X(x)` i.e. of type `i>(i>o)>o`, then we can define `nu` as `\k\l\m ?n m=k+n*l`.

AFAICT using second order logic in this way does not break CERES (here).
The clause set seems to only depend on
1) the axioms (which are still atomic FOL),
2) the binary inferences (these are not affected by this change), and
3) the ancestor relation (which does not change either).
Projecting the proof onto the clauses should still work as well, I hope.  (NB, this is all just based on a cursory glance of "Methods of Cut-Elimination")

In a way I prefer the second-order treatment, as it is seems more natural for the problem domain at hand.

**Comment by shetzl** [comment]
The prime proof has been used with first-order ceres and should continue to work with first-order ceres. These higher-order definitions are certainly natural, if they don't break the ceres method, I'm fine with that.

**Comment by gebner** [comment]
Amazingly, this seems to work just fine with the current CERES implementation. :+1: @quicquid 

```scala
import at.logic.gapt.examples.TacticsProof
import at.logic.gapt.proofs.{ Context, FiniteContext, Sequent }
import at.logic.gapt.expr._
import at.logic.gapt.proofs.ceres.CERES
import at.logic.gapt.proofs.gaptic._

object secondorderceres extends TacticsProof {
  implicit var ctx = FiniteContext()
  ctx += Context.Sort( "i" )
  ctx += ( "in" -> le"λx λX X(x): o" )
  ctx ++= Seq( hoc"P:i>i>o", hoc"c:i", hoc"f:i>i", hoc"g:i>i" )
  ctx += ( "Q" -> le"λx ∃y P(x,y)" )

  val proofWithCut = Lemma(
    ( "pc" -> hof"∀y P(c, y)" ) +: ( "pf" -> hof"∀x ∀y (P(x, g y) ⊃ P(f x, y))" ) +:
      Sequent()
      :+ ( "goal" -> hof"in(f(f(f(f(c)))), Q)" )
  ) {
      cut( hof"∀x ∀y (P(x, g(g y)) ⊃ P(f(f x), y))", "cut" )
      forget( "goal" ); decompose; repeat( chain( "pf" ) ); prop

      unfold( "goal", "in" ); unfold( "goal", "Q" )
      exR( le"c" ); forget( "goal" )
      repeat( chain( "cut" ) ); chain( "pc" )
    }

  val proofWithoutCut = CERES( proofWithCut )
}
```
