### ISSUE TITLE
Strange interaction between string interpolation and definitions in contexts

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#489]
Try the following:

```
import at.logic.gapt.expr._
import at.logic.gapt.proofs.FiniteContext

implicit var ctx = FiniteContext()

val p = FOLConst("p")
ctx += p

ctx += ("q", le" $p")
```

This results in `java.lang.IllegalArgumentException: requirement failed: In definition q -> #v(__qq_0: i): contains free variables Set(#v(__qq_0: i))`. Why is there still a free variable (the placeholder) at that point? Shouldn't it have been interpolated?

**Comment by gebner** [comment]
The key here is looking at `#v(__qq_0: i)`--it's a variable, but ExpressionParseHelper only replaces constants.

**Comment by gebner** [comment]
The clean solution would be to already replace the placeholder in the AST, then type inference would work as well.  Right now the following doesn't work as expected:
```scala
val f = hof"X(c) <-> X(d)"
val g = hof"?X $f"
g == hof"?X (X(c) <-> X(d))"  // returns false
```

**Comment by loewenheim** [comment]
Is there a good reason for only replacing constants? I can't think of one off the top of my head.

**Comment by gebner** [comment]
No, it just didn't matter previously when `__qq_0` was always parsed as a constant.

**Comment by loewenheim** [comment]
Then I guess I'll just change that bit and see whether it fixes my problem.
