### ISSUE TITLE
LK: Extensionality rule

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#491]
In the prime proof, we use extensionality of sets. In the old proof, this is (rather unnaturally) handled in the form of a definition, that is, X = Y is defined as “X and Y contain the same elements”. There are basically 3 other ways that extensionality could be handled:

1. If you need it, you add it to the antecedent of the sequent in question. I find this inelegant because it clutters up the end sequent(s).
2. Make it a theory axiom. This is currently not easily possible because theory axioms need to be atomic.
3. Gabriel's suggestion: make it a rule of LK. It would look something like this:
```
Γ :- Δ, F α = G α
-------------------(ext)
Γ :- Δ, F = G
```
with α an eigenvariable.

**Comment by gebner** [comment]
Come to think of it, even the extensionality rule in the form of (3) won't be enough: we will probably only be able to prove that `F α ↔ G α`, from this we cannot deduce `F α = G α` at the moment (this is propositional extensionality and we could get it via a creative use of induction on `o`).

**Comment by gebner** [comment]
Needless to say, we can't use induction because CERES.

**Comment by gebner** [comment]
Another possibility: define `exteq X1 X2 = ∀y (X1 y <-> X2 y)`, then we can prove congruence as needed, i.e. `exteq X1 X2 ∧ P(X1) ⊃ P(X2)` is always provable in the prime proof after unfolding the definitions.

I don't think we can add congruence as a theory axiom: these need to be atomic and first-order as far as I can tell.

**Comment by loewenheim** [comment]
I think we decided that we won't add extensionality as an inference rule for the time being, so I'm closing this.
