### ISSUE TITLE
Get rid of proofs in XML format

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#495]
Looking over the code (and tests), we still use the following XML proofs:

- [x] PrimeTest: Fürstenberg prime proof (in progress by @loewenheim)
- [x] PrimeTest: also includes Euclid's proof, should we convert that as well?
- [x] MiscTest: `sk2.xml`, `sk3.xml`, `sk4.xml`, `test1p.xml`.  These tests can probably be removed without conversion as they are already subsumed by the SkolemizationTest AFAICT.
- [x] TapeTest: should this be the Urban proof or the "normal" proof?  I picked the "normal" one.
- [x] LNPProofTest: I guess this means "least-number principle"?  Is this a variant of the prime proof?

**Comment by quicquid** [comment]
Yes, LNP stands for least number principle. It is the example in the paper "CERES in Higher Order Logic" (Hetzl, Leitsch, Weller).

**Comment by gebner** [comment]
Okay, I looked at the HLK proof and added a quick gaptic port.  The HLK proof makes some interesting design choices:

* It generally cuts on negations, for whatever reason.
* It cuts on `y > 1` even though the succedent has a formula `y > 1 ⊃ ...`.
* Definitions are generally prenex.

So I have left out one cut, simplified the other one.  And since LKsk doesn't have theory axioms (at the moment), I've added them into the end-sequent--this considerable simplifies the tactics script as I could use the `rewrite` tactic.

In any case, even SPASS can't refute the `reduceHolToFol` version of the characteristic clause set now (no idea if it's the right one, I've just picked the `css` from the `LNPProofTest`).

**Comment by gebner** [comment]
Well, after reading the paper it's clear why SPASS can't refute it; apparently the characteristic sequent set is only higher-order refutable here.  But it looks pretty much like the paper now:
```
((z_0:nat) * (z_1:nat): nat) = y_1 :- (z_0:nat) = 1, (z_0:nat) < (y_1:nat)
 :- ((w:nat) * (z_4 * z_1): nat) = w * z_4 * z_1
 :- ((y_1:nat) * (1:nat): nat) = y_1
X(s_0(λx ¬X(x:nat)): nat) :- X(y:nat): o
(1:nat) < (w_0:nat), (s_2(w_0:nat): nat) = w_0, ((w_0:nat) * (z_9:nat): nat) = s_1 :-
 :- (1:nat) < (s_1:nat)
 :- (z_0:nat) = 1, (1:nat) < (z_0:nat)
(1:nat) < (w_0:nat), ((w_0:nat) * (z_9:nat): nat) = s_1 :- ((s_2(w_0:nat): nat) * (s_3(w_0): nat): nat) = w_0
 :- (y_1:nat) = y_1
(1:nat) < (w_0:nat), (s_2(w_0:nat): nat) = 1, ((w_0:nat) * (z_9:nat): nat) = s_1 :-
(z:nat) < (s_0(λx ¬X(x:nat)): nat) :- X(y:nat): o, X(z:nat): o
```

**Comment by quicquid** [comment]
Yes, the paper mentions the instantiation for X - I'll see if I can add this to the test and find a first-order refutation for the rest.

**Comment by quicquid** [comment]
What I'm just wondering right now, why do the terms have type nat? AFAIK the naturals in this example are axiomatized - if we export the type information to e.g. SMT, the prover might assume more arithmetic than we did.

**Comment by gebner** [comment]
Mainly because I was copying the definitions from the HLK file--and there they have type `nat`.

Regarding SMT export, even if we exported the type as `Int` (I don't think SMT-LIB has a type called `nat`), the SMT solver will still only work in the specified logic.  If we tell the SMT solver to work in `QF_UF`, then it will disable all of its arithmetic support, and `Int` is just an interpreted sort.

So when we add support for more interesting background theories to our SMT solver and first-order prover interface, we will have to pass along the information which background theory the problem requires.  We kind of somewhat have something remotely like this in the cut-introduction code: there we work in first-order logic with/without equality, and this is currently handled by having different `Prover` objects for each of the logics.

(More practically, our SMT solver interface does some heavy renaming so that there is no chance any identifier could ever get confused with a keyword, interpreted function symbol, or interpreted sorts like `Int`.  Even if we called the type of naturals `ðf«g«»ðö`, we'd export it as `(declare-sort t1)`.)

**Comment by quicquid** [comment]
Hm, the instantiated sequent set is:

```
∃z (D(z, s3) ∧
    (s_0(λx ¬∃z (D(z, s3) ∧ x < s3 ∧ z > 1)): nat) < s3 ∧
    z > 1)
:-
∃z (D(z, s3) ∧ (y:nat) < s3 ∧ z > 1)
(z:nat) <
  (s_0(λx ¬∃z (D(z, s3) ∧ #c('<': nat>i>o)(x:nat, s3) ∧ z > 1)): nat)
:-
∃z (D(z, s3) ∧ (y:nat) < s3 ∧ z > 1),
∃z (D(z, s3) ∧ #v(z: nat) < s3 ∧ z > 1)
 :- ((w:nat) * (z_4 * z_1): nat) = w * z_4 * z_1
((z_0:nat) * (z_1:nat): nat) = y_1 :- (z_0:nat) = y_1, (z_0:nat) < (y_1:nat)
 :- ((y_1:nat) * (1:nat): nat) = y_1
(1:nat) < (w_0:nat), (s_2(w_0:nat): nat) = w_0, ((w_0:nat) * (z_9:nat): nat) = s_1 :- 
 :- (1:nat) < (s_1:nat)
 :- (z_0:nat) = 1, (1:nat) < (z_0:nat)
(1:nat) < (w_0:nat), ((w_0:nat) * (z_9:nat): nat) = s_1 :- ((s_2(w_0:nat): nat) * (s_3(w_0): nat): nat) = w_0
 :- (y_1:nat) = y_1
(1:nat) < (w_0:nat), (s_2(w_0:nat): nat) = 1, ((w_0:nat) * (z_9:nat): nat) = s_1 :- 
```

I haven't implemented the decomposition rules for lksk and can't create projections to the cnf of this clause set right now. I'll check in what I have so far, the old analysis also didn't do more than produce the CSS.

**Comment by gebner** [comment]
Just FYI, your instantiation formula includes variables of type `i` instead of `nat`.  In particular, the existential quantifier ranges over `z:i` and the constant `s3:i` should probably be `s_3`.

If it makes it easier, we can switch the prime divisor proof to use the default sort `i`; there is only one non-Boolean sort in there anyhow.

**Comment by gebner** [comment]
So this only leaves Euclid's proof in the PrimeProofTest.  Do we have a description of what that proof should be? @shetzl

**Comment by shetzl** [comment]
Well, mathematically it is the following: suppose there are only finitely many primes, say p_1,...,p_k. Let m = p_1 \cdot ... \cdot p_k + 1. Then none of the p_i divides m. However, since every number has a prime divisor, m has a prime divisor q and q is different from all p_i.

Depending on how the proof is used in the PrimeProofTest there may be some subtle issues concerning choices on how to formalise it. If there is an xml file, chances are there is also an hlk-file.

**Comment by gebner** [comment]
So Euclid's proof is done now as well.  I think it has the same problems as the prime proof at the moment, namely the higher-order terms in the clause set.

**Comment by gebner** [comment]
Actually the clause set of the Euclid proof seems to be fine and does not contain any higher-order content.  Nevertheless, the clause set seems to be satsifiable--at least according to SPASS (it's also satisfiable if we eliminate the definitions first).

For the record, this is what executed:
```
import prime.euclid3._
val ccs = CharacteristicClauseSet(extractStruct(skolemize(regularize(AtomicExpansion(proof)))))
SPASS getRobinsonProof ccs
```

**Comment by quicquid** [comment]
Can you try it with CERES.skipEquations ? I'm still not sure if CERES with unary rules is complete. (Are you experimenting with the master branch? Then I can see if I fid something)

**Comment by gebner** [comment]
Yes, I'm trying this on master.  SPASS almost immediately says the clause set is satisfiable, with all of `skipEquations`, `skipPropositional`, and `skipNothing`.

**Comment by gebner** [comment]
Closing this as we no longer have the XML proofs.
