### ISSUE TITLE
Definition elimination in prime proof fails

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#497]
```scala
val prime3 = prime.prime(3)
DefinitionElimination(prime3.ctx.definitions)(prime3.proof)
```
fails with
```
at.logic.gapt.proofs.lk.LKRuleCreationException: Cannot create EqualityRightRule: Neither λm ∃i (i < p_3 ∧ ¬i = 0 ∧ ∃n m = i + n * p_3) nor λx ¬∃n x = 0 + n * p_3 found in formula ∀m (∃i (i < p_3 ∧ ¬i = 0 ∧ ∃n m = i + n * p_3) ⊃
    ∃l_0 ∀n (∃n_0 n = m + n_0 * (l_0 + 1) ⊃
        ∃i (i < p_3 ∧ ¬i = 0 ∧ ∃n_0 n = i + n_0 * p_3))).
  at at.logic.gapt.proofs.lk.ConvenienceConstructor.LKRuleCreationException(lk.scala:1852)
  at at.logic.gapt.proofs.lk.EqualityRightRule$.apply(lk.scala:1602)
  at at.logic.gapt.proofs.lk.DefinitionElimination.apply(DefinitionElimination.scala:101)
...
```

So this happens because we eliminate the definition in a higher-order equality rule.  To simplify a bit before the definition elimination there was a formula `D(x)` and we applied the equation `D=E`.  If we eliminate the definitions and replace `D` by `λx φ` and `E` by `λx ψ` then we can't apply `(λx φ) = (λx ψ)` anymore as the lambda abstractions are beta-normalized away.

I'd propose to fix this by changing the equality rules as follows: instead of a list of positions they would accept a lambda abstraction `C` describing the rewriting context (in this case for example `λX X(x)`).  If the equation is `t=s`, then they would simply require the auxiliary formula to be `C(t)` and insert `C(s)` as the main formula (both beta-normalized).  This would also fix #472.

**Comment by quicquid** [comment]
Do I understand correctly: a first-order proof after definition elimination is a higher-order proof (apart from trivial cases)? I think this would make reasoning about the proofs quite hard - e.g. CERES omega is not defined for higher-order equality rules. What about replacing the equality rule by ```∀x D(x) -> E(x)``` and using that as an axiom?

Regarding the contexts, it looks like a clean solution. I guess it might be a bit harder to infer C automatically though.

**Comment by gebner** [comment]
> a first-order proof after definition elimination is a higher-order proof (apart from trivial cases)?

Well, it's "first-order" as in there are no abstractions in the proof, and all axioms are first-order.  This subset should actually work with first-order CERES.  Hmm, at least as long as the higher-order content doesn't make it into the characteristic clause set.

My intuition is that the higher-order equality rule is not really the problem here--it justs corresponds to a (first-order sound) deep inference rule that allows you replace equivalent formulas deep inside another formula.  What might be problematic however, is that we added an extensionality axiom into the end-sequent, whose higher-order content makes it into the axioms and quite probably the characteristic clause set as well.

> What about replacing the equality rule by ∀x D(x) -> E(x) and using that as an axiom?

If the clause turns out not to be first-order after we eliminate the definitions, then some variation of this is probably the only way out.  This was one of the possibilities we discussed to deal with the following problem:

- The (original) prime proof uses equality rules on second-order equations.
- In addition, second-order equality is also "defined" to be extensional.

(Replace "second-order" by "second sort" or "first-order and we hope for the best" depending on which version of the proof you're looking at.)

One possibility, which is implemented now, is to use standard second-order equality and then add extensionality as an axiom into the end-sequent (and hope the second-order equations don't make it into the clause set).

Other possibilities:
- Add (an) extensionality rule(s) to LK.  This way all axioms would be first order.  But I just looked into your documentation on CERES for the unary equality rules and the second-order equations could still make it into the clause set. :cry: 
- Add a new defined relation for extensional equality, and simulate the application of this "equality" using propositional and quantifier rules.

The last one is probably the only one where we stay clear of any second-order clauses.  I think Stefan argued against it because the propositional simulation of the equality rules would complicate the clause set.

> Regarding the contexts, it looks like a clean solution. I guess it might be a bit harder to infer C automatically though.

For all cases that are currently supported (i.e. specified by a list of positions) it would be easy: just pick a fresh variable, replace the subterms at all specified positions by the new variable, and abstract over it.

In general this is of course higher-order unification, although I don't know if this subproblem is already undecidable.

**Comment by gebner** [comment]
> I think Stefan argued against it because the propositional simulation of the equality rules would complicate the clause set.

I think Stefan has a really good point here, one of the equality inferences applies `'S[2]' = compN(set_1(1))` to `C('S[2]')`.  Rewriting `C X` to `C Y` is quite a bit of work, just look how deep inside the `X` is:
```scala
val prime3 = prime.prime(3)
import prime3._
DefinitionElimination(ctx.definitions)(hof"C X")
```
```
∀m (¬X(m) ⊃ ∃l ∀n (∃n_0 n = m + n_0 * (l + 1) ⊃ ¬X(n)))
```

**Comment by gebner** [comment]
Come to think of it there's yet another option: make the proof in many-sorted first-order logic and add formulas such as `∀x∀y (in(x, set_1 y) <-> x = y` into the end-sequent.

**Comment by loewenheim** [comment]
Yes, the latter would be my preference if the second-order version doesn't work out. But I don't see why it wouldn't, since right now no theory axiom in the proof contains any higher-order reasoning. That should still be the case after definition elimination, no?

**Comment by loewenheim** [comment]
Regarding your suggestion in your first post, let me see if I understand you correctly. Suppose we have an equation `s = t` and the atom `P(s, f(s))`. If I want to replace the second `s` by `t`, I would pass `λx P(s, f(x))` to the equation rule?

**Comment by gebner** [comment]
> Suppose we have an equation s = t and the atom P(s, f(s)). If I want to replace the second s by t, I would pass λx P(s, f(x)) to the equation rule?

Yes, exactly.

**Comment by gebner** [comment]
> no theory axiom in the proof contains any higher-order reasoning

That's right, they only talk about numbers.  However the other initial sequents can still get into the clause set and there's plenty of higher-order content there:
```scala
val prime2 = prime.prime(2)
import prime2._
proof.subProofs collect { case p:InitialSequent => p.conclusion map {_.toSigRelativeString} } foreach println
```
For example:
```
compN(compN(set_1(1))) = set_1(1) :- compN(compN(set_1(1))) = set_1(1)
```

**Comment by loewenheim** [comment]
Yeah, I wasn't sure whether definitions needed to be eliminated from logical axioms, so out of pure laziness I didn't do it.

**Comment by gebner** [comment]
The definition is not the problem there--the problem is what the definition expands to:
```
scala> DefinitionElimination(ctx.definitions)(hof"compN(compN(set_1(1))) = set_1(1)")
res0: at.logic.gapt.expr.HOLFormula = (λx ¬¬x = 1) = (λl l = 1)
```

**Comment by loewenheim** [comment]
Oh dear. That's not good.

**Comment by loewenheim** [comment]
Fixed in efd6fdff75180bbc53b90e43486e5bbbc094f009.

**Comment by gebner** [comment]
And it is broken again:
```
scala> LKToExpansionProof(DefinitionElimination(prime.prime3.ctx.definitions)(prime.prime3.proof))
java.lang.Exception: ERROR: trying to replace variables in a formula without quantifier.
  at at.logic.gapt.expr.hol.instantiate$.apply(utils.scala:366)
  at at.logic.gapt.proofs.expansion.replaceWithContext$.at$logic$gapt$proofs$expansion$replaceWithContext$$instReplCtx(expansionTrees.scala:403)
```

**Comment by gebner** [comment]
Oops, this is not definition elimination failing, but expansion proof extraction.
