### ISSUE TITLE
user manual: gaptics section - error calling example.proof

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#509]
Put the text at the beginning of Section 3.3.2 Gaptic into a file called example.scala and, as suggested there, do the following on the CLI
```
:load example.scala
example.proof
```
This returns
```
<console>:132: error: value proof is not a member of object example
```

Do you mean example.lemma?

**Comment by gebner** [comment]
> Do you mean example.lemma? 

Yes indeed I did.  Thanks for reading carefully and actually trying it out!
