### ISSUE TITLE
implement term indexing

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#51]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 07, 2009 14:34:45_

for efficient comparison and storage of terms. Can be used in all theorem
provers. Should be higher order.
Should maybe follow this paper: http://www.logic.at/intern/library/Pientka.Brigitte/hol_tree_indexing.ps

_Original issue: http://code.google.com/p/gapt/issues/detail?id=51_

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 22, 2010 17:01:57_

as our terms are immutable it can be perfect to implement this and it will also 
contribute to a huge decrease in space.
Should be implemented on the lambda level (var, app and abs) will contain three 
hashmaps, each from a possible constructor to a term (i.e. AppMap will map from 
two lambda expression to an App and VarMap from a symbol and type to a Var). This 
way even circular terms such as ((a,b)(a,b)) will reuse the same instance and it is also 
easy to implement as it is on the lambda terms level only.

We should also consider extending this to the trees which are our other data 
structure (for proofs)

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on January 22, 2010 17:09:23_

I forgot about the traits we are mixing and therefore the approach cannot be implemented on the lambda level 
only.  should be implemented on hol/fol specifically when we need it

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on October 13, 2010 06:23:49_

postponed

**Labels:** -Milestone-Release2.0

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on October 13, 2010 06:23:58_

**Labels:** -Priority-Medium Priority-Low

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 12:07:33_

**Labels:** Type-Feature

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:20:13_

**Labels:** Component-LogicalDataStructures

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on August 22, 2011 04:23:06_

**Owner:** shaoli...@gmail.com  
**Labels:** -Type-Feature Type-Enhancement Performance

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 12, 2011 05:30:10_

**Blocking:** 173

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 06, 2011 07:26:56_

I will close this issue, since efficient storage of terms has not become an issue yet...

**Status:** WontFix

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on October 06, 2011 09:46:33_

In my opinion, issues which we are not going to deal with soon should be
classified ahis low priority. Closing them will mean it will never be done
and the issues contain information which might be useful for future
implementations

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on April 02, 2012 13:53:35_

without term indexing gapt will never be useful in theorem proving..
this paper might also be interesting: http://www.ags.uni-sb.de/~chris/papers/W35.pdf

**Status:** New  
**Owner:** ---

**Comment by gebner** [comment]
This issue seems to concern hash-consing, and not term indexing.  I have no plans to implement hash-consing in GAPT.
