### ISSUE TITLE
document recursive data types and many-sorted logic in user manual

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#512]
Since we mention it in the release notes and it will become more important with the development of the inductive theorem prover, I would suggest to document the recursive data types and many-sorted logic in the user manual. This would fit together well with an explanation of the many-sorted to single-sorted FOL reduction as well as maybe reduceHolToFol.

**Comment by gebner** [comment]
I have added a section about the many-sorted to single-sorted reduction that also covers a bit of many-sorted logic.  However I don't think there is any feature involving inductive data types that you can easily use from the CLI, did you have something in mind?

**Comment by shetzl** [comment]
I like the seciton on many-sorted logic. Concerning recursive data types, I was thinking about an induction rule for a recursive data type. Could we include, e.g., the construction of a simple proof that does induction on lists?
