### ISSUE TITLE
Expansion tree deskolemization

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#516]
It would be nice to be able to take an expansion proof with skolem quantifiers and convert it to one with eigenvariables.  In particular, this would enable automatic generation of LK proofs with strong quantifiers using Prover9/etc.
- [ ] Elimination of congruence axioms `!x!y (x=y -> s_i(x)=s_i(y))`
- [x] Elimination of duplicate Skolem terms (i.e. different quantifiers nodes with the same Skolem term)
- [x] Replace Skolem terms by eigenvariables

**Comment by shetzl** [comment]
It would also allow the ceres-method to be applied to a single cut at a time.

This issue would make a good student project. It is useful but not urgent and it can be started without having to acquire too much background knowledge beforehand.

**Comment by quicquid** [comment]
If I remember correctly, an alternative would be to use LKsk - I think a master student was investigating the use of CERES omega in a first order context at the beginning of last year.

**Comment by gebner** [comment]
Here is some of the relevant literature:

 - The equality-free case with proof theoretic Skolemization is discussed in [On the complexity of proof deskolemization](http://dmg.tuwien.ac.at/hetzl/research/deskol.pdf)
 - There is a Bachelor thesis describing an implementation of the approach: [A concrete deskolemization algorithm](http://www.cs.ru.nl/bachelorscripties/2014/Ramon_van_Sparrentak___0757276___A_concrete_deskolemization_algorithm.pdf)
 - For elimination of congruence axioms, see: Skolemization and Equality (ask @shetzl for an early draft)

**Comment by gebner** [comment]
To elaborate a bit on the issue of non-proof-theoretic Skolemization: for first-order provers, you generally want to generate as few different Skolem function symbols that are as simple as possible.

So for example, given the formula: `∃x ((P(x) ⊃ ∀y P(y)) ∧ (Q(x) ⊃ ∀y P(y)))`
You want the Skolemization: `∃x ((P(x) ⊃ P(s)) ∧ (Q(x) ⊃ P(s)))`

From a proof complexity point of view, this kind of Skolemization allows for at least exponentially smaller (cut-free) proofs than the "standard" proof-theoretic Skolemization.  By standard proof-theoretic Skolemization I mean the one where you assign a different Skolem symbol for each strong quantifier in the end-sequent, and (crucially) the arguments to the Skolem functions are given by the weak quantifiers that enclose the strong one.

Not only does this version allow for shorter proofs, it is also considerably easier to implement since you do not need keep track of the current position or the enclosing weak quantifiers.  So we use it as the default Skolemization for the external prover interfaces.  Aside from that, if we ever want to import clausifications from external provers (as in #552), we will have these kinds of Skolem functions anyway.

The simple deskolemization algorithm only works for the standard proof-theoretic Skolemization.  Therefore the easiest way to deskolemize here is probably to convert this Skolemization to the standard one.

**Comment by gebner** [comment]
This deskolemization procedure is also described in Dale Miller's PhD thesis: [Proofs in Higher-Order Logic](http://repository.upenn.edu/cgi/viewcontent.cgi?article=1683&context=cis_reports)

**Comment by gebner** [comment]
> So for example, given the formula: `∃x (P(x) ⊃ ∀y P(y))`
> You want the Skolemization: `∃x (P(x) ⊃ P(s))`

Regarding this kind of Skolemization: you can actually deskolemize this easily in linear time by introducing a cut on the formula with the strong quantifier, i.e. on `∀y P(y)` in this case.  In LK, this corresponds to transforming this proof:
```
    --------------- ax
      P(s) :- P(s)
   ------------------  ∀sk:r
     P(s) :- ∀y P(y)
   ------------------ ⊃:r
   :- P(s) ⊃ ∀y P(y)
------------------------  ∃:r
:- ∃x (P(x) ⊃ ∀y P(y))
```
Into the following one:
```
    --------------- ax
      P(s) :- P(s)
   ------------------  ∀sk:r       -------------------- ax
     P(s) :- ∀y P(y)                ∀y P(y) :- ∀y P(y)
   --------------------------------------------------- cut
     P(s) :- ∀y P(y)
   ------------------ ⊃:r
   :- P(s) ⊃ ∀y P(y)
------------------------  ∃:r
:- ∃x (P(x) ⊃ ∀y P(y))
```
Deskolemization would then yield a proof with cut, but that can be easily eliminated.  The only difficulty here is that we introduce a non-atomic axiom, this can be handled in the expansion proof by introducing a definition using `ETDefinedAtom`.

**Comment by gebner** [comment]
This issue is already "two thirds done", thanks to the work by @mschlaipfer.  The only missing part is the equality part now, that is eliminating the congruence axioms for the Skolem functions.
