### ISSUE TITLE
string interpolation and lambda expression parser behaves unexpected

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#522]
Please consider the following gapt commands:

```
gapt> val x = rename(hov"x:i", Set())
x: at.logic.gapt.expr.Var = x

gapt> le"\ $x $x"
res20: at.logic.gapt.expr.LambdaExpression = λ__qq_0 x
```

I would expect:

```
res18: at.logic.gapt.expr.LambdaExpression = λx x
```

Am I doing something wrong?

**Comment by gebner** [comment]
Ah, we didn't think about that!  However, `le"\x $x" should work (no matter what type `x` has).

Greetings from Nagoya!

**Comment by quicquid** [comment]
Oh greetings to Japan! Your solution is fine as long as I know the variable name - I put the rename into the example to suggest that, but perhaps:

```
gapt> val x = rename(hov"x:i", Set(Var("x", Ti)))
x: at.logic.gapt.expr.Var = x_0
```

would have been better. Now if i again write

```
gapt> le"\ x $x"
res1: at.logic.gapt.expr.LambdaExpression = λx x_0
```

then I have bound the wrong variable. My workaround so far is ```Abs(x, le"$x")``` (the actual term i'm creating is a label "\u s=u -> Fs -> Fu" where I make sure that u is not free in s nor F). This pattern might occur in other parts of the code and lead to unexpected results though.

**Comment by quicquid** [comment]
Merci!
