### ISSUE TITLE
Collapsing subproofs in Prooftool

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#533]
How should collapsing subproofs in Prooftool actually work? The way I see it, there are several options. Consider a binary proof:
```
   A :- A       B :- B
----------------------∧:r
        A,B :- A∧B
```

Should it be possible to collapse the subproofs individually, giving
```
   (π₁)       B :- B                       A :- A      (π₂)
----------------------∧:r       or      ----------------------∧:r ?
        A,B :- A∧B                            A,B :- A∧B
```
Or should everything above the line be collapsed at once, giving
```
      (π)
------------∧:r ?
  A,B :- A∧B
```

Also, what should the user interface be? In the second case, I think it might be nice to be able to collapse a proof by clicking on its rule label. In the first case, that's obviously not possible.

**Comment by gebner** [comment]
At first, I would have expected collapsing to produce the following result: when you click hide in the popup menu of the lower sequent the proof above is collapsed to a label:
```
:- A    :- B
------------- ∧:r
  :- A ∧ B
```
collapses to
```
   (π)
:- A ∧ B
```
This is at least the style that I would use in a paper.

> I think it might be nice to be able to collapse a proof by clicking on its rule label.

This seems a bit difficult to discover.  It already took me some time to discover the popup menu (and that's a fairly common paradigm).  If anything, I would expect that clicking on the sequent collapses the proof, but I don't think I would ever try to click on the rule label.

Another thing to consider is that single-click is a fairly valuable input method: it can be done with just one hand.  IMHO we should make sure that we use it for something important.  Having said that, wiith the large proofs that we usually have, I can easily see collapsing to be the killer feature that makes prooftool great again.

**Comment by loewenheim** [comment]
> I can easily see collapsing to be the killer feature that makes prooftool great again.
Are you channelling the Donald? Don't do that to your brain, man.

Seriously though: Your suggestion raises the question of what the label "(π)" actually stands for. After all, what has been hidden is not a single proof.

**Comment by quicquid** [comment]
The way I use the notation does not have a line (since there's not necessary an inference), meaning that pi is a proof ending in the end-sequent Gamma :- Delta. 

          (pi)
     Gamma :- Delta

To define such a proof, I use the inverse notation:

       A :- A
    ------------ &:l
    A & B :- A
        (pi)

llk.sty uses the macros CONTINUEFROM and CONTINUEWITH, if you're interested in the Tex source.

**Comment by loewenheim** [comment]
What do you write if your proof has two immediate subproofs? Something like
```
(π₁)   (π₂)
   Γ :- Δ,
```
or would you only use one label?

**Comment by quicquid** [comment]
Either

          (pi)
      Gamma :- Delta

or


          (pi1)                      (pi2)
     Gamma1 :- Delta1          Gamma2 :- Delta2
    ------------------------------------------------- inf
                   Gamma :- Delta

depending on if the inference is relevant or not.

**Comment by loewenheim** [comment]
Commit https://github.com/gapt/gapt/commit/e5b598d5cc25ba6c41de758f1bba8f5b91df3413 contains a mechanism for collapsing subproofs that I think is very similar to the variant that the two of you proposed. Points of note:

- For some reason, the `(...)` label is not centered above the sequent.
- The context menu behaves pretty weirdly. If you switch on the debug borders, you will see that you can bring up the context menu from anywhere within a `DrawSequentProof` object, even though the only part with that reaction should be the end sequent panel.
- The context menu displaying both "Show proof above" and "Hide proof above" regardless of whether the proof is collapsed or expanded is clearly not optimal.

**Comment by gebner** [comment]
Re: right-click does not work on the sequent

See this [stackoverflow answer](http://stackoverflow.com/a/3090034).  We have a mouse event listener on LatexLabel, therefore we do not receive mouse events in DrawSequentProof.

**Comment by loewenheim** [comment]
Are you talking about the fact that to bring up the menu, you have to right-click in a blank part of the end sequent? Because, while also annoying, that's not what I'm talking about. What I mean is that you can in fact click near the end-sequent of one proof, but the click registers in a proof much further down.

**Comment by gebner** [comment]
Yeah, that's weird as well.  Interestingly enough, it not only works if you click left or right of the sequent, but anywhere within the DrawSequentProof that is *not* inside the SubproofsPanel area.

**Comment by loewenheim** [comment]
Yeah, that's what I mean. How is that possible?

**Comment by gebner** [comment]
I think I figured it out:
```scala
    val ds = DrawSequent(...)
    ds.listenTo( mouse.moves, mouse.clicks, mouse.wheel, main.publisher )
    ds.reactions += {
      case e: MouseClicked if e.peer.getButton == MouseEvent.BUTTON3 =>
        PopupMenu( DrawSequentProof.this, e.point.x, e.point.y )
    }
```
What mouse events is ds listening to?  (Hint: from which object do we get the `mouse` property?)

**Comment by loewenheim** [comment]
I don't follow. Isn't `mouse` just Swing's builtin mouse object?

**Comment by gebner** [comment]
Well, first of all this is scala-swing and not Swing.  But more to the point, this is how `mouse` is defined in `Component.scala`:
```
abstract class Component extends UIElement {
  // ...
  object mouse {
    val clicks: Publisher = // ...
    // ...
  }
}
```
Yes, each scala-swing Component has its own `mouse.clicks` object, which provides a stream of mouse events for that component.  In our case `ds.mouse` would provide the mouse events for the DrawSequent component; `mouse` belongs to `DrawSequentProof`.

**Comment by loewenheim** [comment]
Got it. So what we want is  `ds.listenTo( ds.mouse.moves, ds.mouse.clicks, ds.mouse.wheel, main.publisher )`, right?

**Comment by loewenheim** [comment]
I just noticed that hiding subproofs does currently not play well with hiding structural rules, as both of these procedures involve hiding an inference's line. This means that it might be necessary to keep track of *why* a line was hidden.

**Comment by shetzl** [comment]
What is the plan for this feature w.r.t. the 2.2 release? As it is in master now it is not ideal:
- if a subproof is hidden there is no indication that this is not just an axiom
- if there is no subproof to unhide then "show subproof" should be greyed out
- the context menu appears to have duplicate separator lines

**Comment by loewenheim** [comment]
In my opinion, we should merge it. The status quo in the master branch is pretty bad, as you said.

**Comment by gebner** [comment]
Merging is fine with me.  There's one regression though at the moment: the rule labels are not rendered with anti-aliasing enabled, can you add that?

**Comment by gebner** [comment]
@loewenheim Is this ready for merging?

**Comment by gebner** [comment]
Ok, there's a pretty big bug:
```
scala> prooftool(LinearExampleProof(2))
java.lang.NullPointerException
  at scala.swing.RootPanel$class.contents_$eq(RootPanel.scala:36)
  at scala.swing.Window.contents_$eq(Window.scala:42)
  at at.logic.gapt.prooftool.ProofToolViewer.<init>(ProofToolViewer.scala:120)
  at at.logic.gapt.prooftool.ScrollableProofToolViewer.<init>(ProofToolViewer.scala:359)
  at at.logic.gapt.prooftool.DagProofViewer.<init>(SequentProofViewer.scala:23)
  at at.logic.gapt.prooftool.SequentProofViewer.<init>(SequentProofViewer.scala:36)
  at at.logic.gapt.prooftool.LKProofViewer.<init>(SequentProofViewer.scala:94)
  at at.logic.gapt.prooftool.prooftool$.apply(ProofToolViewer.scala:39)
  ... 42 elided
```
