### ISSUE TITLE
ExpansionProofToLK returns ugly proofs with equational inferences

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#534]
Try out this snippet:
```scala
prooftool(ExpansionProofToLK(Escargot getExpansionProof
  hof"a=b & !x f x = g x -> f b = g a" get))
```
and behold the following beautiful proof:
![uglyproof](https://cloud.githubusercontent.com/assets/313929/16186873/5c6004e4-36cd-11e6-83af-1bf39b7082e1.png)

This proof consists of the lower (unary) part which introduces the instances, and then an upper equational part which is derived from a proof using paramodulation rules.  The whole upper part could be replaced by one unary equation rule (plus a weakening and an axiom)...

It would be nice if could generate smaller proofs automatically:
 1. One way would be to post-process LK proofs: the ugly proof contains lots of cuts on axioms, and cuts on sequents of the form `t=s :- s=t`.  We could get rid of them using a new procedure similar to `cleanStructuralRules`.
 2. We could also improve the resolution->LK conversion.  If we add a Flip rule to the resolution calculus, then I think we could guarantee unary-rules-only proofs for atomic sequents in LK.
 3. A third option would be to write an equational prover for atomic sequents in LK from scratch.  No idea whether this can be done in a way that is less effort than writing a superposition prover plus conversion.

My original preference was 2., but 1. might also be useful for manually constructed proofs.

**Comment by loewenheim** [comment]
In 1., by "get rid of them using a new procedure," do you mean throwing away the left-hand side of the cut and simply using an equation rule on the right-hand side?

**Comment by gebner** [comment]
For cuts with an axiom we can throw away the side with the axiom, and don't even need to add any other rule.

The situation is a bit more difficult for cuts with subproofs ending in `s=t :- t=s`.  There we can throw the subproof away as well in some cases, we just need to keep track of flags that indicate whether an equation in the current sequent is flipped or not--and actually flip it if it occurs in an inference other than an equational rule.

**Comment by gebner** [comment]
I tried out option 2.  Looks better:

![nicer-exp2lk](https://cloud.githubusercontent.com/assets/313929/16260070/e9dda0bc-3865-11e6-9b5e-42f2216a9204.png)

**Comment by loewenheim** [comment]
You're right, that looks good. Fixing this at the conversion point is also arguably the cleaner solution.

**Comment by gebner** [comment]
I think it's the only way we can guarantee to have such nice proofs (i.e. without unexpected cuts).  Just eliminating the cuts on axioms does not achieve that.  For that I think we would need to have (reductive) cut-elimination for equations as well.

On the other hand, it certainly doesn't hurt to have something stronger than `cleanStructuralRules` to clean up LK proofs.
