### ISSUE TITLE
[Prooftool] The search function

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#537]
Is the search function for sequent proofs just dead code right now? Should it be? I'm considering removing it before merging the prooftool-wip branch into master.

**Comment by gebner** [comment]
I think it really is dead at the moment.  I'd remove it, then we can get rid of cruft like this:
```scala
  def searchNotInLKProof() {
    tx = tx1
    initialize()
  }
```

I don't know how useful a search functionality would be, in any case.  Searching for strings is probably completely hopeless, as 1) most strings occur very often in a proof, and 2) searching mathematical formulas is a research problem of its own.

**Comment by loewenheim** [comment]
Exactly. The `DrawSequentProof` class could be made a fair bit simpler without this functionality (such as it is).
