### ISSUE TITLE
prooftool: reduce space between inferences

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#543]
It looks like the space between a sequent and the inference lines has increased.  That is, proofs take up more vertical space now.  Should we reduce it again?

**Comment by loewenheim** [comment]
I think this has been fixed as a side effect of not manually calculating the sizes of sequents anymore. Does it look better to you now?

**Comment by gebner** [comment]
Yeah, it's much better now.  I believe there is still a slight asymmetry though: sometimes there is more space between the sequent and the *lower* line than to the upper line.  But that's not really critical and fine with me.
