### ISSUE TITLE
CERES: unary equation rules

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#555]
As part of the regression tests, we run CERES on proofs generated by cut-introduction.  As of last week, I switched the cut-introduction code to generate actual unary equation rules (instead of simulated paramodulations).  Now we have more than 200+ new failures when running CERES.

Here is the short example illustrating the general problem:
```scala
val Some(proof) = Escargot.getLKProof(
  formulaToSequent pos hof"f 0 = t & !x (f (s x) = f x) -> f ${Numeral(9)} = t")
val Some(proofWithCut) = CutIntroduction.compressLKProof(proof)
```
CERES then fails:
```
scala> CERES(proofWithCut)
java.lang.Exception: The characteristic clause set could not be refuted:
fof(seq_0, axiom, ![X1]: f(X1) = f(X1)).
fof(seq_1, axiom, f(s(s(s('0')))) = f('0')).
fof(seq_2, axiom, ![X1]: f(s(s(s(X1)))) = f(s(s(X1)))).
fof(seq_3, axiom, ![X1]: f(s(s(X1))) = f(X1)).
fof(seq_4, axiom, f(s(s(s(s(s(s(s(s(s('0')))))))))) != t).
```

Here is a rendering of the offending proof with cut:
![proofwithcut](https://cloud.githubusercontent.com/assets/313929/17092101/607f869c-5240-11e6-8479-19704d69f560.png)

**Comment by quicquid** [comment]
Thanks i'll have a look in the afternoon :-)

**Comment by quicquid** [comment]
I found the bug in CERES (which interestingly was not present in CERES omega) responsible for this failure. Can you run the regression tests and check how many failures we have now?

**Comment by gebner** [comment]
Wow, that was fast.  And now the Euclid proof works again as well. :+1: 

Unfortunately I can only run the regression tests on the weekend, since our Jenkins is on a shared VM and Tobias doesn't let me use all 8 cores during the work week...  So we'll have to wait until next week for the results.

**Comment by quicquid** [comment]
I'm on vacation and had some time off :-) Let's see how it is after the weekend, i hope it's better but hard to tell how many we really managed.

**Comment by gebner** [comment]
Good job!  We are now down to just 7 errors in CERES, all of which seem unrelated: http://compile.logic.tuwien.ac.at/job/gapt%20extended%20testing/125/testReport/Prover9TestCase/CERES%20(cut-intro)/  :+1: :tada:
