### ISSUE TITLE
Superscripted formulas in expansion proof viewer

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#558]
This is the expansion proof of `Pi3Pigeonhole.proof`:
![2016-07-29-134438_1920x1080_scrot](https://cloud.githubusercontent.com/assets/313929/17247327/c4c433b4-5592-11e6-9b88-de87d8048fb6.png)

**Comment by gebner** [comment]
@loewenheim I have no idea what change caused this, but it was fine before the merge of DrawSequent restructuring.

**Comment by loewenheim** [comment]
Fixed in https://github.com/gapt/gapt/commit/13db7caba812246d9d64e375f7038f6c9af61412. At some point, I changed a 0.5 to a 0 as an experiment and forgot to change it back.
