### ISSUE TITLE
eliminateTheoryAxioms produces duplicate formulas

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#564]
```
scala> eliminateTheoryAxioms(tape.p, univclosure(And(tape.ctx.axioms.map(_.toDisjunction))))
res0: at.logic.gapt.proofs.lk.LKProof =
[p234] A,
∀x ∀y ∀z (x + y = y + x ∧
    x + y + z = x + (y + z) ∧
    0 + x = x ∧
    ¬x + y + 1 = x),
∀x ∀y ∀z (x + y = y + x ∧
    x + y + z = x + (y + z) ∧
    0 + x = x ∧
    ¬x + y + 1 = x),
∀x ∀y ∀z (x + y = y + x ∧
    x + y + z = x + (y + z) ∧
    0 + x = x ∧
    ¬x + y + 1 = x),
```
In total, there are 27 copies of the theory axiom here.  Maybe we can add a general solution to this problem to `LKVisitor`?  Other functions such as `makeInductionExplicit` also have this problem.

**Comment by loewenheim** [comment]
What do you think of my change in https://github.com/gapt/gapt/commit/86cf661a703b2a913d64c87bf7e92ddb62a6d345? Is that sufficient?

**Comment by gebner** [comment]
It definitely solves the problem with `eliminateTheoryAxioms`.  However the only way to reuse this approach in other visitors is to copy and paste the code.  The `contractAfter` code itself is neat, maybe we can put it in LKVisitor (and make it generic in the visitor's type parameter)?

Then I think it would even suffice to only override a single method in order to enable the contractions, namely `recurse` itself:
```scala
override def recurse(p: LKProof, arg: HOLFormula): (LKProof, OccConnector[HOLFormula]) =
  contractAfter(super.recurse)(proof, arg)
```

**Comment by loewenheim** [comment]
The problem with a straightforward generalization is that the `ContractionLeftMacroRule` used in `contractAfter` requires a formula argument. We could of course replace it with the `ContractionMacroRule` constructor that simply contracts everything.

I suppose that would be the smart solution anyways, since there is no reason we should always want to contract only on the left side in general.

**Comment by gebner** [comment]
Ah I see.  In general I do not think we can contract everything, as we can then no longer recreate the contraction rules from the input proof.  However, I think we can and should contract all formulas that do not have parents in the OccConnector.  These orphans should be precisely the formulas that are newly introduced by the visitor, and we also don't need to apply inferences from the input proof to them so we can safely contract them.

**Comment by loewenheim** [comment]
Does that mean that contracting after every step should become the default behavior for the visitor?

**Comment by gebner** [comment]
No, I don't think it makes sense for most visitors (replacement, regularization, etc.).  It's also easier to enable contractions if you want them--you just need to override a single method--compared to disabling them if you don't.

**Comment by loewenheim** [comment]
Yeah, that makes sense.
