### ISSUE TITLE
Prooftool: Zooming sometimes overwrites formula parts with white boxes

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#570]
This can be seen in in both double negated Ps in the image (the proof is ```prooftool(simple.fol2.proof)```):

![pt-resize](https://cloud.githubusercontent.com/assets/436903/18832807/b94c7ca6-83ed-11e6-912e-c2dbfa7f1911.png)

**Comment by gebner** [comment]
This is probably due to [this line in DrawSequent](https://github.com/gapt/gapt/blob/2ca81fb8a6b8e2b656dd627b734bec7dc6cb18e0/core/src/main/scala/at/logic/gapt/prooftool/DrawSequent.scala#L63).

**Comment by quicquid** [comment]
I just realized that the sequent lines are not at the same hight (updated the picture). Is it possible that the axiom rule just needs these 30 pixels offset on top?

**Comment by gebner** [comment]
Interestingly enough, on my machine only the left `¬¬P` is cut off, here a few inference labels are cut off instead...

**Comment by gebner** [comment]
Once #568 is solved, we can just remove [this line here](https://github.com/gapt/gapt/blob/2ca81fb8a6b8e2b656dd627b734bec7dc6cb18e0/core/src/main/scala/at/logic/gapt/prooftool/DrawSequent.scala#L66) and the formulas will no longer be cut off.  The line is only there so that the sequents are not stretched vertically in small proofs.

**Comment by loewenheim** [comment]
I'm afraid it's not that simple. I tried removing the line and it only causes Swing to make the end sequent panels as big as possible. This stuff is driving me _nuts_.

**Comment by quicquid** [comment]
I completely agree - I was already wondering if it wouldn't be easier to calculate absolute positions in a Graph2D window and draw the sequents without the help of Swing. I might be imagining it easier than it is though...

**Comment by loewenheim** [comment]
Fixed in 47e1f881222b7642e6f8d8db42c58aaad221adc5.
