### ISSUE TITLE
Prooftool: Sequent lines are sometimes too long

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#571]
With big proofs like  ```prooftool(nTape3.input_proof)``` sequent lines become way too long and even write into different parts of the proof:

![pt-long1](https://cloud.githubusercontent.com/assets/436903/18791803/6e45f858-81b4-11e6-8196-9d231f702fd5.png)

Scrolling much further to the right, we can see the end of the lines:

![pt-long2](https://cloud.githubusercontent.com/assets/436903/18791861/a3ed7b66-81b4-11e6-9107-fa53021b17cb.png)

**Comment by loewenheim** [comment]
Fixed in 47e1f881222b7642e6f8d8db42c58aaad221adc5.
