### ISSUE TITLE
marking ancestors / descendants in prooftool

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#576]
For tracing the history of a formula through an LK-proof in prooftool, the following feature would be helpful: on right-click on a formula a context-menu opens with the items "mark ancestors", "mark descendants", "mark ancestors and descendants". The marking could look just as it does for cut-formulas. There would also need to be a way to remove the marks, e.g. an item "remove formula marks" in the View-menu.

**Comment by mrukhaia** [comment]
This functionality was already implemented. It was called something like
"mark Omega ancestors" and was working with schemata code. Probably it was
removed together with the schema code.

Best regards
Mikheil Rukhaia

**Comment by loewenheim** [comment]
I've implemented a version of this in f2fe4ddb925f36c417fcf978939fea6a0a431a8d. Is this about what you had in mind?

**Comment by shetzl** [comment]
Yes, that's exactly what I had in mind.
