### ISSUE TITLE
regression tests fail

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#578]
Last weekend's regression tests (build number 138) have failed with the message:
```
Failed to read test report file /var/lib/jenkins/workspace/gapt extended testing/target/regression-test-results.xml
org.dom4j.DocumentException: Error on line 1244 of document file:///var/lib/jenkins/workspace/gapt%20extended%20testing/target/regression-test-results.xml : XML document structures must start and end within the same entity. Nested exception: XML document structures must start and end within the same entity.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:126)
...
```
See http://compile.logic.tuwien.ac.at/ for details.

**Comment by gebner** [comment]
No idea what happened there, the process just stopped after 20 test cases.  We also don't have any (system) logs anymore as it's too long ago.  Might have been an out-of-memory/out-of-disk issue.  Let's see whether it works this week.

**Comment by gebner** [comment]
Yes, OOM it is.  I restarted the compile server two weeks ago in order to patch the dirty cow kernel vulnerability.  But we have so little memory on the VM and the tiny hard disk is so horribly partitioned that I had to enable a swap file, and I forgot to reenable when rebooting this time.  So keep your fingers crossed for next week!

We should really do something about the compile server.  It's stuck on an ancient ubuntu version; due to the limited disk space it's impractical to upgrade it in place.  Then there is tons of stuff in home directories from various (former) logic.at people, but I can't just go and delete that.
```
Nov  5 00:42:30 compile kernel: [1135644.959617] java invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
Nov  5 00:42:30 compile kernel: [1135644.959627] java cpuset=/ mems_allowed=0
Nov  5 00:42:30 compile kernel: [1135644.960027] CPU: 0 PID: 2891 Comm: java Not tainted 3.13.0-100-generic #147-Ubuntu
Nov  5 00:42:30 compile kernel: [1135644.960027] Hardware name: Bochs Bochs, BIOS Bochs 01/01/2007
Nov  5 00:42:30 compile kernel: [1135644.960027]  0000000000000000 ffff88018eebb958 ffffffff8172a4bb ffff880149ae8000
Nov  5 00:42:30 compile kernel: [1135644.960027]  0000000000000000 ffff88018eebb9e0 ffffffff81724a5a 0000000000000000
Nov  5 00:42:30 compile kernel: [1135644.960027]  0000000000000001 0000000000000001 ffffffff81c3f920 000000000b2e0b2e
Nov  5 00:42:30 compile kernel: [1135644.960027] Call Trace:
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff8172a4bb>] dump_stack+0x64/0x82
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff81724a5a>] dump_header+0x7f/0x1f1
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff81155d11>] oom_kill_process+0x201/0x360
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff812dcab5>] ? security_capable_noaudit+0x15/0x20
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff811564a1>] out_of_memory+0x471/0x4b0
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff8115c7bc>] __alloc_pages_nodemask+0xa6c/0xb90
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff8119ae83>] alloc_pages_current+0xa3/0x160
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff811527c7>] __page_cache_alloc+0x97/0xc0
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff81154235>] filemap_fault+0x185/0x410
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff8117944f>] __do_fault+0x6f/0x530
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff8117d2a2>] handle_mm_fault+0x482/0xf00
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff8115acba>] ? __free_pages+0x5a/0x60
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff81736644>] __do_page_fault+0x184/0x560
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff810a2ba5>] ? set_next_entity+0x95/0xb0
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff810135db>] ? __switch_to+0x16b/0x4f0
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff81736a3a>] do_page_fault+0x1a/0x70
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff817360c9>] do_async_page_fault+0x29/0xe0
Nov  5 00:42:30 compile kernel: [1135644.960027]  [<ffffffff81732d98>] async_page_fault+0x28/0x30
```

**Comment by quicquid** [comment]
I just freed 1GB from my home directory and wrote Artem, whose experiments (related to algebra) created about 7GB of data. If he has a backup of his data, we should have anough space to upgrade.

**Comment by quicquid** [comment]
It seems that jenkins was using 5GB for its logs about completed jobs (/var/lib/jenkins/jobs). In agreement with Artem I deleted 6.8GB from his home and used the space to move the jobs (5GB) directory onto the home partition. We should have sufficient space for a system upgrade. I had a look into the jobs and apparently, the xml file with the junit results is ~ 50MB. The history of 100 build results amounts then to the 5GB. We might want to archive the history in a different place (and bzip the xml files, that should reduce their size dramatically).

**Comment by shetzl** [comment]
Do we need the history of the builds? The point of the regression tests is to alert us if a bug has been introduced. To that aim, keeping the history back to the last (essentially) bug-free build (which in our case is no. 137) should be enough...

**Comment by quicquid** [comment]
It might be interesting for some statistics, but I don't believe we need more than the last 20 builds and the last working one. If one assumes the extended testing happens once a week, this amounts to half a year of history, which should be fine. I think I've lost my jenkins password at some point, but there should be an option in the project settings.

**Comment by gebner** [comment]
Wow, awesome response time!

> I just freed 1GB from my home directory and wrote Artem, whose experiments (related to algebra) created about 7GB of data.

Excellent!  Now home is pretty small:
```
[gebner@compile:~] $ df -h /home
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/VG_compile-Home  7.8G  5.1G  2.3G  69% /home
```

> I just realized that the root file-system is distinct from the homes.

Yeah, it was even on different volume groups, for god's sake...  Now while home still has its own file system, at least there is just one volume group, and we can easily shuffle around space if needed:
```
[gebner@compile:~] $ sudo vgs
  VG         #PV #LV #SN Attr   VSize  VFree 
  VG_compile   3   3   0 wz--n- 49.51g 16.93g
```

> I'm surprised the operating system uses 16GB.

Did somebody clean up already?  It only uses 11G now:
```
[gebner@compile:~] $ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/dm-1        19G   11G  7.3G  59% /
```

> The history of 100 build results amounts then to the 5GB. We might want to archive the history in a different place (and bzip the xml files, that should reduce their size dramatically).

I had already archived some of them to `/home/jenkins`, but didn't compress them.  Compression freed up another few GiB, super!

> Do we need the history of the builds?

Probably not.  I don't think anyone has ever looked at old results.  I just didn't want to delete them as we might at some point maybe want to look at them for nostalgia's sake.

**Comment by gebner** [comment]
> I think I've lost my jenkins password at some point, but there should be an option in the project settings.

Don't worry!  You can always get it back:
```shell
tail -n1 /etc/default/jenkins
```

**Comment by gebner** [comment]
So the compile server now runs Ubuntu 16.04, and the swap partition is now 6x as large.

**Comment by quicquid** [comment]
Thanks a lot for the update!

**Comment by gebner** [comment]
Everything is back to normal now.
