### ISSUE TITLE
aip.sh should be incorporated into viper.sh

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#597]
We should offer only one induction prover as part of gapt. I would suggest to remove aip.sh and allow access to the functionality of AnalyticInductionProver from viper.sh. For the time being, i.e., the 2.4 release, a simple way to achieve this may be to make a call to `./viper.sh analytic <args>` send `<args>` to `at.logic.gapt.provers.viper.aip`.

@gebner @jannikvierling: please coordinate on this issue.

P.S.: the current release tarball contains only the scripts gapt.sh, escargot.sh, and viper.sh.

**Comment by jannikvierling** [comment]
@gebner: if you are ok with the changes proposed by Stefan, then I will
take care of doing the necessary modifications as soon as possible.

**Comment by gebner** [comment]
@jannikvierling I'd rather name the flag `--analytic`, but if you implement it you can choose whatever you like best.  We can discuss post-2.4 changes next Wednesday.  Thanks for taking care of this issue.

**Comment by gebner** [comment]
@jannikvierling Can this issue be closed now?

**Comment by jannikvierling** [comment]
@gebner Yes.
