### ISSUE TITLE
Extracting expansion trees from proofs with definition

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#598]
Currently, we can't extract expansion trees from LK proofs with definition rules. One might think that this should be easy to fix, since there are definition nodes in expansion trees, but those actually don't correspond very well to the LK definition rules: the LK rules let you replace any subexpression of a formula with a new constant symbol, whereas the ET nodes only support the introduction of a new atom for a formula.

I suggested generalizing the ET nodes to mirror the LK rules, but @shetzl made the reasonable point that this would make the order in which formulas are expanded ambiguous.

Suggestions?

**Comment by quicquid** [comment]
That's not a practical contribution, but perhaps you could think of ETs modulo rewriting, analogous to deduction modulo? Reproving the deep formula would need a corresponding prover like Zenon modulo (the last time i tried, iProver modulo didn't compile anymore), but that might be a nice student project.

**Comment by loewenheim** [comment]
The method I implemented in 7b57d160107fd85f69c93d154b763ce0a5c30d4c is actually incorrect—it fails in some simple, pathological cases where definitions are applied to terms of type `o`. I'll see about doing it properly.

**Comment by gebner** [comment]
> I suggested generalizing the ET nodes to mirror the LK rules, [...]
> [...] ETs modulo rewriting [...]

This is pretty much what we have now.  There is an `ETDefinition` node that allows you to change the shallow formula to any other shallow formula, as long as they definitionally reduce to the same normal form (this is not checked at construction time).

> Reproving the deep formula

The deep formula is still a quasi-tautology, at least if the extraction works correctly (it can fail with higher-order rewriting, or with rewriting below definition rules in general).
