### ISSUE TITLE
support for VeriT stable2016

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#603]
The veriT interface does apparently not work together with the stable2016 version of VeriT. Try, e.g., the following on the CLI:
```
val F = fof"a = b -> f(a)=f(b)"
VeriT isValid F
```
This results in an `IOException`. For another example, try
```
val F = fof"- a = b | f(a)=f(b)"
VeriT isValid F
```
which fails with a `VeriTParserException`.

**Comment by shetzl** [comment]
The commit b8e603214f6a8dbd4a7652935b218797cbaead1f fixes the second of the above examples but not the first. The problem with `fof"a=b -> f(a)=f(b)"` seems to be that VeriT does not like the encoding of the implication.

**Comment by gebner** [comment]
Both examples you posted work for me.  Can you post the error message you get when running the first one?

**Comment by shetzl** [comment]
When I do
```
val F = fof"a=b -> f(a)=f(b)"
VeriT isValid F
```
on the CLI, I get
```
java.io.IOException: veriT exited with value 255:                                                                                          
veriT stable2016 - the SMT-solver veriT (UFRN/LORIA).                                                                                      
success                                                                                                                                    
success                                                                                                                                    
success                                                                                                                                    
success                                                                                                                                    
success                                                                                                                                    

  at at.logic.gapt.utils.runProcess$.apply(runProcess.scala:21)
  at at.logic.gapt.provers.verit.VeriT.isValid(VeriT.scala:21)
  at at.logic.gapt.provers.Prover.isValid(provers.scala:29)
  at at.logic.gapt.provers.Prover.isValid$(provers.scala:29)
  at at.logic.gapt.provers.verit.VeriT.isValid(VeriT.scala:14)
  ... 26 elided
```
Calling `SmtLibExporter( Sequent( Nil, F::Nil ))` returns the string
```
(set-logic QF_UF)
(declare-sort t1 0)
(declare-fun f1 () t1)
(declare-fun f2 (t1) t1)
(declare-fun f3 () t1)
(assert (not (=> (= f3 f1) (= (f2 f3) (f2 f1)))))
(check-sat)
```
When I send this string to via stdin to VeriT on bash I get
```
veriT stable2016 - the SMT-solver veriT (UFRN/LORIA).
(set-logic QF_UF)
(declare-sort t1 0)
(declare-fun f1 () t1)
(declare-fun f2 (t1) t1)
(declare-fun f3 () t1)
(assert (not (=> (= f3 f1) (= (f2 f3) (f2 f1)))))
(check-sat)success
success
success
success
success
(error "smt2_term: unresolved symbol > on line 6")
```

**Comment by gebner** [comment]
Okay, this is a hard one.  I successfully tried the SMT-LIB benchmark you posted on my laptop, the compile server, and the experiments machine (all upgraded to veriT 2016).  I also tried it on a freshly compiled veriT on a fresh install of Ubuntu trusty (both 32- and 64-bits), again no problems.

I see two possibilities:
 * Your machine has a really uncommon configuration.  Can you tell me what distribution you are on?  The error looks like a lexing error.  Can you post the output of `lex --version`?
 * The veriT guys changed the tarball after release to fix this bug.  Can you try downloading the tarball again?  Mine has a sha256sum of `8bec735297065068d9868da1250f45bccf36dbf9e1029f8b074f62f06323773f`.

I can also look into it when you're back in Vienna.

**Comment by shetzl** [comment]
Interesting ;-) I am using OpenSuSE Leap 42.2, lex --version says `flex 2.5.37`, and the sha256sum of the tarball is the same. Let's look at this next week when I am back.

**Comment by gebner** [comment]
@shetzl We can still meet up if you need the issue fixed this week.  Otherwise let's postpone it for three weeks.

**Comment by shetzl** [comment]
Yes... I forgot about this one. Let's postpone it until I come back. In any case, it seems to be more of a VeriT / SuSE issue than a gapt issue.

**Comment by shetzl** [comment]
I am closing this since it is not a gapt issue but one of VeriT/SuSE.
