### ISSUE TITLE
Acyclicity condition in Skolem definitions

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#628]
Currently a Skolem definition is just an element of a map s_i → λx_1 .. λx_n Qy φ(x_1, .., x_n, y). We need to check that s_i does not occur in φ. Otherwise proofs of invalid sequents are possible, e.g., the following:
```
val q1 = ReflexivityAxiom( fot"c" )
val q2 = NegLeftRule( q1, fof"c=c" )
val q3 = ExistsSkLeftRule( q2, fot"c", fof"?y -c=y" )

val p1 = LogicalAxiom( fof"u = v" )
val p2 = WeakeningLeftRule( p1, fof"c=u" )
val p3 = EqualityLeftRule( p2, Ant(0), Ant(1), Abs( fov"x", le"x = v" ) )
val p4 = NegRightRule( p3, Ant(0) )
val p5 = NegRightRule( p4, Ant(0) )
val p6 = ExistsRightRule( p5, fof"?y - c = y", fot"u" )
val p7 = ExistsRightRule( p6, fof"?y - c = y", fot"v" )
val p8 = ContractionRightRule( p7, Suc(1), Suc(2) )
val p9 = ForallRightRule( p8, fof"!y u=y", fov"v" )
val p10 = ForallRightRule( p9, fof"!x !y x = y", fov"u" )

val r = CutRule( p10, q3, fof"?y - c = y" )
```
A version of this proof without equality can be given by replacing = by λ x λ y. (P(x) ⊃ P(y)) & (P(y) ⊃ P(x)) and adjusting for the required changes.

**Comment by gebner** [comment]
This is expected, LK proofs do not perform any kind of global validation.  Other cyclic definitions do not cause errors either.  The only reasonable way to check them is via a context (and there this proof would not check).
