### ISSUE TITLE
unexpected beta-reduction

### ISSUE THREAD

**Issue by MarielleLouise** [gapt/gapt#659]
It seems that in a special case the normalization of terms is not as expected, for example:

`val nat = TBase( "nat" )`
`val x = Var( "x", nat )`
`val y = Var( "y", nat -> nat )`
`val fine = normalize(App(normalize(App(Abs(y,y),y)),x)) // is the term y(x) of type nat`
`val notfine = normalize(App(App(Abs(y,y),y),x)) // is the term y of type nat>na`

Here `notfine` is normalized to y, where it should be y(x).

**Comment by gebner** [comment]
Thank you for reporting this critical issue!
