### ISSUE TITLE
PrimRecFunBatch allows non-terminating definitions

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#673]
```scala
implicit val ctx: MutableContext = MutableContext.default()
ctx += InductiveType( "nat", hoc"0: nat", hoc"s: nat>nat" )
ctx += PrimRecFun(
  hoc"f:nat>nat" -> Seq( "f 0 = 0", "f (s x) = g (s x)" ),
  hoc"g:nat>nat" -> Seq( "g 0 = 0", "g (s x) = s (f (s x))" ) )

// does not terminate:
// ctx.normalize( le"f (s x)" )
```

**Comment by gebner** [comment]
@jannikvierling @Ermine516 just bugged me on gitter about the following kind of definition:
```
phi (s n) (s k) 0 = ...
```

Any idea on how to handle that?

**Comment by gebner** [comment]
@Ermine516 Is there a chance you could get by with just `phi n (s k) 0`?

**Comment by Ermine516** [comment]
That's the annoying part, I am sure that would conflict with the distinction between  phi 0 (s k) 0  , phi (s n) (s k) 0 , and others

**Comment by Ermine516** [comment]
If you look at gradedstrictmonotonesequenceschema.scala every proof definition will show up in the characteristic formula inductive definition.

**Comment by Ermine516** [comment]
These definitions are not really PR in the strict sense the context requires

**Comment by jannikvierling** [comment]
If I understand correctly you want to define the function `phi` somewhat as below. But this does not even yield a total function.
```
phi 0     (s k) 0 = t1(k),
phi (s n) (s k) 0 = t2(n,k).
```
So my first idea is to define a total extension by repeated case distinction as follows
```
phi_0 n k     0 = phi_1(n, k),
phi_0 n k (s l) = ???,

phi_1 n     0 = ???,
phi_1 n (s k) = phi_2(n, k),

phi_2     0 k = t1(k),
phi_2 (s n) k = t2(n,k),

phi n m l = phi_0 n m l.
```
Is this possible in your formalism?

**Comment by Ermine516** [comment]
Thanks @jannikvierling  you brought up a point I have not really thought about till now. Yes, the function is not total in some sense. These definitions are coming from the cut structure of a schematic proof. Some which definitions are ok there being that the proof structure is not expected to be primitive recursive in a strict sense. These definitions we are discussing above come from the extraction of the cut structure as inductive definitions which are mutually dependent and together make a total function. Furthermore, they are multiplied by possible configurations of cut ancestors. that is why functions have names like phiATFTTSTFF. While it is possible to put all these functions together into one giant primitive recursive function (one of my proof consist of 36 functions in total) I am not sure there is a benefit in doing so. One, information is lost in the process, two, such a transformation is nontrivial and will be ery complex to write. In the end, what I see is that writing these definitions as primitive recursive functions is the real issue, maybe they need to be set as a special type of PR function. 

On a further note,  simple primitive recursion does not even work for one of my examples being that the arguments are lexicographically ordered.

**Comment by jannikvierling** [comment]
One way to solve this would be to just add reduction rules to the context, without the requirement that these reduction rules form a primitive recursive definition. @gebner What do you think about this? Is it acceptable to add arbitrary reduction rules to the context?

**Comment by gebner** [comment]
Maybe I should explain some of the original motivation behind the Context structure.  I intended Contexts to be sound by construction.  That is, there is a standard model for the Context (where e.g. the inductive types are interpreted as expected) and in this model all the function definitions are satisfied and the proof names are all satisfied as well.  In particular, you couldn't prove false.  (Well, as long as you only use a reasonable set of Updates to construct the Context.)

Alas, this didn't work out---mainly because nobody cares.  And soundness doesn't really matter for the proof theory applications we're doing.

But that's where these checks came from: to make sure that the definitions are sound (in some sense).  And these checks *do* catch bugs, so I'd like to keep them when possible.

Concretely, I'm happy to drop `PrimRecFunBatch` for something less checked (ideally changing the name to something more descriptive as well in the process).  I think we should still make some basic sanity checks, such as ensuring that we only define reductions for new constants, that the definitions are linear (i.e., (type-)variables on the rhs already occur on the lhs), and that both sides of the definition have the same type and only use defined constants.

**Comment by jannikvierling** [comment]
I really like the idea of the context being sound by construction, I just think that for our needs this is to rigid. Moreover the fact that new updates and facets can be added to the context makes it easy to extend the context in such a way that unsound constructions are possible.

However I don't think that we should weaken the conditions imposed by `PrimRecFun` (or `PrimRecFunBatch`), since the concept of definitions being primitive recursive is quite clear and we can thus provide stronger soundness assertions.

**Comment by quicquid** [comment]
Not sure how many cases it captures but could you define orders and use well founded recursion on that order?

**Comment by Ermine516** [comment]
@jannikviering I agree, though I still have not looked at the reduction code. I guess next week. Concorning order, I am not sure I want to make that assumption yet. I have recent work where the well ordering isn't so trivial, I. E it looks non-well ordered from the perspective of the proof symbols

**Comment by Ermine516** [comment]
I checked the changes, everything works now and none terminating functions are no longer needed. :)
