### ISSUE TITLE
Inductive types are unsound

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#675]
Short proof of false:
```scala
import at.logic.gapt.proofs.gaptic._
implicit val ctx = MutableContext.default()
ctx += InductiveType( "conat", hoc"s: conat>conat" )
Lemma( hols":- false" ) {
  induction( hov"x: conat" )
  prop
}
```

Beautifully rendered via prooftool:
![unsound_induction](https://user-images.githubusercontent.com/313929/34732136-9ca1117c-f564-11e7-96c4-806e7f4cd800.png)

**Comment by loewenheim** [comment]
Yeah, not gonna lie, that's pretty hilarious.

**Comment by loewenheim** [comment]
More seriously, though: is the problem that `conat` isn't, strictly speaking, an inductive data type?

**Comment by gebner** [comment]
The main ingredient for this bug is that all types in gapt are implicitly nonempty, that is, you can prove `∃ (x: t) x=x` for every type `t`--simply using exists-right with the variable `x: t`.  (The same property exists in other HOL-based proof systems like Isabelle, etc.)

Now `conat` is a perfectly fine inductive type, it's just that it is semantically an empty type--the smallest set closed under `s` is empty after all.  This is where the contradiction comes from: the induction rule says `conat` is empty, while exists-right says conat is nonempty.

We just need to ensure that all defined inductive types are indeed nonempty, that is, they have a constructor without recursive occurrences of the inductive type.

**Comment by loewenheim** [comment]
Yeah, my thinking was along the lines of "it's not inductive because there are no 'ground' instances", but that might be inaccurate. In any case, it leads to the same solution that you proposed.
