### ISSUE TITLE
LKToND introduces excluded middle for equality-left rule

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#683]
```scala
val lk = ProofBuilder.
  c( LogicalAxiom( hof"P(a)" ) ).
  u( WeakeningLeftRule( _, hof"a=b" ) ).
  u( EqualityLeftRule( _, hof"a=b", hof"P(a)", hof"P(b)" ) ).
  qed
val nd = LKToND( lk )
```
Now `nd` contains excluded middle (unnecessarily).  We should probably handle this using the usual `→`-introduction+elimination trick.

**Comment by mschlaipfer** [comment]
The same with DefinitionLeftRule. Both fixed in https://github.com/gapt/gapt/commit/e76b24e42479f3fc2cae8d89bc87c731dd9d9d79.
