### ISSUE TITLE
LKToND: unhygienic handling of replacement contexts

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#688]
```scala
val lk = ProofBuilder.
  c( LogicalAxiom( hof"P(x)" ) ).
  u( WeakeningLeftRule( _, hof"x=y" ) ).
  u( EqualityLeftRule( _, Ant( 0 ), Ant( 1 ), le"^x (P x: o)".asInstanceOf[Abs] ) ).
  qed
LKToND( lk )
```

**Comment by mschlaipfer** [comment]
Our `EqualityElimRule` needs a `replacementContext` I suppose?

**Comment by gebner** [comment]
The issue here is the following, LKToND translates the equality inference above (on the formula `P(x)` with the replacement context `λx P(x)`) to an equality inference on `P(x) -> P(x)`.  In this process, we also attempt to rewrite at the occurence of `P(x)` that comes from the succedent since it happens to have the same variable that also occurs as the bound variable of the replacement context.

If we α-renamed the bound variable in `λx P(x)` to e.g. `λy P(y)`, then we wouldn't have this problem.  That's why I called unhygienic (correctly handling different identifiers that happen to have the same name is called "hygiene" in macro expansion / metaprogramming, that's where I took the name from).

Refactoring EqualityElimRule to take a replacementContext is probably a good idea (so that it is consistent with the rule in LK), but it wouldn't fix this issue.

I see two possible solutions:
 1) Rename the bound variable in the replacement context if it is a free variable of the succedent formula.
 2) Use a different translation where the EqualityElimRule rewrites only `P(x)` instead of `P(x) -> P(x)`.  You should be able to do this with 1 ImpIntro, 1 ImpElim, 1 EqualityElim, and 2 LogicalAxioms.

I think 2 is cleaner.

**Comment by mschlaipfer** [comment]
Wasn't aware of the origin of "hygiene", thanks. 

1. was my first thought, but refrained from doing that. i guess it would require a `DefinitionRule`.

I can't seem to find the proof you suggest for 2. Are we thinking of the same `P(x)` out of the two in the implication? The unwanted capture happens in the consequent.
