### ISSUE TITLE
New cut-reduction architecture

### ISSUE THREAD

**Issue by jannikvierling** [gapt/gapt#692]
### Requirements

 - Cut-reduction should be terminating.
 - It should not fail (or loop) in the presence of rules that can prevent cut-elimination:
   - Theory axioms
   - Induction inferences
   - Definition rules
   - Skolem inferences
   - Equational rules
  - It should be easy-ish to implement different strategies, or do partial cut-elimination:
    - Uppermost first
    - Maximum grade first
    - Do not reduce propositional cuts
    - Reduce to ACNFtop
  - Performance should be better than it is now

**Comment by shetzl** [comment]
Unfortunately we forgot to discuss this at the last gapt meeting... At the next gapt meeting we should discuss what we want from our implementation of reductive cut-reduction and which, if any, changes this requires.

**Comment by jannikvierling** [comment]
Fixed by #695
