### ISSUE TITLE
User manual has "list of corrections" section

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#694]
https://www.logic.at/gapt/downloads/gapt-user-manual.pdf, page 3.

Didn't we decide to leave out this page?

Although this will probably solve itself when we upgrade clogic92 to bionic in 2 months.

**Comment by jannikvierling** [comment]
Latex reports a warning when compiling with an outdated fixme-package. I have installed the new version of fixme on clogic92, and updated the user manual.
