### ISSUE TITLE
Expansion proof viewer does not support merge

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#706]

**Comment by quicquid** [comment]
A merge is not covered by DisplayExpansion proof. An underlying problem is that the invariant that merge does not appear in an ET after `eliminateMerges` is called. E.g.

    eliminateMerges( nTape3.expansion_proof ).subProofs.collect( { case x @ ETMerge( _, _ ) => x } ).isEmpty

is false.

**Comment by quicquid** [comment]
The culprit is the `( Merges(t0), s : ETSkolemQuantifier )` case where t0 may contain weakenings that are not filtered out. Fixing it.
