### ISSUE TITLE
Inexhaustive matches on expansion trees

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#709]
Several expansion tree algorithms are currently not defined for some inputs.

* The `check` method in the `Checkable` trait is not defined for merge nodes. Should merge nodes be considered valid in this context?
* The `mapDefinedAtom` method in `atomicExpansionET` is only defined for definition nodes that are immediately followed by atoms and weakenings.
* `gatherOccs` in `nonProofTheoreticSkolemTerms` is not defined for definition nodes.
* `ExpansionProofToMG3iViaSAT` contains a match that fails on definition nodes.
* The `back` and `unguard` methods in `PredicateReductionHelper` is not defined for definition, Skolem quantifier, or strong quantifier nodes.
* `generateSuccessorTrees` in `Minimizer` is not defined for merge nodes. I'm not completely sure whether the obvious solution is sound.
* `extractInstances` is not defined for merge nodes, but the fix is obvious.

I would like to make the `ExpansionTree` trait sealed, but the inexhaustive matches keep me from doing that. How should I proceed?

**Comment by gebner** [comment]
> * The `check` method in the `Checkable` trait is not defined for merge nodes. Should merge nodes be considered valid in this context?

Yep.

> * The `mapDefinedAtom` method in `atomicExpansionET` is only defined for definition nodes that are immediately followed by atoms and weakenings.

Should probably recurse through the definition otherwise.  Failure is also an option.

> * `gatherOccs` in `nonProofTheoreticSkolemTerms` is not defined for definition nodes.

Just recurse, like in the strong quantifier case.

> * `ExpansionProofToMG3iViaSAT` contains a match that fails on definition nodes.

Call addClause twice, with the following proofs: `φ ⊢ ψ` and `ψ ⊢ φ`, where `φ` is the defined formula, and `ψ` is its definition.

> * The `back` and `unguard` methods in `PredicateReductionHelper` is not defined for definition, Skolem quantifier, or strong quantifier nodes.

Just fail.

> * `generateSuccessorTrees` in `Minimizer` is not defined for merge nodes. I'm not completely sure whether the obvious solution is sound.

I don't see how the obvious solution could be unsound.

> * `extractInstances` is not defined for merge nodes, but the fix is obvious.

Please fix it.

**Comment by loewenheim** [comment]
> I don't see how the obvious solution could be unsound.

What I mean is this: Suppose we have a node `ETMerge(l, r)`, where `l` and `r` have the instances `A, B` and `A, C`, respectively. Reducing the merge leads to a node with instances `A, B, C`, which means that the successor trees have instances `A,B`, `A,C`, and `B,C`.

By contrast, if we first apply `generateSuccessorTrees` and then reduce the merges, we obtain trees with the instances `A,B`, `A,C`, and `A,B,C`.

**Comment by loewenheim** [comment]
> Call addClause twice, with the following proofs: `φ ⊢ ψ` and `ψ ⊢ φ`, where `φ` is the defined formula, and `ψ` is its definition.

Where do I get these proofs from? Also, I neglected to mention that the function also fails on Skolem quantifier nodes.

**Comment by gebner** [comment]
> By contrast, if we first apply generateSuccessorTrees and then reduce the merges, we obtain trees with the instances A,B, A,C, and A,B,C.

I don't see how this is a problem?  In either case we reach a minimal expansion proof, right?

**Comment by gebner** [comment]
> > Call addClause twice, with the following proofs: φ ⊢ ψ and ψ ⊢ φ, where φ is the defined formula, and ψ is its definition.
>
> Where do I get these proofs from?

Something like `DefinitionRightRule(LogicalAxiom(φ), Suc(0), ψ)` and similarly for the other case.

> Also, I neglected to mention that the function also fails on Skolem quantifier nodes.

Skip or fail, this case shouldn't be reached.

**Comment by loewenheim** [comment]
> I don't see how this is a problem? In either case we reach a minimal expansion proof, right?

Well, if the intention is to enumerate all expansion trees with fewer instances, we are missing some.

**Comment by gebner** [comment]
> Well, if the intention is to enumerate all expansion trees with fewer instances, we are missing some.

I think I didn't completely understand the intention behind your example.  So yes, it is of course possible that eliminating merges could result in an expansion proof where we can remove more instances.  (This requires non-prenex formulas though.)

The minimization algorithm still returns minimal expansion proofs in the following sense: it returns minimal subtrees where no weak quantifier inference can be removed such that the deep formula remains valid.

I think that is a perfectly fine result.  After all, there are few operations on expansion trees that could allow us to further reduce the number of instances in some cases, such as applying a substitution to the expansion proof, or copying instances used in one branch to another, etc.

I further believe that it is important for the minimization algorithm to handle merge nodes.  There are quite a few cases where merges cannot be eliminated (multiple Skolem nodes with different Skolem functions, definition nodes vs. normal nodes).  These special cases are used in an essential way by the deskolemization algorithm.  Martin also recently ran into this situation with the nTape proof from his thesis.

**Comment by loewenheim** [comment]
in that case, this is fixed as of f107950484ae4b2c1965805a4e70f49503056533 :)
