### ISSUE TITLE
LaTeX logging

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#71]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on February 15, 2010 13:13:35_

We usually deal with complicated data like formulas and trees, which are
hard to visualize using UTF-8 output.

So I propose that we connect and extend Tomer's work on LaTeX output with
our logging facilities, so that we can log data using LaTeX.

Imagine debugging an algorithm on proof trees, and having a log that really
contains nicely formated proof trees in the usual format, instead of a
large string of symbols which has to be decoded manually before its meaning
becomes clear to the user.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=71_

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:15:31_

**Labels:** Component-Parsing

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on October 03, 2011 08:46:41_

Cvetan has just shown me that he automatically generates latex PDF of schematic clause sets... If I understood correctly, he uses Tomer's work on LaTeX output, and additionally calls "pdflatex" from within GAPT...

Perhaps Cvetan's implementation is relevant to this issue...

**Cc:** cdunc...@gmail.com shaoli...@gmail.com

**Comment by shetzl** [comment]
adding CCs from google code: @frehn @shaolintl

**Comment by gebner** [comment]
This discussion seems to be open-ended brainstorming from a few years ago, concerning issues that no longer seem relevant.  If you have any concrete proposals/problems, please feel free to open another issue.
