### ISSUE TITLE
prover9 proof parse error

### ISSUE THREAD

**Issue by alanruttenberg** [gapt/gapt#719]
Hi,
Just starting to look at GAPT. Looks great! 
Baby steps tried to parse a prover9 proof using the API. Took the contents from prover9 example [x2.out](https://github.com/theoremprover-museum/prover9/blob/master/source/prover9.examples/x2.out) but got a java exception::

```Java exception 'java.io.IOException: prooftrans ivy exited with value 1:
;; ============================== prooftrans ============================
;; Prover9 (32) version Apr-2006A, Apr 2006.
;; Process 28593 was started by mccune on cleo.thornwood,
;; Fri May  5 09:04:05 2006
;; The command was "../bin/prover9 -f x2.in".
;; ============================== end of head ===========================
unknown: 27, unknown

Fatal error:  term_to_just, unknown justification

'.
```

**Comment by gebner** [comment]
Unfortunately this error already happens in the `prooftrans` tool bundled by Prover9, which we use as a preprocessing step:
```
$ curl -s https://raw.githubusercontent.com/theoremprover-museum/\
prover9/master/source/prover9.examples/x2.out | prooftrans
============================== prooftrans ============================
Prover9 (32) version Apr-2006A, Apr 2006.
Process 28593 was started by mccune on cleo.thornwood,
Fri May  5 09:04:05 2006
The command was "../bin/prover9 -f x2.in".
============================== end of head ===========================
============================== end of input ==========================
unknown: 27, unknown
Fatal error:  term_to_just, unknown justification
Fatal error:  term_to_just, unknown justification
(23) Failed writing body
```

However, if you run prover9 (2009A) yourself on `x2.in` then it should work (with the latest commit on master).

**Comment by alanruttenberg** [comment]
OK, thanks for responding. 
As it happens it looks like I won't be using gapt for the moment.

Background

I'm already using another language on the JVM (armed bear common lisp). There's native support for calling JAVA code, but I timed out while trying to understand how to work with Scala using just calls to Java methods.
 
I've written enough to use 3 reasoners: prover9, z3, vampire. My source is very similar to common logic, and I generate the inputs to the reasoners. I parse minimal information from the proofs now, just the names of the formula that were used by the proof. The idea of me tossing my current code that generates input and parses proofs and using gapt instead, gaining access to a number of other reasoners, is appealing. 

I don't usual engage with details of the proof - I'm typically interested in the answer. However, since I often need to debug my formulas, any insights that can be gained from proofs can be useful.

Anyways, nice to see projects like this :-)
