### ISSUE TITLE
ExpansionProofToLKProof does not introduce induction inferences

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#736]
ExpansionProofToLKProof transforms expansions of `∀X (X → X)` to cuts. In my opinion it would be natural to transform expansions of induction axioms like `∀X (X(0) ∧ ∀x0 (X(x0) → X(s(x0))) → ∀x X(x))` to induction inferences. This does currently not happen, see e.g.:
```
induction.associativity.p.conclusion
val Right( q ) = ExpansionProofToLK( LKToExpansionProof( induction.associativity.p ) )
q.conclusion
```

**Comment by gebner** [comment]
Make sure that the context is in implicit scope, e.g. by `import induction.associativity._`.

**Comment by shetzl** [comment]
Thanks!
