### ISSUE TITLE
DLS Algorithm does not eliminate quantifier for nullary variables 

### ISSUE THREAD

**Issue by jvierling** [gapt/gapt#746]
Evaluating `witnessForSecondOrderQuantifierElimination( hof"?X X" )` yields `Success((Substitution(),∃X X))`. The expected behavior is that the quantifier is eliminated.

**Comment by jvierling** [comment]
This issue is probably due to the restriction on the number of arguments in `StrictSecondOrderRelationVariable`.

**Comment by fachammer** [comment]
should be fixed by 87240da9

**Comment by jvierling** [comment]
:+1:
