### ISSUE TITLE
No assembly created

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#748]
Hello, I just tried to create an assembly of gapt at the master (tag v2.15.1) but it seems the gapt jar file is not created. The only jar file created is `./target/scala-2.13/root-assembly-2.15.1.jar` which is still lacking its manifest. The tests run without an error. Do you know what could have gone wrong?

[log.txt](https://github.com/gapt/gapt/files/4509362/log.txt)

**Comment by jvierling** [comment]
This is an error in the `include.sh` file, where during the update to scala 2.13 I forgot to update the scala version. The line
```
for _jar in "$basedir/gapt-$gapt_version.jar" "$basedir/target/scala-2.12/root-assembly-$gapt_version.jar"; do
```
should be
```
for _jar in "$basedir/gapt-$gapt_version.jar" "$basedir/target/scala-2.13/root-assembly-$gapt_version.jar"; do
```
I'll will soon provide a fix.

**Comment by jvierling** [comment]
@quicquid I could not reproduce the missing manifest file issue. On my system it is generated as `META-INF/MANIFEST.MF`

**Comment by quicquid** [comment]
Thank you, the fix to the include did the trick!

Sorry for being confusing about the manifest - I called:

    [user@pc gapt]$ java -jar target/scala-2.13/root-assembly-2.15.1.jar 
    no main manifest attribute, in target/scala-2.13/root-assembly-2.15.1.jar

The manifest file is there, it's just not part of that jar.

**Comment by jvierling** [comment]
You could run the CLI from the GAPT root as follows:
```
java -cp .:target/scala-2.13/root-assembly-2.15.1.jar gapt.cli.CLIMain
```

**Comment by jvierling** [comment]
5c3a4dc8436c456c2b34bff7a661a78810177299 sets `CLIMain` as the entry point. It is now possible to run GAPT with `java -jar target/scala-2.13/root-assembly-2.15.1.jar `.
