### ISSUE TITLE
String interpolation of formula.toString gives unexpected result

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#749]
Hello,

Please consider the following code fragment:

    scala> val f = hof"A ∧ B"
    f: gapt.expr.formula.Formula = A ∧ B
    
    scala> val g = hof"${f.toString}"
    g: gapt.expr.formula.Formula = 'A ∧ B':o
    
    scala> g match { case Atom(c, _) => c }
    res4: gapt.expr.Expr = 'A ∧ B':o

I'm trying to create a formula A ∧ B and parse it back from its string representation. Following the [API documentation](https://www.logic.at/gapt/api/gapt/expr/Expr.html#toRawString:String) I would expect the same formula but instead I get a constant with the name "A ∧B". Obviously I'm doing something wrong here - can you tell me how to do it properly? Thanks!

**Comment by gebner** [comment]
@quicquid This is by design: if `s` is a string, then the anti-quotation `hof"$f"` inserts `f` as an identifier (variable or constant).  This is just like when `e` is an expression, then `hof"$e"` inserts the expression `e`.

You're looking for the `parseFormula` function:
```scala
BabelParser.parseFormula(hof"A ∧ B".toString)
```

**Comment by quicquid** [comment]
Thank you @gebner that was exactly what I was looking for!
