### ISSUE TITLE
Releases 2.14 and later do not compile with Java 11

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#763]
I have tried to compile the releases 2.14 upwards to 2.15.4 with the latest sbt and OpenJDK 11 (Linux). The compile fails with scala errors of the form "polymorphic expression cannot be instantiated to expected type;" (Log: [out2.15.3.txt](https://github.com/gapt/gapt/files/8865305/out2.15.3.txt) tested with a fresh copy and coursier cache). An upgrade to OpenJDK 17 resolves the problem. Since JDK 11 is pretty dated and the next LTS release is JDK 17, I'd propose to just raise the minimum requirements of GAPT accordingly.

**Comment by jvierling** [comment]
I can't reproduce the errors with OpenJDK 11. Could you send the output of a failing SBT session with debug output (options `-v -d`)?  Using OpenJDK 17 for GAPT 2.15.4 is not recommended because we use Scala 2.13.1 and OpenJDK 17 requires Scala 2.13.6.

**Comment by gebner** [comment]
> Using OpenJDK 17 for GAPT 2.15.4 is not recommended because we use Scala 2.13.1 and OpenJDK 17 requires Scala 2.13.6

I guess we should upgrade then.  But as far as I can tell, current GAPT master works just fine with OpenJDK 17.

(On the other hand, our external prover interfaces have completely bitrotten away.  Apparently the Vampire, E, and veriT interfaces are broken with the latest versions of the provers now.)

**Comment by quicquid** [comment]
@jvierling This is a log from my computer:
[log.txt](https://github.com/gapt/gapt/files/8881188/log.txt)
[stdout.txt](https://github.com/gapt/gapt/files/8881189/stdout.txt)

If it can't be reproduced then I think it's best not to worry about it too much since I've managed to get it to run with JDK 17. 

@gebner agree to the bitrot - I might have some time to investigate the E and vampire interfaces a bit over the summer. veriT switched to the [alethe format](https://arxiv.org/abs/2107.02354) and needs a more drastic change unfortunately.

**Comment by jvierling** [comment]
The development branch is now using Scala 2.13.8 and is therefore compatible with JDK 17.  As soon as the prover interfaces are updated I will release a new version GAPT.

**Comment by gebner** [comment]
> I will release a new version GAPT.

I'm looking forward to it.  From what I can tell, no PRs made since 2020 have made it into a release.  (I only noticed this just now when doing `git log master..develop`.)  Was that intentional?

**Comment by jvierling** [comment]
Yes, that was intentional.
