### ISSUE TITLE
Set of Support Refinement

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#79]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on August 07, 2010 11:50:31_

The set of support refinement should be added to ATP:
1) The extension to the Refinement interface should be created, maybe by having all clauses in the set of support appearing at the beginning of the queue and therefore not being used among themselves to resolve.
2) We need to be able to decide the set of support at the beginning. Maybe in the clause insertion syntax we also need to specify if the clause is an axiom of the theory so we can later use this information automatically to include this clause in the set of support.

Bruno, you expressed some wish to have this feature. Do you have any thing to say about this issue? Do you want to implement this?

_Original issue: http://code.google.com/p/gapt/issues/detail?id=79_

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 09:12:11_

**Owner:** bruno...@gmail.com  
**Labels:** -Priority-Medium Priority-Low

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 12:07:33_

**Labels:** Type-Feature

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:39:01_

**Labels:** Component-TheoremProvers

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 22, 2011 07:52:05_

Not essential...

**Status:** WontFix

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 12, 2011 05:32:05_

**Blocking:** 173

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on September 12, 2011 05:32:32_

**Status:** New  
**Owner:** ---

**Comment by gebner** [comment]
No longer relevant since ATP was removed.
