### ISSUE TITLE
Multiset equals between sequents does not work properly

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#95]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 15, 2010 18:42:00_

adding the following test to LKTest fails

"MultisetEquals" should {
    "compute correctly in multiset equality of the empty sequent and a sequent without succedent" in {
      (Sequent(f2::Nil,Nil) multisetEquals Sequent(Nil,Nil)) must beEqual (false)
    }
  }

_Original issue: http://code.google.com/p/gapt/issues/detail?id=95_

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 21, 2010 01:48:14_

See my latest comments to issue #68 .

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 21, 2010 06:22:34_

So the test above does not describe multiset equality? I did not look on other definitions but can A :- be multiset equal :- ?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 21, 2010 06:29:35_

The test should not fail, you are right! But before I go and debug multisetEquals, I want to be sure of the semantics of equals. If equals is already multiset equality, why should we debug multisetEquals (and not just replace it by equals, and debug that, if it fails)?

Look at LKTest.scala, lines 466-471. Apparently equals is already multiset equality. What do you think?

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 21, 2010 07:34:47_

you are completely right! I have just checked equals and it is indeed multiset equality done in a different way than the method multisetEquals. I think we should move the code to multisetEquals and call this method in equals. What do you think?

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on December 23, 2010 05:00:33_

I think that's a good idea! Could you implement this change?

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on December 23, 2010 06:34:57_

ok, I will do it. A note for myself, also change the calls for setEqual in ATP to multisetEqual once it is fixed

**Owner:** shaolintl

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on August 11, 2011 04:05:48_

Issue 68 has been merged into this issue.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on August 11, 2011 04:07:05_

Sequent is going to change to be a set of occurrences. When this change is done then equals could be set equals and multiset equals should be different. Once the sequent new code is checked in, this change should be done.

**Blockedon:** 117

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:36:56_

**Labels:** Component-LogicalDataStructures

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 23, 2011 13:43:53_

**Labels:** Milestone-Release2.0

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on August 24, 2011 04:03:17_

Sequent multisetEqual and setEqual should be implemented for Sequents. We need to think if equals should be any of them or a syntactic equals or a pointer equals. I think it should be multiset equals which is the normal theoretical equality of sequents in our calculus.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on November 10, 2011 06:20:51_

**Owner:** ---

**Comment by gebner** [comment]
Closing this issue as it seems to have been resolved a few years ago, judging from the comments.  The current situation is that both FSequent and Sequent have multiset comparison operators (multiSetEquals and syntacticMultisetEquals, resp.).  The default equality for FSequents is list-equality, for Sequents it is pointer equality.  As Sequents contain (presumably unique) FormulaOccurences, and will probably be refactored during the upcoming calculus clean-up, we should probably leave Sequent equality as it is for the moment.
